/*
 * Copyright 2026 The flow-as-code Authors
 * SPDX-License-Identifier: Apache-2.0
 */
// The shared scaffold generator. What it emits end to end is asserted where it
// is used (packages/cli/src/cli.test.ts compiles the CLI's output with
// tsc, and packages/studio/tests/exportParity.test.ts compares the
// studio's bytes against the CLI's). What is pinned here is the contract that
// makes sharing it safe: it is pure, it is deterministic, and its one path
// calculation agrees with node's.

import { readFileSync } from "node:fs";
import { relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import type { FlowDoc } from "@flow-as-code/core";

import { CDK_SCAFFOLD_FILE, cdkScaffold, referencedNames, sourceForDepth } from "./scaffold.js";

const DEMO = new URL("../../../conformance/demo/appointment-line.flowdoc.json", import.meta.url);
const demoDoc = (): FlowDoc => JSON.parse(readFileSync(DEMO, "utf8")) as FlowDoc;

describe("cdkScaffold", () => {
  it("is byte-stable for the same input", () => {
    const once = cdkScaffold({ docs: [demoDoc()], source: "." });
    expect(cdkScaffold({ docs: [demoDoc()], source: "." })).toBe(once);
    // A neutral generator banner, not this repo's licence header: the file
    // lands in a user's project and is theirs.
    expect(once.startsWith("// Generated by `flow-cli emit --target cdk`")).toBe(true);
    expect(once).not.toContain("SPDX-License-Identifier");
    expect(once.endsWith("\n")).toBe(true);
  });

  it("does not depend on the order the documents were read", () => {
    const a = { ...demoDoc(), name: "a-line" };
    const b = { ...demoDoc(), name: "b-line" };
    expect(cdkScaffold({ docs: [a, b], source: "." })).toBe(
      cdkScaffold({ docs: [b, a], source: "." }),
    );
  });

  it("writes a TODO for exactly the reference types the set uses", () => {
    const scaffold = cdkScaffold({ docs: [demoDoc()], source: "." });
    for (const type of ["hours", "lambda", "queue"]) {
      expect(scaffold).toContain(`TODO: bind ${type}`);
    }
    for (const type of ["lex", "prompt"]) {
      expect(scaffold).not.toContain(`TODO: bind ${type}`);
    }
    // FlowSet resolves module references itself, so a binder never has one.
    expect(scaffold).not.toContain("module: (name)");
    expect(scaffold).not.toContain("arn:aws:");
  });

  it("names the file it is written to", () => {
    expect(CDK_SCAFFOLD_FILE).toBe("flow-stack.ts");
  });

  it("unions the reference index with what the content actually holds", () => {
    const doc = demoDoc();
    doc.refs = [];
    expect([...referencedNames([doc]).keys()].sort()).toEqual(["hours", "lambda", "queue"]);
  });
});

describe("sourceForDepth", () => {
  it("agrees with node's path.relative for a nested output directory", () => {
    const docs = resolve("/srv/flows");
    for (const [depth, out] of [
      [0, docs],
      [1, resolve(docs, "infra")],
      [2, resolve(docs, "infra/cdk")],
    ] as const) {
      const expected = relative(out, docs).split("/").join("/");
      expect(sourceForDepth(depth)).toBe(expected === "" ? "." : expected);
    }
  });
});

describe("the module stays browser-safe", () => {
  it("imports no node builtin, because the studio bundles it", () => {
    const source = readFileSync(fileURLToPath(new URL("./scaffold.ts", import.meta.url)), "utf8");
    // Anchored: the scaffold it emits does import node:url, as a line inside a
    // string literal. Prettier puts this module's own imports at column zero,
    // so an import that would break the browser bundle still matches.
    expect(source).not.toMatch(/^import .*from "node:/m);
    expect(source).not.toMatch(/^import "node:/m);
  });

  it("emits a FLOW_DOCS that does not depend on the working directory", () => {
    const scaffold = cdkScaffold({ docs: [demoDoc()], source: ".." });
    expect(scaffold).toContain('const FLOW_DOCS = fileURLToPath(new URL("..", import.meta.url));');
    expect(scaffold).toContain('import { fileURLToPath } from "node:url";');
  });
});
