/*
 * Copyright 2026 The flow-as-code Authors
 * SPDX-License-Identifier: Apache-2.0
 */
// The shared scaffold generator. What it emits end to end is asserted where it
// is used (packages/cli/src/cli.test.ts compiles the CLI's output with
// tsc, and packages/studio/tests/exportParity.test.ts compares the
// studio's bytes against the CLI's). What is pinned here is the contract that
// makes sharing it safe: it is pure, it is deterministic, and its one path
// calculation agrees with node's.

import { readFileSync } from "node:fs";
import { relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { collectRefs, type FlowDoc } from "@flow-as-code/core";

import { CDK_SCAFFOLD_FILE, cdkScaffold, referencedNames, sourceForDepth } from "./scaffold.js";

const DEMO = new URL("../../../conformance/demo/appointment-line.flowdoc.json", import.meta.url);
const demoDoc = (): FlowDoc => JSON.parse(readFileSync(DEMO, "utf8")) as FlowDoc;

describe("cdkScaffold", () => {
  it("is byte-stable for the same input", () => {
    const once = cdkScaffold({ docs: [demoDoc()], source: "." });
    expect(cdkScaffold({ docs: [demoDoc()], source: "." })).toBe(once);
    // A neutral generator banner, not this repo's licence header: the file
    // lands in a user's project and is theirs.
    expect(once.startsWith("// Generated by `flow-cli emit --target cdk`")).toBe(true);
    expect(once).not.toContain("SPDX-License-Identifier");
    expect(once.endsWith("\n")).toBe(true);
  });

  it("does not depend on the order the documents were read", () => {
    const a = { ...demoDoc(), name: "a-line" };
    const b = { ...demoDoc(), name: "b-line" };
    expect(cdkScaffold({ docs: [a, b], source: "." })).toBe(
      cdkScaffold({ docs: [b, a], source: "." }),
    );
  });

  it("writes a TODO for exactly the reference types the set uses", () => {
    const scaffold = cdkScaffold({ docs: [demoDoc()], source: "." });
    for (const type of ["hours", "lambda", "queue"]) {
      expect(scaffold).toContain(`TODO: bind ${type}`);
    }
    for (const type of ["lex", "prompt"]) {
      expect(scaffold).not.toContain(`TODO: bind ${type}`);
    }
    // The demo references no module or flow outside itself, so the optional
    // methods are absent.
    expect(scaffold).not.toContain("module:");
    expect(scaffold).not.toContain("flow:");
    expect(scaffold).not.toContain("arn:aws:");
  });

  it("writes module() and flow() only for documents the set does not hold (C06)", () => {
    // One flow invoking a module and pointing a hook at a whisper flow, with
    // neither document in the set: both are the binder's to answer.
    const referrer = demoDoc();
    referrer.content.Actions = [
      ...referrer.content.Actions,
      {
        Identifier: "offer",
        Type: "InvokeFlowModule",
        Parameters: { FlowModuleId: "${cdref:module:callback-offer@prod}" },
        Transitions: {},
      },
      {
        Identifier: "hook",
        Type: "UpdateContactEventHooks",
        Parameters: { EventHooks: { CustomerWhisper: "${cdref:flow:whisper-line}" } },
        Transitions: {},
      },
      {
        Identifier: "show",
        Type: "ShowView",
        Parameters: { ViewResource: { Id: "${cdref:view:after-contact-work@1}" } },
        Transitions: {},
      },
      // The five FlowDoc 0.3 types, each the binder's (there is no document to
      // resolve them from), carried by the generic blocks that hold them
      // until their types are modeled.
      {
        Identifier: "task",
        Type: "CreateTask",
        Parameters: { Name: "Follow up", TaskTemplateId: "${cdref:tasktemplate:follow-up}" },
        Transitions: {},
      },
      {
        Identifier: "case",
        Type: "CreateCase",
        Parameters: {
          CaseTemplateId: "${cdref:casetemplate:billing}",
          CaseRequestFields: { "${cdref:casefield:priority}": "high" },
        },
        Transitions: {},
      },
      {
        Identifier: "assist",
        Type: "CreateWisdomSession",
        Parameters: { WisdomAssistantArn: "${cdref:assistant:agent-help}" },
        Transitions: {},
      },
      {
        Identifier: "sms",
        Type: "StartOutboundChatContact",
        Parameters: { SourceEndpoint: { Address: "${cdref:phonenumber:main-did}" } },
        Transitions: {},
      },
    ];
    referrer.refs = collectRefs(referrer.content);

    const alone = cdkScaffold({ docs: [referrer], source: "." });
    expect(alone).toContain("  module: (name, alias) => {");
    expect(alone).toContain("// Names referenced: callback-offer.");
    expect(alone).toContain("  flow: (name) => {");
    expect(alone).toContain("// Names referenced: whisper-line.");
    // A view is the binder's too, with the version the token pins.
    expect(alone).toContain("  view: (name, version) => {");
    expect(alone).toContain("// Names referenced: after-contact-work.");
    for (const [type, name] of [
      ["tasktemplate", "follow-up"],
      ["casetemplate", "billing"],
      ["casefield", "priority"],
      ["assistant", "agent-help"],
      ["phonenumber", "main-did"],
    ]) {
      expect(alone).toContain(`  ${type}: (name) => {`);
      expect(alone).toContain(`// Names referenced: ${name}.`);
    }
    // Alphabetical with the required methods, so the file reads as one list.
    const order = [
      "assistant:",
      "casefield:",
      "casetemplate:",
      "flow:",
      "hours:",
      "lambda:",
      "lex:",
      "module:",
      "phonenumber:",
      "prompt:",
      "queue:",
      "tasktemplate:",
      "view:",
    ].map((key) => alone.indexOf(`  ${key} `));
    expect(order).toEqual([...order].sort((a, b) => a - b));
    expect(order.every((at) => at > 0)).toBe(true);

    // Add both documents to the set and FlowSet resolves them: the methods go.
    const whisper = { ...demoDoc(), name: "whisper-line" };
    const module = { ...demoDoc(), name: "callback-offer", kind: "module" as const };
    const together = cdkScaffold({ docs: [referrer, whisper, module], source: "." });
    expect(together).not.toContain("module:");
    expect(together).not.toContain("flow:");
    expect(referencedNames([referrer, whisper, module]).has("module")).toBe(false);
    expect(referencedNames([referrer, whisper, module]).has("flow")).toBe(false);
  });

  it("names the file it is written to", () => {
    expect(CDK_SCAFFOLD_FILE).toBe("flow-stack.ts");
  });

  it("unions the reference index with what the content actually holds", () => {
    const doc = demoDoc();
    doc.refs = [];
    expect([...referencedNames([doc]).keys()].sort()).toEqual(["hours", "lambda", "queue"]);
  });
});

describe("sourceForDepth", () => {
  it("agrees with node's path.relative for a nested output directory", () => {
    const docs = resolve("/srv/flows");
    for (const [depth, out] of [
      [0, docs],
      [1, resolve(docs, "infra")],
      [2, resolve(docs, "infra/cdk")],
    ] as const) {
      const expected = relative(out, docs).split("/").join("/");
      expect(sourceForDepth(depth)).toBe(expected === "" ? "." : expected);
    }
  });
});

describe("the module stays browser-safe", () => {
  it("imports no node builtin, because the studio bundles it", () => {
    const source = readFileSync(fileURLToPath(new URL("./scaffold.ts", import.meta.url)), "utf8");
    // Anchored: the scaffold it emits does import node:url, as a line inside a
    // string literal. Prettier puts this module's own imports at column zero,
    // so an import that would break the browser bundle still matches.
    expect(source).not.toMatch(/^import .*from "node:/m);
    expect(source).not.toMatch(/^import "node:/m);
  });

  it("emits a FLOW_DOCS that does not depend on the working directory", () => {
    const scaffold = cdkScaffold({ docs: [demoDoc()], source: ".." });
    expect(scaffold).toContain('const FLOW_DOCS = fileURLToPath(new URL("..", import.meta.url));');
    expect(scaffold).toContain('import { fileURLToPath } from "node:url";');
  });
});
