/*
 * Copyright 2026 The flow-as-code Authors
 * SPDX-License-Identifier: Apache-2.0
 */
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import type { FlowAction, FlowDoc } from "./index.js";
import {
  DisconnectParticipant,
  Flow,
  GenericBlock,
  GetParticipantInput,
  MessageParticipant,
  Refs,
  UpdateContactAttributes,
  canonicalize,
  codegen,
  factoryName,
  synth,
} from "./index.js";

const demoDoc = (): FlowDoc =>
  JSON.parse(
    readFileSync(
      new URL("../../../conformance/demo/appointment-line.flowdoc.json", import.meta.url),
      "utf8",
    ),
  ) as FlowDoc;

/** A minimal hand-rolled FlowDoc for shapes the builder cannot produce. */
function docWith(actions: FlowDoc["content"]["Actions"]): FlowDoc {
  return {
    flowdoc: "0.1",
    kind: "flow",
    name: "hand-rolled",
    connectType: "CONTACT_FLOW",
    content: { Version: "2019-10-30", StartAction: actions[0]!.Identifier, Actions: actions },
  };
}

describe("factoryName", () => {
  it("camelCases slugs", () => {
    expect(factoryName("appointment-line")).toBe("appointmentLine");
    expect(factoryName("main")).toBe("main");
  });

  it("guards names that are not valid identifiers", () => {
    expect(factoryName("24-7-line")).toBe("flow247Line");
    expect(factoryName("return")).toBe("flowReturn");
  });
});

describe("codegen emission", () => {
  it("opens with a neutral banner naming the document, not a licence header", () => {
    // The output is written into a user's project and is their file. Stamping
    // this repository's copyright on it would be a claim we do not have.
    const source = codegen(demoDoc());
    expect(source.split("\n").slice(0, 2)).toEqual([
      "// Generated by @flow-as-code/core codegen from appointment-line.flowdoc.json.",
      "// Edits to structure regenerate; comments marked @keep survive.",
    ]);
    expect(source).not.toContain("SPDX-License-Identifier");
    expect(source).not.toContain("Copyright");
  });

  it("defaults the import to the published package", () => {
    expect(codegen(demoDoc())).toContain('} from "@flow-as-code/core";');
  });

  it("honors options.moduleSpecifier", () => {
    expect(codegen(demoDoc(), { moduleSpecifier: "../index.js" })).toContain(
      '} from "../index.js";',
    );
  });

  it("omits layout when it equals the deterministic auto-layout", () => {
    // The demo fixture's layout is synth's auto-layout (see synth.test.ts).
    expect(codegen(demoDoc())).not.toContain("layout:");
  });

  it("emits hand-placed layout and an explicit start verbatim", () => {
    const doc = synth(
      new Flow({
        name: "placed",
        start: "greet",
        layout: { greet: { x: 12, y: 34 }, bye: { x: 56, y: 78 } },
      }).add(
        new GenericBlock({ id: "warm-up", type: "UpdateFlowLoggingBehavior", next: "greet" }),
        new MessageParticipant({ id: "greet", text: "hi", next: "bye", onError: "bye" }),
        new DisconnectParticipant({ id: "bye" }),
      ),
      { includeMeta: false },
    );
    const out = codegen(doc);
    expect(out).toContain('start: "greet",');
    expect(out).toContain("layout: {");
    expect(out).toContain("bye: { x: 56, y: 78 },");
    expect(out).toContain("greet: { x: 12, y: 34 },");
  });

  it("keeps a default TargetContact implicit and emits a non-default one", () => {
    const doc = synth(
      new Flow({ name: "attrs" }).add(
        new UpdateContactAttributes({
          id: "set-current",
          attributes: { a: "1" },
          next: "set-related",
          onError: "set-related",
        }),
        new UpdateContactAttributes({
          id: "set-related",
          attributes: { b: "2" },
          targetContact: "Related",
          next: "bye",
          onError: "bye",
        }),
        new DisconnectParticipant({ id: "bye" }),
      ),
      { includeMeta: false },
    );
    const out = codegen(doc);
    expect(out).not.toContain('targetContact: "Current"');
    expect(out.match(/targetContact: "Related"/g)).toHaveLength(1);
  });

  it("throws on a module doc with a non-MODULE connect type", () => {
    const doc = { ...demoDoc(), kind: "module" as const };
    expect(() => codegen(doc)).toThrow(/requires connectType MODULE/);
  });
});

describe("GenericBlock fallback keeps the round-trip lossless", () => {
  it("falls back when a modeled Type carries an extra parameter", () => {
    const doc = synth(
      new Flow({ name: "extra-param" }).add(
        new GenericBlock({
          id: "odd",
          type: "MessageParticipant",
          parameters: { Text: "hi", Unmodeled: "true" },
          next: "bye",
          errors: [{ errorType: "NoMatchingError", target: "bye" }],
        }),
        new DisconnectParticipant({ id: "bye" }),
      ),
      { includeMeta: false },
    );
    const out = codegen(doc);
    expect(out).toContain(
      'new GenericBlock({\n      id: "odd",\n      type: "MessageParticipant",',
    );
    expect(out).not.toContain("new MessageParticipant(");
  });

  it("falls back when a reference field holds a token of the wrong type", () => {
    const doc = synth(
      new Flow({ name: "wrong-ref" }).add(
        new GenericBlock({
          id: "set-queue",
          type: "UpdateContactTargetQueue",
          parameters: { QueueId: "${cdref:lambda:not-a-queue}" },
          next: "bye",
          errors: [{ errorType: "NoMatchingError", target: "bye" }],
        }),
        new DisconnectParticipant({ id: "bye" }),
      ),
      { includeMeta: false },
    );
    const out = codegen(doc);
    expect(out).toContain("new GenericBlock(");
    expect(out).toContain('QueueId: "${cdref:lambda:not-a-queue}"');
    expect(out).not.toContain("Refs.");
  });

  it("falls back when a modeled Type misses its required error branch", () => {
    const doc = docWith([
      {
        Identifier: "no-error-branch",
        Type: "MessageParticipant",
        Parameters: { Text: "hi" },
        Transitions: { NextAction: "bye", Errors: [], Conditions: [] },
      },
      { Identifier: "bye", Type: "DisconnectParticipant", Parameters: {}, Transitions: {} },
    ]);
    const out = codegen(doc);
    expect(out).toContain('type: "MessageParticipant"');
    expect(out).not.toContain("new MessageParticipant(");
  });

  it("keeps tokens inside GenericBlock parameters as verbatim strings", () => {
    const doc = synth(
      new Flow({ name: "passthrough" }).add(
        new GenericBlock({
          id: "lex",
          type: "ConnectParticipantWithLexBot",
          parameters: { LexV2Bot: "${cdref:lex:sales-bot}" },
          next: "bye",
        }),
        new DisconnectParticipant({ id: "bye" }),
      ),
      { includeMeta: false },
    );
    const out = codegen(doc);
    expect(out).toContain('LexV2Bot: "${cdref:lex:sales-bot}"');
    expect(out).not.toContain("Refs.lex");
  });
});

// invertAction does not trust an inverter: it constructs the block the inverter
// proposes and compares its toAction() against the source Action, falling back
// to GenericBlock on any difference. Every other fallback in this file is
// caught earlier, by an inverter's own guards, so the comparison itself was
// removable (replace it with a bare `candidate !== undefined`) with the whole
// suite green. These are the cases that reach it.
describe("codegen verifies an inversion instead of trusting it", () => {
  // Transitions.Conditions is optional in the Flow language and Connect's own
  // exports omit it when empty. wiredTransitions() accepts that (it only
  // requires no conditions), so the inverter hands back a MessageParticipant
  // candidate, but the class writes `Conditions: []` unconditionally. Only
  // re-synthesizing the candidate notices.
  const omittedConditions = (): FlowDoc =>
    docWith([
      {
        Identifier: "welcome",
        Type: "MessageParticipant",
        Parameters: { Text: "Thanks for calling." },
        Transitions: {
          NextAction: "bye",
          Errors: [{ ErrorType: "NoMatchingError", NextAction: "bye" }],
        },
      },
      { Identifier: "bye", Type: "DisconnectParticipant", Parameters: {}, Transitions: {} },
    ]);

  it("emits GenericBlock for a modeled Type whose block class would rewrite it", () => {
    const out = codegen(omittedConditions());
    expect(out).toContain('type: "MessageParticipant"');
    expect(out).not.toContain("new MessageParticipant(");
  });

  it("is exactly the divergence the comparison catches", () => {
    // Stated concretely so the next person to change wire() sees what this
    // fallback was protecting: the class adds a key the Action does not have.
    const action = omittedConditions().content.Actions[0]!;
    expect(action.Transitions).not.toHaveProperty("Conditions");
    const rebuilt = new MessageParticipant({
      id: "welcome",
      text: "Thanks for calling.",
      next: "bye",
      onError: "bye",
    }).toAction();
    expect(rebuilt.Transitions).toHaveProperty("Conditions");
  });

  it("emits GenericBlock when an error branch carries a field the class drops", () => {
    const doc = docWith([
      {
        Identifier: "welcome",
        Type: "MessageParticipant",
        Parameters: { Text: "Thanks for calling." },
        Transitions: {
          NextAction: "bye",
          // A future Flow language field, or one this library does not model
          // yet. The inverter reads ErrorType and NextAction only.
          Errors: [{ ErrorType: "NoMatchingError", NextAction: "bye", Unmodeled: "keep" } as never],
          Conditions: [],
        },
      },
      { Identifier: "bye", Type: "DisconnectParticipant", Parameters: {}, Transitions: {} },
    ]);
    const out = codegen(doc);
    expect(out).toContain('type: "MessageParticipant"');
    expect(out).not.toContain("new MessageParticipant(");
  });

  it("still emits the modeled block when the inversion does reproduce the Action", () => {
    const doc = docWith([
      {
        Identifier: "welcome",
        Type: "MessageParticipant",
        Parameters: { Text: "Thanks for calling." },
        Transitions: {
          NextAction: "bye",
          Errors: [{ ErrorType: "NoMatchingError", NextAction: "bye" }],
          Conditions: [],
        },
      },
      { Identifier: "bye", Type: "DisconnectParticipant", Parameters: {}, Transitions: {} },
    ]);
    const out = codegen(doc);
    expect(out).toContain("new MessageParticipant(");
    expect(out).not.toContain('type: "MessageParticipant"');
  });
});

describe("GetParticipantInput inverts only the shape the class emits", () => {
  /** The exact Action the class writes for a two-key menu. */
  const menuAction = (): FlowAction => ({
    Identifier: "menu",
    Type: "GetParticipantInput",
    Parameters: { Text: "Press 1 or 2.", InputTimeLimitSeconds: "5", StoreInput: "False" },
    Transitions: {
      NextAction: "again",
      Errors: [
        { ErrorType: "InputTimeLimitExceeded", NextAction: "again" },
        { ErrorType: "NoMatchingCondition", NextAction: "again" },
        { ErrorType: "NoMatchingError", NextAction: "bye" },
      ],
      Conditions: [
        { NextAction: "bye", Condition: { Operator: "Equals", Operands: ["1"] } },
        { NextAction: "again", Condition: { Operator: "Equals", Operands: ["2"] } },
      ],
    },
  });
  const rest = (): FlowAction[] => [
    {
      Identifier: "again",
      Type: "MessageParticipant",
      Parameters: { Text: "Sorry." },
      Transitions: {
        NextAction: "menu",
        Errors: [{ ErrorType: "NoMatchingError", NextAction: "bye" }],
        Conditions: [],
      },
    },
    { Identifier: "bye", Type: "DisconnectParticipant", Parameters: {}, Transitions: {} },
  ];
  const withMenu = (edit: (a: FlowAction) => void): FlowDoc => {
    const a = menuAction();
    edit(a);
    return docWith([a, ...rest()]);
  };
  const generic = (doc: FlowDoc) => {
    const out = codegen(doc);
    expect(out).toContain('type: "GetParticipantInput"');
    expect(out).not.toContain("new GetParticipantInput(");
    return out;
  };

  it("emits the class for the exact shape, and the class re-emits the Action", () => {
    const out = codegen(docWith([menuAction(), ...rest()]));
    expect(out).toContain(
      [
        "    new GetParticipantInput({",
        '      id: "menu",',
        '      text: "Press 1 or 2.",',
        "      timeoutSeconds: 5,",
        "      branches: [",
        '        { digit: "1", target: "bye" },',
        '        { digit: "2", target: "again" },',
        "      ],",
        '      onTimeout: "again",',
        '      onNoMatch: "again",',
        '      onError: "bye",',
        "    }),",
      ].join("\n"),
    );
    // The other direction: the block that source constructs synthesizes to
    // the same Action the doc held.
    const block = new GetParticipantInput({
      id: "menu",
      text: "Press 1 or 2.",
      timeoutSeconds: 5,
      branches: [
        { digit: "1", target: "bye" },
        { digit: "2", target: "again" },
      ],
      onTimeout: "again",
      onNoMatch: "again",
      onError: "bye",
    });
    expect(block.toAction()).toEqual(menuAction());
  });

  it("turns a PromptId token into Refs.prompt and a JSONPath into jsonPath()", () => {
    const token = codegen(
      withMenu((a) => {
        a.Parameters = { ...a.Parameters, PromptId: Refs.prompt("menu-prompt") };
        delete a.Parameters.Text;
      }),
    );
    expect(token).toContain('prompt: Refs.prompt("menu-prompt")');
    expect(token).toContain("new GetParticipantInput(");
    expect(token).toContain("Refs,");
    const path = codegen(
      withMenu((a) => {
        a.Parameters = { ...a.Parameters, PromptId: "$.Attributes.menuPrompt" };
        delete a.Parameters.Text;
      }),
    );
    expect(path).toContain('prompt: jsonPath("$.Attributes.menuPrompt")');
    expect(path).toContain("new GetParticipantInput(");
  });

  it("inverts a menu with SSML, and one with no prompt at all", () => {
    const ssml = codegen(
      withMenu((a) => {
        a.Parameters = { ...a.Parameters, SSML: "<speak>Press 1.</speak>" };
        delete a.Parameters.Text;
      }),
    );
    expect(ssml).toContain('ssml: "<speak>Press 1.</speak>"');
    expect(ssml).toContain("new GetParticipantInput(");
    const silent = codegen(
      withMenu((a) => {
        delete a.Parameters.Text;
      }),
    );
    expect(silent).toContain("new GetParticipantInput(");
    expect(silent).toContain('      id: "menu",\n      timeoutSeconds: 5,');
  });

  it("round-trips the synthesized shape byte-stably", () => {
    const flow = new Flow({ name: "menu" }).add(
      new GetParticipantInput({
        id: "menu",
        text: "Press 1 or 2.",
        timeoutSeconds: 5,
        branches: [
          { digit: "1", target: "bye" },
          { digit: "2", target: "again" },
        ],
        onTimeout: "again",
        onNoMatch: "again",
        onError: "bye",
      }),
      new MessageParticipant({ id: "again", text: "Sorry.", next: "menu", onError: "bye" }),
      new DisconnectParticipant({ id: "bye" }),
    );
    const doc = synth(flow, { includeMeta: false });
    expect(canonicalize(doc).content.Actions[0]).toEqual(
      canonicalize(docWith([menuAction()])).content.Actions[0],
    );
    const first = codegen(doc);
    expect(codegen(doc)).toBe(first);
    expect(first).toContain("new GetParticipantInput(");
  });

  it("falls back for the stored-input form, which the class never emits", () => {
    generic(
      withMenu((a) => {
        a.Parameters = {
          ...a.Parameters,
          StoreInput: "True",
          InputValidation: { CustomValidation: { MaximumLength: "4" } },
        };
        a.Transitions.Conditions = [];
      }),
    );
    generic(
      withMenu((a) => {
        a.Parameters = { ...a.Parameters, StoreInput: "True" };
      }),
    );
    generic(
      withMenu((a) => {
        delete a.Parameters.StoreInput;
      }),
    );
  });

  it("falls back when the timeout is not the plain decimal string the class writes", () => {
    for (const timeout of [5, "05", "5.0", " 5", "", "0", "181", "abc"]) {
      generic(
        withMenu((a) => {
          a.Parameters = { ...a.Parameters, InputTimeLimitSeconds: timeout };
        }),
      );
    }
    generic(
      withMenu((a) => {
        delete a.Parameters.InputTimeLimitSeconds;
      }),
    );
  });

  it("falls back when the prompt is doubled, mistyped, or a parameter is unmodeled", () => {
    generic(
      withMenu((a) => {
        a.Parameters = { ...a.Parameters, PromptId: Refs.prompt("p") };
      }),
    );
    generic(
      withMenu((a) => {
        a.Parameters = { ...a.Parameters, PromptId: Refs.queue("q") };
        delete a.Parameters.Text;
      }),
    );
    generic(
      withMenu((a) => {
        a.Parameters = { ...a.Parameters, Text: 5 };
      }),
    );
    generic(
      withMenu((a) => {
        a.Parameters = {
          ...a.Parameters,
          DTMFConfiguration: { InputTerminationSequence: "#" },
        };
      }),
    );
    generic(
      withMenu((a) => {
        a.Parameters = {
          ...a.Parameters,
          Media: { Uri: "x", SourceType: "S3", MediaType: "Audio" },
        };
      }),
    );
  });

  it("falls back when a condition is not a single-key Equals", () => {
    const setCondition = (c: { Operator: string; Operands: string[] }) =>
      withMenu((a) => {
        a.Transitions.Conditions![0]!.Condition = c as never;
      });
    generic(setCondition({ Operator: "TextStartsWith", Operands: ["1"] }));
    generic(setCondition({ Operator: "Equals", Operands: ["10"] }));
    generic(setCondition({ Operator: "Equals", Operands: ["a"] }));
    generic(setCondition({ Operator: "Equals", Operands: [""] }));
    generic(setCondition({ Operator: "Equals", Operands: ["1", "2"] }));
    generic(setCondition({ Operator: "Equals", Operands: [] }));
    generic(
      withMenu((a) => {
        delete a.Transitions.Conditions;
      }),
    );
  });

  it("falls back when a key branches twice, which the class refuses", () => {
    // The shape is otherwise exact, so this fallback rides on the constructor
    // check alone: codegen builds the real block to verify an inversion, and
    // the throw sends the action to GenericBlock. The conformance fixture
    // pins the same shape for the other implementations.
    generic(
      withMenu((a) => {
        a.Transitions.Conditions![1]!.Condition.Operands = ["1"];
      }),
    );
    const fixture = JSON.parse(
      readFileSync(
        new URL("../../../conformance/roundtrip/repeated-key/doc.flowdoc.json", import.meta.url),
        "utf8",
      ),
    ) as FlowDoc;
    generic(fixture);
  });

  it("falls back when the error set or its order differs from the class's", () => {
    generic(
      withMenu((a) => {
        a.Transitions.Errors = [
          a.Transitions.Errors![1]!,
          a.Transitions.Errors![0]!,
          a.Transitions.Errors![2]!,
        ];
      }),
    );
    generic(
      withMenu((a) => {
        a.Transitions.Errors = a.Transitions.Errors!.filter(
          (e) => e.ErrorType !== "InputTimeLimitExceeded",
        );
      }),
    );
    generic(
      withMenu((a) => {
        a.Transitions.Errors = a.Transitions.Errors!.filter(
          (e) => e.ErrorType !== "NoMatchingCondition",
        );
      }),
    );
    generic(
      withMenu((a) => {
        a.Transitions.Errors = a.Transitions.Errors!.filter(
          (e) => e.ErrorType !== "NoMatchingError",
        );
      }),
    );
    generic(
      withMenu((a) => {
        a.Transitions.Errors!.push({ ErrorType: "InvalidPhoneNumber", NextAction: "bye" });
      }),
    );
  });

  it("falls back on a field the inverter never reads, by re-synthesizing the candidate", () => {
    // isCondition checks the fields the class uses and nothing else, so only
    // verify-by-construction notices a condition entry carrying more.
    generic(
      withMenu((a) => {
        a.Transitions.Conditions![0] = {
          ...a.Transitions.Conditions![0]!,
          Unmodeled: "keep",
        } as never;
      }),
    );
    generic(
      withMenu((a) => {
        a.Transitions.Errors![0] = { ...a.Transitions.Errors![0]!, Unmodeled: "keep" } as never;
      }),
    );
  });

  it("falls back when NextAction does not mirror the NoMatchingCondition target", () => {
    generic(
      withMenu((a) => {
        a.Transitions.NextAction = "bye";
      }),
    );
    generic(
      withMenu((a) => {
        delete a.Transitions.NextAction;
      }),
    );
  });

  it("keeps the unknown-actions fixture's GetParticipantInput generic", () => {
    // That fixture predates the block and carries a numeric timeout, no
    // StoreInput, and only two of the three errors: none of it is the class's
    // shape, and the fixture's round-trip test holds it verbatim.
    const doc = JSON.parse(
      readFileSync(
        new URL("../../../conformance/roundtrip/unknown-actions/doc.flowdoc.json", import.meta.url),
        "utf8",
      ),
    ) as FlowDoc;
    generic(doc);
  });
});

describe("@keep comments survive regeneration", () => {
  it("re-attaches @keep comments to the matching block and the export", () => {
    const doc = demoDoc();
    const base = codegen(doc);
    const previous = base
      .replace(
        "    new CheckHoursOfOperation({",
        "    // Business hours drive everything below. @keep\n    // scratch note, not kept\n    new CheckHoursOfOperation({",
      )
      .replace(
        "export function appointmentLine",
        "// Reviewed by on-call. @keep\nexport function appointmentLine",
      );
    const regen = codegen(doc, { previous });
    expect(regen).toContain(
      "    // Business hours drive everything below. @keep\n    new CheckHoursOfOperation({",
    );
    expect(regen).toContain("// Reviewed by on-call. @keep\nexport function appointmentLine");
    expect(regen).not.toContain("scratch note");
  });

  it("is idempotent: regenerating from its own output changes nothing", () => {
    const doc = demoDoc();
    const base = codegen(doc);
    expect(codegen(doc, { previous: base })).toBe(base);
    const withKeep = codegen(doc, {
      previous: base.replace(
        '    new DisconnectParticipant({ id: "hang-up" }),',
        '    // Terminal on purpose. @keep\n    new DisconnectParticipant({ id: "hang-up" }),',
      ),
    });
    expect(codegen(doc, { previous: withKeep })).toBe(withKeep);
  });

  it("drops a @keep comment whose block id no longer exists", () => {
    const doc = demoDoc();
    const base = codegen(doc);
    const previous = base.replace(
      '    new MessageParticipant({\n      id: "welcome",',
      '    // Stale note. @keep\n    new MessageParticipant({\n      id: "gone-now",',
    );
    const regen = codegen(doc, { previous });
    expect(regen).not.toContain("Stale note");
  });
});
