/*
 * Copyright 2026 The flow-as-code Authors
 * SPDX-License-Identifier: Apache-2.0
 */
// codegen: FlowDoc in, idiomatic TypeScript out.
//
// The output is what a person would have written against the builder API: one
// exported zero-arg factory returning a Flow (or FlowModule), with one inline
// block construction per Action, in doc order. Synth preserves declaration
// order (docs/adr/0003-action-ordering.md), so emitting doc order makes
// synth(codegen(doc)) reproduce the doc with no reordering step.
//
// Invariants:
// - Pure and byte-stable: the same FlowDoc yields the identical string.
// - Prettier-clean as written: the printer mirrors the repo Prettier config
//   (2-space indent, double quotes, trailing commas, printWidth 100), and a
//   test formats the output to prove it is a fixed point.
// - Lossless: an Action of a modeled Type that the block class cannot
//   reproduce exactly falls back to GenericBlock, verified by re-synthesizing
//   every candidate block and comparing against the source Action.
// - Reference tokens in modeled reference-bearing fields become Refs.* calls;
//   JSONPath strings become jsonPath(...); tokens inside GenericBlock
//   parameters stay verbatim strings and are never rewritten.

import {
  AGENT_METRIC_TYPES,
  ActionType,
  CALLBACK_NUMBER_NOT_DIALABLE,
  CHANNEL_MISMATCH,
  DTMF_DIGITS,
  EVENT_HOOKS,
  INPUT_TIME_LIMIT_EXCEEDED,
  INVALID_CALLBACK_NUMBER,
  LEX_TIMEOUT_MAX,
  LEX_TIMEOUT_MIN,
  LOOP_CONTINUE,
  LOOP_DONE,
  MESSAGES_INTERRUPTED,
  METRIC_OPERATORS,
  METRIC_TYPES,
  PARTICIPANT_NOT_FOUND,
  PERCENTAGE_THRESHOLD_MAX,
  QUEUE_CHANNELS,
  SYSTEM_TAG_PREFIX,
  TAG_LIMIT,
  TIME_LIMIT_EXCEEDED,
  TARGET_CONTACTS,
  TTS_ENGINES,
  TTS_STYLES,
  VOICE_ID_RESPONSE_TIME_MAX,
  VOICE_ID_RESPONSE_TIME_MIN,
  VOICE_ID_THRESHOLD_MAX,
  VOICE_ID_THRESHOLD_MIN,
  WAIT_COMPLETED,
  WAIT_EVENTS,
  WAIT_TIMEOUT_MAX,
  WAIT_TIMEOUT_MIN,
  NO_MATCHING_CONDITION,
  NO_MATCHING_ERROR,
  REFERENCE_FIELDS,
} from "./actions.js";
import type { DtmfDigit } from "./actions.js";
import type { Block, DtmfBranch, GenericBlockConfig, MessageBody } from "./blocks.js";
import {
  CheckHoursOfOperation,
  CheckMetricData,
  Compare,
  ConnectParticipantWithLexBot,
  CreateCallbackContact,
  DequeueContactAndTransferToQueue,
  DisconnectParticipant,
  DistributeByPercentage,
  EndFlowExecution,
  EndFlowModuleExecution,
  GenericBlock,
  GetMetricData,
  GetParticipantInput,
  InvokeFlowModule,
  InvokeLambdaFunction,
  Loop,
  MessageParticipant,
  MessageParticipantIteratively,
  ShowView,
  TagContact,
  TransferContactToAgent,
  UntagContact,
  TransferContactToQueue,
  TransferToFlow,
  UpdateContactAttributes,
  UpdateContactCallbackNumber,
  UpdateContactData,
  UpdateContactEventHooks,
  UpdateContactRecordingAndAnalyticsBehavior,
  UpdateContactRecordingBehavior,
  UpdateContactRoutingBehavior,
  UpdateContactTargetQueue,
  UpdateContactTextToSpeechVoice,
  UpdateFlowAttributes,
  UpdateFlowLoggingBehavior,
  Wait,
} from "./blocks.js";
import type {
  ConditionOperator,
  ErrorTransition,
  FlowAction,
  FlowDoc,
  Point,
  RefType,
  Transitions,
} from "./flowdoc.js";
import { assertFlowDoc } from "./flowdoc.js";
import { autoLayout } from "./layout.js";
import { PACKAGE_NAMES } from "./package-names.js";
import { parseToken } from "./refs.js";

export interface CodegenOptions {
  /** Import path for the builder API. Defaults to the published package. */
  moduleSpecifier?: string;
  /**
   * A previously generated source for the same flow. Comment lines containing
   * `@keep` that immediately precede a block construction re-attach to the
   * block with the same id; ones immediately preceding the export function
   * re-attach there. Everything else regenerates.
   */
  previous?: string;
  /**
   * Kept comment lines to attach, in place of those `previous` holds: what
   * `flow-cli convert` carries over from a `.flow.tf`, whose `# @keep` lines
   * arrive here rewritten as `// @keep`.
   */
  keep?: KeepComments;
}

const DEFAULT_MODULE_SPECIFIER = PACKAGE_NAMES.core;
const PRINT_WIDTH = 100;

// The banner on generated files. No licence header: the output lands in a
// user's project and is their file, not ours, so stamping this repo's
// copyright on it would be wrong. The Terraform emitter's banner works the
// same way (packages/tf/src/emit.ts).
//
// Naming the document it came from makes a file found on its own explain
// itself, and `.flowdoc.json` is the name `flow-cli codegen` reads.
function generatedMarker(name: string): string[] {
  return [
    `// Generated by ${PACKAGE_NAMES.core} codegen from ${name}.flowdoc.json.`,
    "// Edits to structure regenerate; comments marked @keep survive.",
  ];
}

// ---------------------------------------------------------------------------
// Value model for the printer
// ---------------------------------------------------------------------------

/** A code fragment emitted verbatim, e.g. `Refs.queue("front-desk")`. */
class Raw {
  constructor(readonly code: string) {}
}

/** An object literal with a fixed entry order. */
class ObjV {
  constructor(readonly entries: [string, V][]) {}
}

class ArrV {
  constructor(readonly items: V[]) {}
}

type V = string | number | boolean | null | Raw | ObjV | ArrV;

/** Arbitrary JSON (GenericBlock parameters) to the value model, keys sorted. */
function toV(value: unknown): V {
  if (value === null || typeof value === "string" || typeof value === "number") return value;
  if (typeof value === "boolean") return value;
  if (Array.isArray(value)) return new ArrV(value.map(toV));
  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>)
      .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
      .map(([k, v]) => [k, toV(v)] as [string, V]);
    return new ObjV(entries);
  }
  throw new Error(`Cannot emit a ${typeof value} value.`);
}

// ---------------------------------------------------------------------------
// Printer. Mirrors the repo Prettier config so the output is a Prettier fixed
// point: double quotes unless the string holds more double than single quotes,
// keys quoted only when not valid identifiers, objects kept expanded once
// broken (Prettier objectWrap: preserve), arrays force-broken when every
// element is an object with two or more properties.
// ---------------------------------------------------------------------------

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function quoteString(s: string): string {
  const doubles = (s.match(/"/g) ?? []).length;
  const singles = (s.match(/'/g) ?? []).length;
  const q = doubles > singles ? "'" : '"';
  let out = q;
  for (const ch of s) {
    if (ch === "\\") out += "\\\\";
    else if (ch === q) out += `\\${q}`;
    else if (ch === "\n") out += "\\n";
    else if (ch === "\r") out += "\\r";
    else if (ch === "\t") out += "\\t";
    else if (
      ch < " " ||
      ch === "\u2028" ||
      ch === "\u2029" ||
      (ch.codePointAt(0)! >= 0xd800 && ch.codePointAt(0)! <= 0xdfff)
    ) {
      // Control characters, JS line separators, and lone surrogates must be
      // escaped: an unpaired surrogate written to a utf8 file becomes U+FFFD,
      // which would break the file-based round trip.
      out += `\\u${ch.codePointAt(0)!.toString(16).padStart(4, "0")}`;
    } else out += ch;
  }
  return out + q;
}

function keySource(key: string): string {
  return IDENTIFIER.test(key) ? key : quoteString(key);
}

/** Prettier breaks such arrays regardless of width. */
function arrayForcesBreak(a: ArrV): boolean {
  return a.items.length > 1 && a.items.every((i) => i instanceof ObjV && i.entries.length >= 2);
}

/** Single-line rendering, or undefined when the value must break. */
function inlineV(v: V): string | undefined {
  if (v instanceof Raw) return v.code;
  if (typeof v === "string") return quoteString(v);
  if (typeof v === "number" || typeof v === "boolean" || v === null) return String(v);
  if (v instanceof ArrV) {
    if (arrayForcesBreak(v)) return undefined;
    const items = v.items.map(inlineV);
    if (items.some((i) => i === undefined)) return undefined;
    return `[${items.join(", ")}]`;
  }
  if (v.entries.length === 0) return "{}";
  const parts = v.entries.map(([k, val]) => {
    const inner = inlineV(val);
    return inner === undefined ? undefined : `${keySource(k)}: ${inner}`;
  });
  if (parts.some((p) => p === undefined)) return undefined;
  return `{ ${parts.join(", ")} }`;
}

/**
 * Renders a value starting at column `col` on a line indented by `indent`.
 * Continuation lines carry their own indentation; the first line does not.
 * One column is reserved for the trailing comma the caller appends.
 */
function printV(v: V, col: number, indent: string): string {
  const flat = inlineV(v);
  if (flat !== undefined && col + flat.length + 1 <= PRINT_WIDTH) return flat;
  const inner = `${indent}  `;
  if (v instanceof ObjV && v.entries.length > 0) return printBrokenObject(v.entries, indent);
  if (v instanceof ArrV && v.items.length > 0) {
    const lines = v.items.map((i) => `${inner}${printV(i, inner.length, inner)},`);
    return `[\n${lines.join("\n")}\n${indent}]`;
  }
  // Primitives and Raw fragments cannot break; emit even when over width.
  return flat ?? "";
}

function printBrokenObject(entries: [string, V][], indent: string): string {
  const inner = `${indent}  `;
  const lines = entries.map(([k, val]) => {
    const prefix = `${inner}${keySource(k)}: `;
    return `${prefix}${printV(val, prefix.length, inner)},`;
  });
  return `{\n${lines.join("\n")}\n${indent}}`;
}

// ---------------------------------------------------------------------------
// Inversion: FlowAction back to a block construction.
//
// Every candidate is verified by constructing the real block and comparing its
// toAction() output against the source Action; on any mismatch the Action is
// emitted as a GenericBlock instead, so the round-trip stays lossless.
// ---------------------------------------------------------------------------

interface Inversion {
  /** Block class name, also the import to emit. */
  cls: string;
  /** Config object entries in emission order. */
  entries: [string, V][];
  /** The constructed block, used to verify the inversion is exact. */
  block: Block;
}

interface Ctx {
  refs: boolean;
  jsonPath: boolean;
}

function stableJson(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(stableJson).join(",")}]`;
  if (value !== null && typeof value === "object") {
    const keys = Object.keys(value as Record<string, unknown>).sort();
    const body = keys
      .map((k) => `${JSON.stringify(k)}:${stableJson((value as Record<string, unknown>)[k])}`)
      .join(",");
    return `{${body}}`;
  }
  return JSON.stringify(value);
}

const cast = <T>(value: unknown): T => value as T;

/**
 * A reference-bearing field value as builder source. Well-formed tokens of the
 * expected type become Refs.* calls, JSONPath strings become jsonPath(...),
 * anything else is inexpressible and forces the GenericBlock fallback.
 * https://docs.aws.amazon.com/connect/latest/devguide/flow-language-actions.html
 * documents these fields as fully static or a single JSONPath identifier.
 */
function refSource(value: unknown, type: RefType, ctx: Ctx): Raw | undefined {
  if (typeof value !== "string") return undefined;
  const entry = parseToken(value);
  if (entry !== undefined) {
    if (entry.type !== type) return undefined;
    if (type === "module") {
      if (entry.alias === undefined) return undefined; // Refs.module requires an alias
      ctx.refs = true;
      return new Raw(`Refs.module(${quoteString(entry.name)}, ${quoteString(entry.alias)})`);
    }
    if (type === "view") {
      // The alias slot holds the view version, and a view need not pin one.
      ctx.refs = true;
      return new Raw(
        entry.alias === undefined
          ? `Refs.view(${quoteString(entry.name)})`
          : `Refs.view(${quoteString(entry.name)}, ${quoteString(entry.alias)})`,
      );
    }
    if (entry.alias !== undefined) return undefined; // only module and view refs carry aliases
    ctx.refs = true;
    return new Raw(`Refs.${type}(${quoteString(entry.name)})`);
  }
  if (/^\$\.[A-Za-z0-9_$.[\]'-]+$/.test(value)) {
    ctx.jsonPath = true;
    return new Raw(`jsonPath(${quoteString(value)})`);
  }
  return undefined;
}

function paramKeysAre(
  params: Record<string, unknown>,
  required: string[],
  optional: string[] = [],
): boolean {
  const keys = Object.keys(params);
  return (
    required.every((k) => keys.includes(k)) &&
    keys.every((k) => required.includes(k) || optional.includes(k))
  );
}

/** NextAction plus exactly one catch-all error and no conditions. */
function wiredTransitions(
  t: Transitions,
  errorType: string,
): { next: string; onError: string } | undefined {
  if (t.NextAction === undefined) return undefined;
  const errors = t.Errors ?? [];
  if (errors.length !== 1 || errors[0]!.ErrorType !== errorType) return undefined;
  if ((t.Conditions ?? []).length !== 0) return undefined;
  return { next: t.NextAction, onError: errors[0]!.NextAction };
}

function isStringMap(value: unknown): value is Record<string, string> {
  return (
    value !== null &&
    typeof value === "object" &&
    !Array.isArray(value) &&
    Object.values(value as Record<string, unknown>).every((v) => typeof v === "string")
  );
}

const OPERATORS: readonly string[] = [
  "Equals",
  "TextStartsWith",
  "TextEndsWith",
  "TextContains",
  "NumberGreaterThan",
  "NumberGreaterOrEqualTo",
  "NumberLessThan",
  "NumberLessOrEqualTo",
];

function isCondition(
  value: unknown,
): value is { NextAction: string; Condition: { Operator: ConditionOperator; Operands: string[] } } {
  const c = value as {
    NextAction?: unknown;
    Condition?: { Operator?: unknown; Operands?: unknown };
  };
  return (
    typeof c.NextAction === "string" &&
    typeof c.Condition === "object" &&
    c.Condition !== null &&
    typeof c.Condition.Operator === "string" &&
    OPERATORS.includes(c.Condition.Operator) &&
    Array.isArray(c.Condition.Operands) &&
    c.Condition.Operands.every((o) => typeof o === "string")
  );
}

function terminal(a: FlowAction, make: () => Block): Inversion | undefined {
  if (Object.keys(a.Parameters).length !== 0) return undefined;
  if (Object.keys(a.Transitions).length !== 0) return undefined;
  return { cls: a.Type, entries: [["id", a.Identifier]], block: make() };
}

/**
 * One inverter per modeled action type; undefined means "not expressible".
 *
 * The correctness gate is not in here. invertAction constructs the candidate
 * block, compares its synthesized Action with the source byte for byte, and
 * falls back to GenericBlock on any difference or constructor throw. The early
 * returns below are readable statements of each class's shape and a cheap way
 * out before a constructor runs; most of them are redundant with that
 * comparison, so neutering one does not change the output. The exception is
 * the refSource check: the block would still verify with an unresolvable
 * PromptId, but the emitted entries would carry `prompt: undefined`, so that
 * return is load-bearing and is the one a test pins. The typeof checks on
 * string parameters exist for the type checker; the comparison catches the
 * JSON number spelling either way.
 */
const INVERTERS: Record<string, (a: FlowAction, ctx: Ctx) => Inversion | undefined> = {
  [ActionType.MessageParticipant]: (a, ctx) => {
    // The catch-all is optional: the service accepts the action without it
    // and the console's own flows usually omit it.
    const t = a.Transitions;
    if (t.NextAction === undefined || (t.Conditions ?? []).length !== 0) return undefined;
    const errors = t.Errors ?? [];
    if (errors.length > 1 || (errors.length === 1 && errors[0]!.ErrorType !== NO_MATCHING_ERROR)) {
      return undefined;
    }
    const w = { next: t.NextAction, onError: errors[0]?.NextAction };
    const p = a.Parameters;
    const keys = Object.keys(p);
    if (keys.length !== 1) return undefined;
    const entries: [string, V][] = [["id", a.Identifier]];
    if (keys[0] === "Text" && typeof p.Text === "string") entries.push(["text", p.Text]);
    else if (keys[0] === "SSML" && typeof p.SSML === "string") entries.push(["ssml", p.SSML]);
    else if (keys[0] === "PromptId") {
      const ref = refSource(
        p.PromptId,
        REFERENCE_FIELDS[ActionType.MessageParticipant]!.PromptId!,
        ctx,
      );
      if (ref === undefined) return undefined;
      entries.push(["prompt", ref]);
    } else return undefined;
    entries.push(["next", w.next]);
    if (w.onError !== undefined) entries.push(["onError", w.onError]);
    const body =
      keys[0] === "Text"
        ? { text: cast<string>(p.Text) }
        : keys[0] === "SSML"
          ? { ssml: cast<string>(p.SSML) }
          : { prompt: cast<never>(p.PromptId) };
    return {
      cls: "MessageParticipant",
      entries,
      block: new MessageParticipant({
        id: a.Identifier,
        ...body,
        next: w.next,
        ...(w.onError === undefined ? {} : { onError: w.onError }),
      }),
    };
  },

  [ActionType.MessageParticipantIteratively]: (a, ctx) => {
    const t = a.Transitions;
    if (t.NextAction !== undefined) return undefined;
    const errors = t.Errors ?? [];
    if (errors.length > 1 || (errors.length === 1 && errors[0]!.ErrorType !== NO_MATCHING_ERROR)) {
      return undefined;
    }
    const conditions = t.Conditions ?? [];
    if (conditions.length > 1 || !conditions.every(isCondition)) return undefined;
    const interrupt = conditions[0];
    if (
      interrupt !== undefined &&
      stableJson(interrupt.Condition) !==
        stableJson({ Operator: "Equals", Operands: [MESSAGES_INTERRUPTED] })
    ) {
      return undefined;
    }
    if (!paramKeysAre(a.Parameters, ["Messages"], ["InterruptFrequencySeconds"])) return undefined;
    const raw = a.Parameters.Messages;
    if (!Array.isArray(raw) || raw.length === 0) return undefined;
    const messages: Record<string, unknown>[] = [];
    const messageV: V[] = [];
    for (const m of raw) {
      if (m === null || typeof m !== "object" || Array.isArray(m)) return undefined;
      const keys = Object.keys(m as Record<string, unknown>);
      if (keys.length !== 1) return undefined;
      const [key] = keys;
      const value = (m as Record<string, unknown>)[key!];
      if (key === "Text" && typeof value === "string") {
        messages.push({ text: value });
        messageV.push(new ObjV([["text", value]]));
      } else if (key === "SSML" && typeof value === "string") {
        messages.push({ ssml: value });
        messageV.push(new ObjV([["ssml", value]]));
      } else if (key === "PromptId") {
        const ref = refSource(value, "prompt", ctx);
        if (ref === undefined) return undefined;
        messages.push({ prompt: value });
        messageV.push(new ObjV([["prompt", ref]]));
      } else if (key === "Media") {
        const media = value as Record<string, unknown> | null;
        if (
          media === null ||
          typeof media !== "object" ||
          !paramKeysAre(media, ["Uri", "SourceType", "MediaType"]) ||
          typeof media.Uri !== "string" ||
          media.SourceType !== "S3" ||
          media.MediaType !== "Audio"
        ) {
          return undefined;
        }
        messages.push({ media: { uri: media.Uri } });
        messageV.push(new ObjV([["media", new ObjV([["uri", media.Uri]])]]));
      } else {
        return undefined;
      }
    }
    const entries: [string, V][] = [
      ["id", a.Identifier],
      ["messages", new ArrV(messageV)],
    ];
    const config: Record<string, unknown> = { id: a.Identifier, messages };
    const seconds = a.Parameters.InterruptFrequencySeconds;
    if ((seconds !== undefined) !== (interrupt !== undefined)) return undefined;
    if (seconds !== undefined) {
      if (typeof seconds !== "string" || !/^[1-9][0-9]*$/.test(seconds)) return undefined;
      const n = Number(seconds);
      if (!Number.isSafeInteger(n)) return undefined;
      entries.push(["interruptFrequencySeconds", n], ["onInterrupt", interrupt!.NextAction]);
      config.interruptFrequencySeconds = n;
      config.onInterrupt = interrupt!.NextAction;
    }
    if (errors.length === 1) {
      entries.push(["onError", errors[0]!.NextAction]);
      config.onError = errors[0]!.NextAction;
    }
    return {
      cls: "MessageParticipantIteratively",
      entries,
      block: new MessageParticipantIteratively(cast<never>(config)),
    };
  },

  [ActionType.ConnectParticipantWithLexBot]: (a, ctx) => {
    const t = a.Transitions;
    const errors = t.Errors ?? [];
    if (
      errors.length !== 3 ||
      errors[0]!.ErrorType !== INPUT_TIME_LIMIT_EXCEEDED ||
      errors[1]!.ErrorType !== NO_MATCHING_ERROR ||
      errors[2]!.ErrorType !== NO_MATCHING_CONDITION
    ) {
      return undefined;
    }
    // The class mirrors NextAction onto the no-match branch.
    if (t.NextAction !== errors[2]!.NextAction) return undefined;
    const conditions = t.Conditions ?? [];
    if (!conditions.every(isCondition)) return undefined;
    for (const c of conditions) {
      if (c.Condition.Operator !== "Equals" || c.Condition.Operands.length !== 1) return undefined;
      if (typeof c.Condition.Operands[0] !== "string") return undefined;
    }
    const p = a.Parameters;
    const optional = [
      "PromptId",
      "Text",
      "SSML",
      "LexSessionAttributes",
      "LexInitializationData",
      "LexTimeoutSeconds",
    ];
    if (!paramKeysAre(p, ["LexV2Bot"], optional)) return undefined;
    const bodies = ["PromptId", "Text", "SSML"].filter((k) => p[k] !== undefined);
    if (bodies.length > 1) return undefined;
    const entries: [string, V][] = [["id", a.Identifier]];
    const config: Record<string, unknown> = { id: a.Identifier };
    if (bodies[0] === "Text" && typeof p.Text === "string") {
      entries.push(["text", p.Text]);
      config.text = p.Text;
    } else if (bodies[0] === "SSML" && typeof p.SSML === "string") {
      entries.push(["ssml", p.SSML]);
      config.ssml = p.SSML;
    } else if (bodies[0] === "PromptId") {
      const ref = refSource(p.PromptId, "prompt", ctx);
      if (ref === undefined) return undefined;
      entries.push(["prompt", ref]);
      config.prompt = p.PromptId;
    } else if (bodies[0] !== undefined) {
      return undefined;
    }
    const bot = p.LexV2Bot as Record<string, unknown> | null;
    if (bot === null || typeof bot !== "object" || !paramKeysAre(bot, ["AliasArn"])) {
      return undefined;
    }
    const botRef = refSource(bot.AliasArn, "lex", ctx);
    if (botRef === undefined) return undefined;
    entries.push(["bot", botRef]);
    config.bot = bot.AliasArn;
    if (p.LexSessionAttributes !== undefined) {
      if (!isStringMap(p.LexSessionAttributes)) return undefined;
      entries.push(["sessionAttributes", toV(p.LexSessionAttributes)]);
      config.sessionAttributes = p.LexSessionAttributes;
    }
    if (p.LexInitializationData !== undefined) {
      const init = p.LexInitializationData as Record<string, unknown> | null;
      if (
        init === null ||
        typeof init !== "object" ||
        !paramKeysAre(init, ["InitialMessage"]) ||
        typeof init.InitialMessage !== "string"
      ) {
        return undefined;
      }
      entries.push(["initialMessage", init.InitialMessage]);
      config.initialMessage = init.InitialMessage;
    }
    if (p.LexTimeoutSeconds !== undefined) {
      const timeout = p.LexTimeoutSeconds as Record<string, unknown> | null;
      if (timeout === null || typeof timeout !== "object" || !paramKeysAre(timeout, ["Text"])) {
        return undefined;
      }
      const raw = timeout.Text;
      if (typeof raw !== "string" || !/^[1-9][0-9]*$/.test(raw)) return undefined;
      const seconds = Number(raw);
      if (seconds < LEX_TIMEOUT_MIN || seconds > LEX_TIMEOUT_MAX) return undefined;
      entries.push(["timeoutSeconds", seconds]);
      config.timeoutSeconds = seconds;
    }
    const intents = conditions.map((c) => ({
      name: cast<string>(c.Condition.Operands[0]),
      target: c.NextAction,
    }));
    entries.push(
      [
        "intents",
        new ArrV(
          intents.map(
            (i) =>
              new ObjV([
                ["name", i.name],
                ["target", i.target],
              ]),
          ),
        ),
      ],
      ["onNoMatch", errors[2]!.NextAction],
      ["onError", errors[1]!.NextAction],
      ["onTimeout", errors[0]!.NextAction],
    );
    return {
      cls: "ConnectParticipantWithLexBot",
      entries,
      block: new ConnectParticipantWithLexBot(
        cast<never>({
          ...config,
          intents,
          onNoMatch: errors[2]!.NextAction,
          onError: errors[1]!.NextAction,
          onTimeout: errors[0]!.NextAction,
        }),
      ),
    };
  },

  [ActionType.ShowView]: (a, ctx) => {
    const t = a.Transitions;
    const errors = t.Errors ?? [];
    // The admin guide's order, and NextAction a copy of the catch-all's target.
    if (
      errors.length !== 3 ||
      errors[0]!.ErrorType !== NO_MATCHING_CONDITION ||
      errors[1]!.ErrorType !== NO_MATCHING_ERROR ||
      errors[2]!.ErrorType !== TIME_LIMIT_EXCEEDED
    ) {
      return undefined;
    }
    if (t.NextAction !== errors[1]!.NextAction) return undefined;
    const conditions = t.Conditions ?? [];
    if (!conditions.every(isCondition)) return undefined;
    for (const c of conditions) {
      if (c.Condition.Operator !== "Equals" || c.Condition.Operands.length !== 1) return undefined;
      if (typeof c.Condition.Operands[0] !== "string") return undefined;
    }
    const p = a.Parameters;
    if (
      !paramKeysAre(
        p,
        ["ViewResource", "InvocationTimeLimitSeconds"],
        ["ViewData", "SensitiveDataConfiguration"],
      )
    ) {
      return undefined;
    }
    const resource = p.ViewResource as Record<string, unknown> | null;
    if (
      resource === null ||
      typeof resource !== "object" ||
      !paramKeysAre(resource, ["Id"], ["Version"])
    ) {
      return undefined;
    }
    const view = refSource(resource.Id, "view", ctx);
    if (view === undefined) return undefined;
    const entries: [string, V][] = [
      ["id", a.Identifier],
      ["view", view],
    ];
    const config: Record<string, unknown> = { id: a.Identifier, view: resource.Id };
    if (resource.Version !== undefined) {
      if (typeof resource.Version !== "string") return undefined;
      entries.push(["version", resource.Version]);
      config.version = resource.Version;
    }
    const seconds = p.InvocationTimeLimitSeconds;
    if (typeof seconds !== "string" || !/^[1-9][0-9]*$/.test(seconds)) return undefined;
    const n = Number(seconds);
    if (!Number.isSafeInteger(n)) return undefined;
    entries.push(["timeoutSeconds", n]);
    config.timeoutSeconds = n;
    if (p.ViewData !== undefined) {
      const data = p.ViewData;
      if (data === null || typeof data !== "object" || Array.isArray(data)) return undefined;
      entries.push(["data", toV(data)]);
      config.data = data;
    }
    if (p.SensitiveDataConfiguration !== undefined) {
      const sensitive = p.SensitiveDataConfiguration as Record<string, unknown> | null;
      if (
        sensitive === null ||
        typeof sensitive !== "object" ||
        !paramKeysAre(sensitive, ["HideResponseOn"]) ||
        !Array.isArray(sensitive.HideResponseOn) ||
        !sensitive.HideResponseOn.every((h) => typeof h === "string" && h !== "")
      ) {
        return undefined;
      }
      entries.push(["hideResponseOn", new ArrV([...cast<string[]>(sensitive.HideResponseOn)])]);
      config.hideResponseOn = sensitive.HideResponseOn;
    }
    const actions = conditions.map((c) => ({
      action: cast<string>(c.Condition.Operands[0]),
      target: c.NextAction,
    }));
    entries.push(
      [
        "actions",
        new ArrV(
          actions.map(
            (b) =>
              new ObjV([
                ["action", b.action],
                ["target", b.target],
              ]),
          ),
        ),
      ],
      ["onNoMatch", errors[0]!.NextAction],
      ["onTimeout", errors[2]!.NextAction],
      ["onError", errors[1]!.NextAction],
    );
    return {
      cls: "ShowView",
      entries,
      block: new ShowView(
        cast<never>({
          ...config,
          actions,
          onNoMatch: errors[0]!.NextAction,
          onTimeout: errors[2]!.NextAction,
          onError: errors[1]!.NextAction,
        }),
      ),
    };
  },

  [ActionType.GetParticipantInput]: (a, ctx) => {
    const t = a.Transitions;
    const errors = t.Errors ?? [];
    // The class emits the menu form's three errors in this order.
    const expected = [INPUT_TIME_LIMIT_EXCEEDED, NO_MATCHING_CONDITION, NO_MATCHING_ERROR];
    if (errors.length !== expected.length) return undefined;
    if (errors.some((e, i) => e.ErrorType !== expected[i])) return undefined;
    const [onTimeout, onNoMatch, onError] = errors.map((e) => e.NextAction) as [
      string,
      string,
      string,
    ];
    // The class mirrors NextAction onto the no-match path.
    if (t.NextAction !== onNoMatch) return undefined;
    const conditions = t.Conditions ?? [];
    if (!conditions.every(isCondition)) return undefined;
    const branches: DtmfBranch[] = [];
    for (const c of conditions) {
      if (c.Condition.Operator !== "Equals" || c.Condition.Operands.length !== 1) return undefined;
      const digit = c.Condition.Operands[0]!;
      if (!(DTMF_DIGITS as readonly string[]).includes(digit)) return undefined;
      branches.push({ digit: digit as DtmfDigit, target: c.NextAction });
    }
    const p = a.Parameters;
    if (!paramKeysAre(p, ["InputTimeLimitSeconds", "StoreInput"], ["Text", "SSML", "PromptId"])) {
      return undefined;
    }
    // Only the menu form is modeled; stored input has no conditions and needs
    // InputValidation, which the class does not emit.
    if (p.StoreInput !== "False") return undefined;
    // The class writes the timeout as a plain decimal string, so only that
    // spelling inverts: "5", never 5, "05", or "5.0". The constructor holds
    // the value to its documented range.
    if (typeof p.InputTimeLimitSeconds !== "string") return undefined;
    if (!/^[1-9][0-9]*$/.test(p.InputTimeLimitSeconds)) return undefined;
    const timeoutSeconds = Number(p.InputTimeLimitSeconds);
    const bodyKeys = ["Text", "SSML", "PromptId"].filter((k) => k in p);
    if (bodyKeys.length > 1) return undefined;
    const entries: [string, V][] = [["id", a.Identifier]];
    let body: MessageBody | { text?: never; ssml?: never; prompt?: never } = {};
    if (bodyKeys[0] === "Text" && typeof p.Text === "string") {
      entries.push(["text", p.Text]);
      body = { text: p.Text };
    } else if (bodyKeys[0] === "SSML" && typeof p.SSML === "string") {
      entries.push(["ssml", p.SSML]);
      body = { ssml: p.SSML };
    } else if (bodyKeys[0] === "PromptId") {
      const ref = refSource(
        p.PromptId,
        REFERENCE_FIELDS[ActionType.GetParticipantInput]!.PromptId!,
        ctx,
      );
      if (ref === undefined) return undefined;
      entries.push(["prompt", ref]);
      body = { prompt: cast<never>(p.PromptId) };
    } else if (bodyKeys.length === 1) return undefined;
    entries.push(
      ["timeoutSeconds", timeoutSeconds],
      [
        "branches",
        new ArrV(
          branches.map(
            (b) =>
              new ObjV([
                ["digit", b.digit],
                ["target", b.target as string],
              ]),
          ),
        ),
      ],
      ["onTimeout", onTimeout],
      ["onNoMatch", onNoMatch],
      ["onError", onError],
    );
    return {
      cls: "GetParticipantInput",
      entries,
      block: new GetParticipantInput({
        id: a.Identifier,
        ...body,
        timeoutSeconds,
        branches,
        onTimeout,
        onNoMatch,
        onError,
      }),
    };
  },

  [ActionType.DisconnectParticipant]: (a) =>
    terminal(a, () => new DisconnectParticipant({ id: a.Identifier })),
  [ActionType.EndFlowExecution]: (a) =>
    terminal(a, () => new EndFlowExecution({ id: a.Identifier })),
  [ActionType.TransferContactToAgent]: (a) =>
    terminal(a, () => new TransferContactToAgent({ id: a.Identifier })),
  [ActionType.EndFlowModuleExecution]: (a) =>
    terminal(a, () => new EndFlowModuleExecution({ id: a.Identifier })),

  [ActionType.CheckHoursOfOperation]: (a, ctx) => {
    const t = a.Transitions;
    const errors = t.Errors ?? [];
    const conditions = t.Conditions ?? [];
    if (errors.length !== 1 || errors[0]!.ErrorType !== NO_MATCHING_ERROR) return undefined;
    if (conditions.length !== 2) return undefined;
    const [inHours, outOfHours] = conditions;
    if (stableJson(inHours!.Condition) !== stableJson({ Operator: "Equals", Operands: ["True"] })) {
      return undefined;
    }
    if (
      stableJson(outOfHours!.Condition) !== stableJson({ Operator: "Equals", Operands: ["False"] })
    ) {
      return undefined;
    }
    // The class mirrors NextAction onto the out-of-hours path.
    if (t.NextAction !== outOfHours!.NextAction) return undefined;
    if (!paramKeysAre(a.Parameters, [], ["HoursOfOperationId"])) return undefined;
    const entries: [string, V][] = [["id", a.Identifier]];
    let hours: string | undefined;
    if ("HoursOfOperationId" in a.Parameters) {
      const ref = refSource(a.Parameters.HoursOfOperationId, "hours", ctx);
      if (ref === undefined) return undefined;
      entries.push(["hours", ref]);
      hours = cast<string>(a.Parameters.HoursOfOperationId);
    }
    entries.push(
      ["onInHours", inHours!.NextAction],
      ["onOutOfHours", outOfHours!.NextAction],
      ["onError", errors[0]!.NextAction],
    );
    return {
      cls: "CheckHoursOfOperation",
      entries,
      block: new CheckHoursOfOperation({
        id: a.Identifier,
        ...(hours === undefined ? {} : { hours: cast<never>(hours) }),
        onInHours: inHours!.NextAction,
        onOutOfHours: outOfHours!.NextAction,
        onError: errors[0]!.NextAction,
      }),
    };
  },

  [ActionType.Loop]: (a, ctx) => {
    const t = a.Transitions;
    const errors = t.Errors ?? [];
    if (errors.length > 1 || (errors.length === 1 && errors[0]!.ErrorType !== NO_MATCHING_ERROR)) {
      return undefined;
    }
    const conditions = t.Conditions ?? [];
    if (conditions.length !== 2) return undefined;
    const [cont, done] = conditions;
    if (
      stableJson(cont!.Condition) !== stableJson({ Operator: "Equals", Operands: [LOOP_CONTINUE] })
    ) {
      return undefined;
    }
    if (stableJson(done!.Condition) !== stableJson({ Operator: "Equals", Operands: [LOOP_DONE] })) {
      return undefined;
    }
    // The class mirrors NextAction onto the done path.
    if (t.NextAction !== done!.NextAction) return undefined;
    if (!paramKeysAre(a.Parameters, ["LoopCount"])) return undefined;
    // The console's spelling: a decimal string, or a single JSONPath.
    const raw = a.Parameters.LoopCount;
    if (typeof raw !== "string") return undefined;
    let count: number | string;
    let countV: V;
    if (/^(0|[1-9][0-9]?|100)$/.test(raw)) {
      count = Number(raw);
      countV = count;
    } else if (/^\$\.[A-Za-z0-9_$.[\]'-]+$/.test(raw)) {
      count = raw;
      ctx.jsonPath = true;
      countV = new Raw(`jsonPath(${quoteString(raw)})`);
    } else {
      return undefined;
    }
    const entries: [string, V][] = [
      ["id", a.Identifier],
      ["count", countV],
      ["onContinue", cont!.NextAction],
      ["onDone", done!.NextAction],
    ];
    if (errors.length === 1) entries.push(["onError", errors[0]!.NextAction]);
    return {
      cls: "Loop",
      entries,
      block: new Loop({
        id: a.Identifier,
        count: cast<never>(count),
        onContinue: cont!.NextAction,
        onDone: done!.NextAction,
        ...(errors.length === 1 ? { onError: errors[0]!.NextAction } : {}),
      }),
    };
  },

  [ActionType.Wait]: (a, ctx) => {
    const t = a.Transitions;
    const errors = t.Errors ?? [];
    if (errors.length === 0 || errors.length > 2) return undefined;
    if (errors[0]!.ErrorType !== NO_MATCHING_ERROR) return undefined;
    if (errors.length === 2 && errors[1]!.ErrorType !== PARTICIPANT_NOT_FOUND) return undefined;
    // The class mirrors NextAction onto the catch-all.
    if (t.NextAction !== errors[0]!.NextAction) return undefined;
    const conditions = t.Conditions ?? [];
    if (conditions.length === 0 || !conditions.every(isCondition)) return undefined;
    const [timeout, ...events] = conditions;
    if (
      stableJson(timeout!.Condition) !==
      stableJson({ Operator: "Equals", Operands: [WAIT_COMPLETED] })
    ) {
      return undefined;
    }
    if (!paramKeysAre(a.Parameters, ["TimeLimitSeconds"], ["Events"])) return undefined;
    const listed = a.Parameters.Events;
    const eventNames = events.map((c) => c.Condition.Operands[0]);
    // Events and their conditions name the same events, in the class's order.
    const expected: string[] = listed === undefined ? [] : cast<string[]>(listed);
    if (!Array.isArray(expected) || stableJson(expected) !== stableJson(eventNames)) {
      return undefined;
    }
    const order = WAIT_EVENTS.filter((e) => eventNames.includes(e));
    if (stableJson(order) !== stableJson(eventNames)) return undefined;
    for (const c of events) {
      if (c.Condition.Operator !== "Equals" || c.Condition.Operands.length !== 1) return undefined;
    }
    const bot = eventNames.includes("BotParticipantDisconnected");
    if (bot !== (errors.length === 2)) return undefined;
    // The console's spelling: a decimal string, or a single JSONPath.
    const raw = a.Parameters.TimeLimitSeconds;
    if (typeof raw !== "string") return undefined;
    let seconds: number | string;
    let secondsV: V;
    if (/^[1-9][0-9]*$/.test(raw)) {
      seconds = Number(raw);
      if (
        !Number.isSafeInteger(seconds) ||
        seconds < WAIT_TIMEOUT_MIN ||
        seconds > WAIT_TIMEOUT_MAX
      ) {
        return undefined;
      }
      secondsV = seconds;
    } else if (/^\$\.[A-Za-z0-9_$.[\]'-]+$/.test(raw)) {
      seconds = raw;
      ctx.jsonPath = true;
      secondsV = new Raw(`jsonPath(${quoteString(raw)})`);
    } else {
      return undefined;
    }
    const entries: [string, V][] = [
      ["id", a.Identifier],
      ["timeoutSeconds", secondsV],
      ["onTimeout", timeout!.NextAction],
    ];
    const onEvent: Record<string, string> = {};
    for (const c of events) onEvent[cast<string>(c.Condition.Operands[0])] = c.NextAction;
    if (events.length > 0) {
      entries.push([
        "onEvent",
        new ObjV(events.map((c) => [cast<string>(c.Condition.Operands[0]), c.NextAction])),
      ]);
    }
    entries.push(["onError", errors[0]!.NextAction]);
    if (errors.length === 2) entries.push(["onParticipantNotFound", errors[1]!.NextAction]);
    return {
      cls: "Wait",
      entries,
      block: new Wait({
        id: a.Identifier,
        timeoutSeconds: cast<never>(seconds),
        onTimeout: timeout!.NextAction,
        ...(events.length > 0 ? { onEvent: cast<never>(onEvent) } : {}),
        onError: errors[0]!.NextAction,
        ...(errors.length === 2 ? { onParticipantNotFound: errors[1]!.NextAction } : {}),
      }),
    };
  },

  [ActionType.DistributeByPercentage]: (a) => {
    const t = a.Transitions;
    if (Object.keys(a.Parameters).length !== 0) return undefined;
    const errors = t.Errors ?? [];
    if (errors.length !== 1 || errors[0]!.ErrorType !== NO_MATCHING_CONDITION) return undefined;
    // The console mirrors NextAction onto the remainder branch, and so does the class.
    if (t.NextAction !== errors[0]!.NextAction) return undefined;
    const conditions = t.Conditions ?? [];
    if (conditions.length === 0 || !conditions.every(isCondition)) return undefined;
    const branches: { percent: number; target: string }[] = [];
    let previous = 1;
    for (const c of conditions) {
      const operand = c.Condition.Operands[0];
      if (c.Condition.Operator !== "NumberLessThan" || c.Condition.Operands.length !== 1) {
        return undefined;
      }
      if (typeof operand !== "string" || !/^[1-9][0-9]*$/.test(operand)) return undefined;
      const threshold = Number(operand);
      if (threshold <= previous || threshold > PERCENTAGE_THRESHOLD_MAX) return undefined;
      branches.push({ percent: threshold - previous, target: c.NextAction });
      previous = threshold;
    }
    return {
      cls: "DistributeByPercentage",
      entries: [
        ["id", a.Identifier],
        [
          "branches",
          new ArrV(
            branches.map(
              (b) =>
                new ObjV([
                  ["percent", b.percent],
                  ["target", b.target],
                ]),
            ),
          ),
        ],
        ["onRemainder", errors[0]!.NextAction],
      ],
      block: new DistributeByPercentage({
        id: a.Identifier,
        branches,
        onRemainder: errors[0]!.NextAction,
      }),
    };
  },

  [ActionType.UpdateFlowAttributes]: (a) => {
    const w = wiredTransitions(a.Transitions, NO_MATCHING_ERROR);
    if (w === undefined) return undefined;
    if (!paramKeysAre(a.Parameters, ["FlowAttributes"])) return undefined;
    const raw = a.Parameters.FlowAttributes;
    if (raw === null || typeof raw !== "object" || Array.isArray(raw)) return undefined;
    // The console's value shape: { Value: "<string>" } for every attribute.
    const attributes: Record<string, string> = {};
    for (const [k, v] of Object.entries(raw as Record<string, unknown>)) {
      const entry = v as Record<string, unknown> | null;
      if (entry === null || typeof entry !== "object" || !paramKeysAre(entry, ["Value"])) {
        return undefined;
      }
      if (typeof entry.Value !== "string") return undefined;
      attributes[k] = entry.Value;
    }
    return {
      cls: "UpdateFlowAttributes",
      entries: [
        ["id", a.Identifier],
        ["attributes", toV(attributes)],
        ["next", w.next],
        ["onError", w.onError],
      ],
      block: new UpdateFlowAttributes({
        id: a.Identifier,
        attributes,
        next: w.next,
        onError: w.onError,
      }),
    };
  },

  [ActionType.CheckMetricData]: (a, ctx) => {
    const t = a.Transitions;
    const errors = t.Errors ?? [];
    // The console writes the two errors in either order; the class writes
    // the catch-all first, and the comparison in invertAction re-emits this
    // action in that order, so an export in the other order round-trips as
    // a GenericBlock. Reading them by type keeps the inverter honest about
    // which order it would reproduce.
    const onError = errors.find((e) => e.ErrorType === NO_MATCHING_ERROR);
    const onNoMatch = errors.find((e) => e.ErrorType === NO_MATCHING_CONDITION);
    if (errors.length !== 2 || onError === undefined || onNoMatch === undefined) return undefined;
    // The console mirrors NextAction onto the catch-all, and so does the class.
    if (t.NextAction !== onError.NextAction) return undefined;
    const conditions = t.Conditions ?? [];
    if (conditions.length === 0 || !conditions.every(isCondition)) return undefined;
    if (!paramKeysAre(a.Parameters, ["MetricType"], ["QueueId", "AgentId"])) return undefined;
    const p = a.Parameters;
    if (p.QueueId !== undefined && p.AgentId !== undefined) return undefined;
    const metric = p.MetricType;
    if (typeof metric !== "string" || !(METRIC_TYPES as readonly string[]).includes(metric)) {
      return undefined;
    }
    const entries: [string, V][] = [
      ["id", a.Identifier],
      ["metric", metric],
    ];
    const config: Record<string, unknown> = { id: a.Identifier, metric };
    for (const [key, prop] of [
      ["QueueId", "queue"],
      ["AgentId", "agent"],
    ] as const) {
      if (p[key] === undefined) continue;
      const ref = refSource(p[key], "queue", ctx);
      if (ref === undefined) return undefined;
      entries.push([prop, ref]);
      config[prop] = p[key];
    }
    const branches: { operator: string; operand: string; target: string }[] = [];
    for (const c of conditions) {
      const operand = c.Condition.Operands[0];
      if (
        !(METRIC_OPERATORS as readonly string[]).includes(c.Condition.Operator) ||
        c.Condition.Operands.length !== 1 ||
        typeof operand !== "string"
      ) {
        return undefined;
      }
      branches.push({ operator: c.Condition.Operator, operand, target: c.NextAction });
    }
    if (
      (AGENT_METRIC_TYPES as readonly string[]).includes(metric) &&
      (branches.length !== 1 ||
        branches[0]!.operator !== "NumberGreaterThan" ||
        branches[0]!.operand !== "0")
    ) {
      return undefined;
    }
    entries.push(
      [
        "branches",
        new ArrV(
          branches.map(
            (b) =>
              new ObjV([
                ["operator", b.operator],
                ["operand", b.operand],
                ["target", b.target],
              ]),
          ),
        ),
      ],
      ["onNoMatch", onNoMatch.NextAction],
      ["onError", onError.NextAction],
    );
    return {
      cls: "CheckMetricData",
      entries,
      block: new CheckMetricData(
        cast<never>({
          ...config,
          branches,
          onNoMatch: onNoMatch.NextAction,
          onError: onError.NextAction,
        }),
      ),
    };
  },

  [ActionType.GetMetricData]: (a, ctx) => {
    const w = wiredTransitions(a.Transitions, NO_MATCHING_ERROR);
    if (w === undefined) return undefined;
    const p = a.Parameters;
    if (!paramKeysAre(p, [], ["QueueId", "AgentId", "QueueChannel"])) return undefined;
    if (p.QueueId !== undefined && p.AgentId !== undefined) return undefined;
    const entries: [string, V][] = [["id", a.Identifier]];
    const config: Record<string, unknown> = { id: a.Identifier };
    for (const [key, prop] of [
      ["QueueId", "queue"],
      ["AgentId", "agent"],
    ] as const) {
      if (p[key] === undefined) continue;
      const ref = refSource(p[key], "queue", ctx);
      if (ref === undefined) return undefined;
      entries.push([prop, ref]);
      config[prop] = p[key];
    }
    if (p.QueueChannel !== undefined) {
      const channel = p.QueueChannel;
      if (typeof channel !== "string") return undefined;
      if ((QUEUE_CHANNELS as readonly string[]).includes(channel)) {
        entries.push(["channel", channel]);
      } else if (/^\$\.[A-Za-z0-9_$.[\]'-]+$/.test(channel)) {
        ctx.jsonPath = true;
        entries.push(["channel", new Raw(`jsonPath(${quoteString(channel)})`)]);
      } else {
        return undefined;
      }
      config.channel = channel;
    }
    entries.push(["next", w.next], ["onError", w.onError]);
    return {
      cls: "GetMetricData",
      entries,
      block: new GetMetricData(cast<never>({ ...config, next: w.next, onError: w.onError })),
    };
  },

  [ActionType.Compare]: (a, ctx) => {
    const t = a.Transitions;
    if (t.NextAction !== undefined) return undefined;
    const errors = t.Errors ?? [];
    if (errors.length !== 1 || errors[0]!.ErrorType !== NO_MATCHING_CONDITION) return undefined;
    const conditions = t.Conditions ?? [];
    if (conditions.length === 0 || !conditions.every(isCondition)) return undefined;
    if (!paramKeysAre(a.Parameters, ["ComparisonValue"])) return undefined;
    const value = a.Parameters.ComparisonValue;
    if (typeof value !== "string" || !/^\$\.[A-Za-z0-9_$.[\]'-]+$/.test(value)) return undefined;
    // The emitted config calls jsonPath(); record it so the import is present
    // even when no other action pulls it in through refSource.
    ctx.jsonPath = true;
    const branches = conditions.map((c) => ({
      operator: c.Condition.Operator,
      operands: c.Condition.Operands,
      target: c.NextAction,
    }));
    const entries: [string, V][] = [
      ["id", a.Identifier],
      ["value", new Raw(`jsonPath(${quoteString(value)})`)],
      [
        "branches",
        new ArrV(
          branches.map(
            (b) =>
              new ObjV([
                ["operator", b.operator],
                ["operands", new ArrV([...b.operands])],
                ["target", b.target],
              ]),
          ),
        ),
      ],
      ["onNoMatch", errors[0]!.NextAction],
    ];
    return {
      cls: "Compare",
      entries,
      block: new Compare({
        id: a.Identifier,
        value: cast<never>(value),
        branches,
        onNoMatch: errors[0]!.NextAction,
      }),
    };
  },

  [ActionType.TransferToFlow]: (a, ctx) => {
    const w = wiredTransitions(a.Transitions, NO_MATCHING_ERROR);
    if (w === undefined || !paramKeysAre(a.Parameters, ["ContactFlowId"])) return undefined;
    const ref = refSource(a.Parameters.ContactFlowId, "flow", ctx);
    if (ref === undefined) return undefined;
    return {
      cls: "TransferToFlow",
      entries: [
        ["id", a.Identifier],
        ["flow", ref],
        ["next", w.next],
        ["onError", w.onError],
      ],
      block: new TransferToFlow({
        id: a.Identifier,
        flow: cast<never>(a.Parameters.ContactFlowId),
        next: w.next,
        onError: w.onError,
      }),
    };
  },

  [ActionType.UpdateContactTargetQueue]: (a, ctx) => {
    const w = wiredTransitions(a.Transitions, NO_MATCHING_ERROR);
    if (w === undefined) return undefined;
    const keys = Object.keys(a.Parameters);
    if (keys.length !== 1 || (keys[0] !== "QueueId" && keys[0] !== "AgentId")) return undefined;
    const field = keys[0];
    const ref = refSource(a.Parameters[field], "queue", ctx);
    if (ref === undefined) return undefined;
    const prop = field === "QueueId" ? "queue" : "agent";
    return {
      cls: "UpdateContactTargetQueue",
      entries: [
        ["id", a.Identifier],
        [prop, ref],
        ["next", w.next],
        ["onError", w.onError],
      ],
      block: new UpdateContactTargetQueue(
        cast<never>({
          id: a.Identifier,
          [prop]: a.Parameters[field],
          next: w.next,
          onError: w.onError,
        }),
      ),
    };
  },

  [ActionType.TransferContactToQueue]: (a) => {
    const t = a.Transitions;
    if (Object.keys(a.Parameters).length !== 0) return undefined;
    if (t.NextAction === undefined || (t.Conditions ?? []).length !== 0) return undefined;
    const errors = t.Errors ?? [];
    if (
      errors.length !== 2 ||
      errors[0]!.ErrorType !== "QueueAtCapacity" ||
      errors[1]!.ErrorType !== NO_MATCHING_ERROR
    ) {
      return undefined;
    }
    return {
      cls: "TransferContactToQueue",
      entries: [
        ["id", a.Identifier],
        ["next", t.NextAction],
        ["onQueueAtCapacity", errors[0]!.NextAction],
        ["onError", errors[1]!.NextAction],
      ],
      block: new TransferContactToQueue({
        id: a.Identifier,
        next: t.NextAction,
        onQueueAtCapacity: errors[0]!.NextAction,
        onError: errors[1]!.NextAction,
      }),
    };
  },

  [ActionType.DequeueContactAndTransferToQueue]: (a, ctx) => {
    const t = a.Transitions;
    if (t.NextAction === undefined || (t.Conditions ?? []).length !== 0) return undefined;
    const errors = t.Errors ?? [];
    if (
      errors.length !== 2 ||
      errors[0]!.ErrorType !== "QueueAtCapacity" ||
      errors[1]!.ErrorType !== NO_MATCHING_ERROR
    ) {
      return undefined;
    }
    const keys = Object.keys(a.Parameters);
    if (
      keys.length > 1 ||
      (keys[0] !== undefined && keys[0] !== "QueueId" && keys[0] !== "AgentId")
    ) {
      return undefined;
    }
    const entries: [string, V][] = [["id", a.Identifier]];
    const target: Record<string, unknown> = {};
    const field = keys[0];
    if (field !== undefined) {
      const ref = refSource(a.Parameters[field], "queue", ctx);
      if (ref === undefined) return undefined;
      const prop = field === "QueueId" ? "queue" : "agent";
      entries.push([prop, ref]);
      target[prop] = a.Parameters[field];
    }
    entries.push(
      ["next", t.NextAction],
      ["onQueueAtCapacity", errors[0]!.NextAction],
      ["onError", errors[1]!.NextAction],
    );
    return {
      cls: "DequeueContactAndTransferToQueue",
      entries,
      block: new DequeueContactAndTransferToQueue(
        cast<never>({
          id: a.Identifier,
          ...target,
          next: t.NextAction,
          onQueueAtCapacity: errors[0]!.NextAction,
          onError: errors[1]!.NextAction,
        }),
      ),
    };
  },

  [ActionType.UpdateContactRoutingBehavior]: (a) => {
    const t = a.Transitions;
    if (t.NextAction === undefined) return undefined;
    if ((t.Errors ?? []).length !== 0 || (t.Conditions ?? []).length !== 0) return undefined;
    const keys = Object.keys(a.Parameters);
    if (keys.length !== 1) return undefined;
    const field = keys[0]!;
    if (field !== "QueuePriority" && field !== "QueueTimeAdjustmentSeconds") return undefined;
    // The console's spelling: a decimal string, no leading zero.
    const raw = a.Parameters[field];
    const shape = field === "QueuePriority" ? /^[1-9][0-9]*$/ : /^-?(0|[1-9][0-9]*)$/;
    if (typeof raw !== "string" || !shape.test(raw)) return undefined;
    const value = Number(raw);
    if (!Number.isSafeInteger(value)) return undefined;
    const prop = field === "QueuePriority" ? "queuePriority" : "queueTimeAdjustmentSeconds";
    return {
      cls: "UpdateContactRoutingBehavior",
      entries: [
        ["id", a.Identifier],
        [prop, value],
        ["next", t.NextAction],
      ],
      block: new UpdateContactRoutingBehavior(
        cast<never>({ id: a.Identifier, [prop]: value, next: t.NextAction }),
      ),
    };
  },

  [ActionType.CreateCallbackContact]: (a, ctx) => {
    const w = wiredTransitions(a.Transitions, NO_MATCHING_ERROR);
    if (w === undefined) return undefined;
    const p = a.Parameters;
    const required = ["InitialCallDelaySeconds", "MaximumConnectionAttempts", "RetryDelaySeconds"];
    if (!paramKeysAre(p, required, ["QueueId", "AgentId", "ContactFlowId", "CallerId"])) {
      return undefined;
    }
    if (p.QueueId !== undefined && p.AgentId !== undefined) return undefined;
    const entries: [string, V][] = [["id", a.Identifier]];
    const config: Record<string, unknown> = { id: a.Identifier };
    for (const [key, prop] of [
      ["QueueId", "queue"],
      ["AgentId", "agent"],
    ] as const) {
      if (p[key] === undefined) continue;
      const ref = refSource(p[key], "queue", ctx);
      if (ref === undefined) return undefined;
      entries.push([prop, ref]);
      config[prop] = p[key];
    }
    for (const [key, prop] of [
      ["InitialCallDelaySeconds", "initialCallDelaySeconds"],
      ["MaximumConnectionAttempts", "maximumConnectionAttempts"],
      ["RetryDelaySeconds", "retryDelaySeconds"],
    ] as const) {
      // The console's spelling: a decimal string, no leading zero.
      const raw = p[key];
      if (typeof raw !== "string" || !/^[1-9][0-9]*$/.test(raw)) return undefined;
      const value = Number(raw);
      if (!Number.isSafeInteger(value)) return undefined;
      entries.push([prop, value]);
      config[prop] = value;
    }
    if (p.ContactFlowId !== undefined) {
      const ref = refSource(p.ContactFlowId, "flow", ctx);
      if (ref === undefined) return undefined;
      entries.push(["flow", ref]);
      config.flow = p.ContactFlowId;
    }
    if (p.CallerId !== undefined) {
      if (typeof p.CallerId !== "string") return undefined;
      entries.push(["callerId", p.CallerId]);
      config.callerId = p.CallerId;
    }
    entries.push(["next", w.next], ["onError", w.onError]);
    return {
      cls: "CreateCallbackContact",
      entries,
      block: new CreateCallbackContact(
        cast<never>({ ...config, next: w.next, onError: w.onError }),
      ),
    };
  },

  [ActionType.UpdateContactCallbackNumber]: (a, ctx) => {
    const t = a.Transitions;
    if (t.NextAction === undefined || (t.Conditions ?? []).length !== 0) return undefined;
    const errors = t.Errors ?? [];
    if (
      errors.length !== 2 ||
      errors[0]!.ErrorType !== INVALID_CALLBACK_NUMBER ||
      errors[1]!.ErrorType !== CALLBACK_NUMBER_NOT_DIALABLE
    ) {
      return undefined;
    }
    if (!paramKeysAre(a.Parameters, ["CallbackNumber"])) return undefined;
    const value = a.Parameters.CallbackNumber;
    if (typeof value !== "string" || !/^\$\.[A-Za-z0-9_$.[\]'-]+$/.test(value)) return undefined;
    ctx.jsonPath = true;
    return {
      cls: "UpdateContactCallbackNumber",
      entries: [
        ["id", a.Identifier],
        ["callbackNumber", new Raw(`jsonPath(${quoteString(value)})`)],
        ["next", t.NextAction],
        ["onInvalidNumber", errors[0]!.NextAction],
        ["onNotDialable", errors[1]!.NextAction],
      ],
      block: new UpdateContactCallbackNumber({
        id: a.Identifier,
        callbackNumber: cast<never>(value),
        next: t.NextAction,
        onInvalidNumber: errors[0]!.NextAction,
        onNotDialable: errors[1]!.NextAction,
      }),
    };
  },

  [ActionType.TagContact]: (a) => {
    const w = wiredTransitions(a.Transitions, NO_MATCHING_ERROR);
    if (w === undefined) return undefined;
    if (!paramKeysAre(a.Parameters, ["Tags"])) return undefined;
    const tags = a.Parameters.Tags;
    if (!isStringMap(tags)) return undefined;
    const keys = Object.keys(tags);
    if (keys.length === 0 || keys.length > TAG_LIMIT) return undefined;
    if (keys.some((k) => k.startsWith(SYSTEM_TAG_PREFIX))) return undefined;
    return {
      cls: "TagContact",
      entries: [
        ["id", a.Identifier],
        ["tags", toV(tags)],
        ["next", w.next],
        ["onError", w.onError],
      ],
      block: new TagContact({ id: a.Identifier, tags, next: w.next, onError: w.onError }),
    };
  },

  [ActionType.UntagContact]: (a) => {
    const w = wiredTransitions(a.Transitions, NO_MATCHING_ERROR);
    if (w === undefined) return undefined;
    if (!paramKeysAre(a.Parameters, ["TagKeys"])) return undefined;
    const keys = a.Parameters.TagKeys;
    if (!Array.isArray(keys) || keys.length === 0) return undefined;
    if (!keys.every((k) => typeof k === "string" && k !== "" && !k.startsWith(SYSTEM_TAG_PREFIX))) {
      return undefined;
    }
    return {
      cls: "UntagContact",
      entries: [
        ["id", a.Identifier],
        ["tagKeys", new ArrV([...cast<string[]>(keys)])],
        ["next", w.next],
        ["onError", w.onError],
      ],
      block: new UntagContact({
        id: a.Identifier,
        tagKeys: cast<string[]>(keys),
        next: w.next,
        onError: w.onError,
      }),
    };
  },

  [ActionType.UpdateContactTextToSpeechVoice]: (a, ctx) => {
    // The catch-all is optional: the page requires it, the service and the
    // console's exports do not.
    const t = a.Transitions;
    if (t.NextAction === undefined || (t.Conditions ?? []).length !== 0) return undefined;
    const errors = t.Errors ?? [];
    if (errors.length > 1 || (errors.length === 1 && errors[0]!.ErrorType !== NO_MATCHING_ERROR)) {
      return undefined;
    }
    const w = { next: t.NextAction, onError: errors[0]?.NextAction };
    if (w === undefined) return undefined;
    const p = a.Parameters;
    if (!paramKeysAre(p, ["TextToSpeechVoice"], ["TextToSpeechEngine", "TextToSpeechStyle"])) {
      return undefined;
    }
    const voice = p.TextToSpeechVoice;
    if (typeof voice !== "string" || voice === "") return undefined;
    const entries: [string, V][] = [
      ["id", a.Identifier],
      ["voice", voice],
    ];
    const config: Record<string, unknown> = { id: a.Identifier, voice };
    for (const [key, prop, allowed] of [
      ["TextToSpeechEngine", "engine", TTS_ENGINES],
      ["TextToSpeechStyle", "style", TTS_STYLES],
    ] as const) {
      const value = p[key];
      if (value === undefined) continue;
      if (typeof value !== "string") return undefined;
      if ((allowed as readonly string[]).includes(value)) {
        entries.push([prop, value]);
      } else if (/^\$\.[A-Za-z0-9_$.[\]'-]+$/.test(value)) {
        ctx.jsonPath = true;
        entries.push([prop, new Raw(`jsonPath(${quoteString(value)})`)]);
      } else {
        return undefined;
      }
      config[prop] = value;
    }
    entries.push(["next", w.next]);
    if (w.onError !== undefined) entries.push(["onError", w.onError]);
    return {
      cls: "UpdateContactTextToSpeechVoice",
      entries,
      block: new UpdateContactTextToSpeechVoice(
        cast<never>({ ...config, next: w.next, onError: w.onError }),
      ),
    };
  },

  [ActionType.UpdateContactData]: (a) => {
    const w = wiredTransitions(a.Transitions, NO_MATCHING_ERROR);
    if (w === undefined) return undefined;
    const p = a.Parameters;
    const strings = [
      ["Name", "name"],
      ["Description", "description"],
      ["LanguageCode", "languageCode"],
      ["CustomerId", "customerId"],
      ["WatchlistId", "watchlistId"],
      ["WisdomSessionArn", "wisdomSessionArn"],
    ] as const;
    const flags = [
      ["IsVoiceIdStreamingEnabled", "voiceIdStreaming"],
      ["IsVoiceAuthenticationEnabled", "voiceAuthentication"],
      ["IsFraudDetectionEnabled", "fraudDetection"],
    ] as const;
    const numbers = [
      [
        "VoiceAuthenticationThreshold",
        "voiceAuthenticationThreshold",
        VOICE_ID_THRESHOLD_MIN,
        VOICE_ID_THRESHOLD_MAX,
      ],
      [
        "VoiceAuthenticationResponseTime",
        "voiceAuthenticationResponseTime",
        VOICE_ID_RESPONSE_TIME_MIN,
        VOICE_ID_RESPONSE_TIME_MAX,
      ],
      [
        "FraudDetectionThreshold",
        "fraudDetectionThreshold",
        VOICE_ID_THRESHOLD_MIN,
        VOICE_ID_THRESHOLD_MAX,
      ],
    ] as const;
    const optional = [
      ...strings.map(([k]) => k),
      "References",
      ...flags.map(([k]) => k),
      ...numbers.map(([k]) => k),
    ];
    if (!paramKeysAre(p, [], [...optional, "TargetContact"])) return undefined;
    const target = p.TargetContact;
    if (
      target !== undefined &&
      (typeof target !== "string" || !(TARGET_CONTACTS as readonly string[]).includes(target))
    ) {
      return undefined;
    }
    const entries: [string, V][] = [["id", a.Identifier]];
    const config: Record<string, unknown> = { id: a.Identifier };
    if (target !== undefined) {
      entries.push(["targetContact", target]);
      config.targetContact = target;
    }
    for (const [key, prop] of strings) {
      if (p[key] === undefined) continue;
      if (typeof p[key] !== "string") return undefined;
      entries.push([prop, p[key]]);
      config[prop] = p[key];
    }
    if (p.References !== undefined) {
      if (!isStringMap(p.References)) return undefined;
      entries.push(["references", toV(p.References)]);
      config.references = p.References;
    }
    for (const [key, prop] of flags) {
      if (p[key] === undefined) continue;
      if (p[key] !== "TRUE" && p[key] !== "FALSE") return undefined;
      entries.push([prop, p[key] === "TRUE"]);
      config[prop] = p[key] === "TRUE";
    }
    for (const [key, prop, min, max] of numbers) {
      const raw = p[key];
      if (raw === undefined) continue;
      if (typeof raw !== "string" || !/^(0|[1-9][0-9]*)$/.test(raw)) return undefined;
      const value = Number(raw);
      if (value < min || value > max) return undefined;
      entries.push([prop, value]);
      config[prop] = value;
    }
    entries.push(["next", w.next], ["onError", w.onError]);
    return {
      cls: "UpdateContactData",
      entries,
      block: new UpdateContactData(cast<never>({ ...config, next: w.next, onError: w.onError })),
    };
  },

  [ActionType.UpdateContactEventHooks]: (a, ctx) => {
    const w = wiredTransitions(a.Transitions, NO_MATCHING_ERROR);
    if (w === undefined) return undefined;
    if (!paramKeysAre(a.Parameters, ["EventHooks"])) return undefined;
    const hooks = a.Parameters.EventHooks;
    if (hooks === null || typeof hooks !== "object" || Array.isArray(hooks)) return undefined;
    const keys = Object.keys(hooks);
    if (keys.length !== 1) return undefined;
    const hook = keys[0]!;
    if (!(EVENT_HOOKS as readonly string[]).includes(hook)) return undefined;
    const value = (hooks as Record<string, unknown>)[hook];
    const ref = refSource(value, "flow", ctx);
    if (ref === undefined) return undefined;
    return {
      cls: "UpdateContactEventHooks",
      entries: [
        ["id", a.Identifier],
        ["hook", hook],
        ["flow", ref],
        ["next", w.next],
        ["onError", w.onError],
      ],
      block: new UpdateContactEventHooks({
        id: a.Identifier,
        hook: cast<never>(hook),
        flow: cast<never>(value),
        next: w.next,
        onError: w.onError,
      }),
    };
  },

  [ActionType.UpdateContactAttributes]: (a) => {
    const w = wiredTransitions(a.Transitions, NO_MATCHING_ERROR);
    if (w === undefined) return undefined;
    if (!paramKeysAre(a.Parameters, ["Attributes", "TargetContact"])) return undefined;
    const attributes = a.Parameters.Attributes;
    const target = a.Parameters.TargetContact;
    if (!isStringMap(attributes)) return undefined;
    if (target !== "Current" && target !== "Related") return undefined;
    const entries: [string, V][] = [
      ["id", a.Identifier],
      ["attributes", toV(attributes)],
    ];
    if (target === "Related") entries.push(["targetContact", "Related"]);
    entries.push(["next", w.next], ["onError", w.onError]);
    return {
      cls: "UpdateContactAttributes",
      entries,
      block: new UpdateContactAttributes({
        id: a.Identifier,
        attributes,
        ...(target === "Related" ? { targetContact: target } : {}),
        next: w.next,
        onError: w.onError,
      }),
    };
  },

  [ActionType.UpdateContactRecordingBehavior]: (a) => {
    const t = a.Transitions;
    if (t.NextAction === undefined) return undefined;
    if ((t.Errors ?? []).length !== 0 || (t.Conditions ?? []).length !== 0) return undefined;
    if (!paramKeysAre(a.Parameters, ["RecordingBehavior"])) return undefined;
    const rb = a.Parameters.RecordingBehavior as Record<string, unknown> | null;
    if (rb === null || typeof rb !== "object" || Array.isArray(rb)) return undefined;
    if (
      !paramKeysAre(
        rb,
        ["RecordedParticipants"],
        ["ScreenRecordedParticipants", "IVRRecordingBehavior"],
      )
    ) {
      return undefined;
    }
    const recorded = rb.RecordedParticipants;
    if (!Array.isArray(recorded) || !recorded.every((p) => p === "Agent" || p === "Customer")) {
      return undefined;
    }
    const entries: [string, V][] = [
      ["id", a.Identifier],
      ["recordedParticipants", new ArrV([...recorded])],
    ];
    const screen = rb.ScreenRecordedParticipants;
    if (screen !== undefined) {
      if (!Array.isArray(screen) || !screen.every((p) => p === "Agent")) return undefined;
      entries.push(["screenRecordedParticipants", new ArrV([...screen])]);
    }
    const ivr = rb.IVRRecordingBehavior;
    if (ivr !== undefined) {
      if (ivr !== "Enabled" && ivr !== "Disabled") return undefined;
      entries.push(["ivrRecordingBehavior", ivr]);
    }
    entries.push(["next", t.NextAction]);
    return {
      cls: "UpdateContactRecordingBehavior",
      entries,
      block: new UpdateContactRecordingBehavior({
        id: a.Identifier,
        recordedParticipants: cast<never>(recorded),
        ...(screen === undefined ? {} : { screenRecordedParticipants: cast<never>(screen) }),
        ...(ivr === undefined ? {} : { ivrRecordingBehavior: ivr }),
        next: t.NextAction,
      }),
    };
  },

  [ActionType.UpdateContactRecordingAndAnalyticsBehavior]: (a) => {
    const t = a.Transitions;
    if (t.NextAction === undefined || (t.Conditions ?? []).length !== 0) return undefined;
    const errors = t.Errors ?? [];
    if (
      errors.length !== 2 ||
      errors[0]!.ErrorType !== NO_MATCHING_ERROR ||
      errors[1]!.ErrorType !== CHANNEL_MISMATCH
    ) {
      return undefined;
    }
    // The voice recording form or the screen recording form, never both (the
    // service refuses two objects on one block); the chat form and the voice
    // analytics settings stay generic.
    if (!paramKeysAre(a.Parameters, [], ["VoiceBehavior", "ScreenRecordingBehavior"])) {
      return undefined;
    }
    const entries: [string, V][] = [["id", a.Identifier]];
    const config: Record<string, unknown> = { id: a.Identifier };
    const vb = a.Parameters.VoiceBehavior as Record<string, unknown> | undefined;
    if (vb !== undefined) {
      if (vb === null || typeof vb !== "object" || Array.isArray(vb)) return undefined;
      if (!paramKeysAre(vb, ["VoiceRecordingBehavior"])) return undefined;
      const rb = vb.VoiceRecordingBehavior as Record<string, unknown> | null;
      if (rb === null || typeof rb !== "object" || Array.isArray(rb)) return undefined;
      if (!paramKeysAre(rb, ["RecordedParticipants"], ["IVRRecordingBehavior"])) return undefined;
      const recorded = rb.RecordedParticipants;
      if (!Array.isArray(recorded) || !recorded.every((p) => p === "Agent" || p === "Customer")) {
        return undefined;
      }
      const voice: [string, V][] = [["recordedParticipants", new ArrV([...recorded])]];
      const voiceConfig: Record<string, unknown> = { recordedParticipants: recorded };
      const ivr = rb.IVRRecordingBehavior;
      if (ivr !== undefined) {
        if (ivr !== "Enabled" && ivr !== "Disabled") return undefined;
        voice.push(["ivrRecordingBehavior", ivr]);
        voiceConfig.ivrRecordingBehavior = ivr;
      }
      entries.push(["voice", new ObjV(voice)]);
      config.voice = voiceConfig;
    }
    const sb = a.Parameters.ScreenRecordingBehavior as Record<string, unknown> | undefined;
    if (sb !== undefined) {
      if (sb === null || typeof sb !== "object" || Array.isArray(sb)) return undefined;
      if (!paramKeysAre(sb, ["ScreenRecordedParticipants"])) return undefined;
      const screen = sb.ScreenRecordedParticipants;
      if (!Array.isArray(screen) || !screen.every((p) => p === "Agent")) return undefined;
      entries.push(["screenRecordedParticipants", new ArrV([...screen])]);
      config.screenRecordedParticipants = screen;
    }
    if ((vb === undefined) === (sb === undefined)) return undefined;
    entries.push(
      ["next", t.NextAction],
      ["onError", errors[0]!.NextAction],
      ["onChannelMismatch", errors[1]!.NextAction],
    );
    return {
      cls: "UpdateContactRecordingAndAnalyticsBehavior",
      entries,
      block: new UpdateContactRecordingAndAnalyticsBehavior(
        cast<never>({
          ...config,
          next: t.NextAction,
          onError: errors[0]!.NextAction,
          onChannelMismatch: errors[1]!.NextAction,
        }),
      ),
    };
  },

  [ActionType.UpdateFlowLoggingBehavior]: (a) => {
    const t = a.Transitions;
    if (t.NextAction === undefined) return undefined;
    if ((t.Errors ?? []).length !== 0 || (t.Conditions ?? []).length !== 0) return undefined;
    if (!paramKeysAre(a.Parameters, ["FlowLoggingBehavior"])) return undefined;
    const behavior = a.Parameters.FlowLoggingBehavior;
    if (behavior !== "Enabled" && behavior !== "Disabled") return undefined;
    return {
      cls: "UpdateFlowLoggingBehavior",
      entries: [
        ["id", a.Identifier],
        ["behavior", behavior],
        ["next", t.NextAction],
      ],
      block: new UpdateFlowLoggingBehavior({ id: a.Identifier, behavior, next: t.NextAction }),
    };
  },

  [ActionType.InvokeFlowModule]: (a, ctx) => {
    const w = wiredTransitions(a.Transitions, NO_MATCHING_ERROR);
    if (w === undefined || !paramKeysAre(a.Parameters, ["FlowModuleId"])) return undefined;
    const ref = refSource(a.Parameters.FlowModuleId, "module", ctx);
    if (ref === undefined) return undefined;
    return {
      cls: "InvokeFlowModule",
      entries: [
        ["id", a.Identifier],
        ["module", ref],
        ["next", w.next],
        ["onError", w.onError],
      ],
      block: new InvokeFlowModule({
        id: a.Identifier,
        module: cast<never>(a.Parameters.FlowModuleId),
        next: w.next,
        onError: w.onError,
      }),
    };
  },

  [ActionType.InvokeLambdaFunction]: (a, ctx) => {
    const w = wiredTransitions(a.Transitions, NO_MATCHING_ERROR);
    if (w === undefined) return undefined;
    const p = a.Parameters;
    if (
      !paramKeysAre(
        p,
        ["LambdaFunctionARN", "InvocationTimeLimitSeconds", "InvocationType"],
        ["LambdaInvocationAttributes", "ResponseValidation"],
      )
    ) {
      return undefined;
    }
    const ref = refSource(p.LambdaFunctionARN, "lambda", ctx);
    if (ref === undefined) return undefined;
    const timeout = p.InvocationTimeLimitSeconds;
    if (typeof timeout !== "number") return undefined;
    const invocationType = p.InvocationType;
    if (invocationType !== "SYNCHRONOUS" && invocationType !== "ASYNCHRONOUS") return undefined;
    const entries: [string, V][] = [
      ["id", a.Identifier],
      ["lambda", ref],
      ["timeoutSeconds", timeout],
    ];
    if (invocationType === "ASYNCHRONOUS") entries.push(["invocationType", invocationType]);
    const attributes = p.LambdaInvocationAttributes;
    if (attributes !== undefined) {
      if (!isStringMap(attributes)) return undefined;
      entries.push(["attributes", toV(attributes)]);
    }
    let responseType: "STRING_MAP" | "JSON" | undefined;
    if (p.ResponseValidation !== undefined) {
      const rv = p.ResponseValidation as Record<string, unknown> | null;
      if (rv === null || typeof rv !== "object" || !paramKeysAre(rv, ["ResponseType"])) {
        return undefined;
      }
      if (rv.ResponseType !== "STRING_MAP" && rv.ResponseType !== "JSON") return undefined;
      responseType = rv.ResponseType;
      entries.push(["responseType", responseType]);
    }
    entries.push(["next", w.next], ["onError", w.onError]);
    return {
      cls: "InvokeLambdaFunction",
      entries,
      block: new InvokeLambdaFunction({
        id: a.Identifier,
        lambda: cast<never>(p.LambdaFunctionARN),
        timeoutSeconds: timeout,
        ...(invocationType === "ASYNCHRONOUS" ? { invocationType } : {}),
        ...(attributes === undefined
          ? {}
          : { attributes: cast<Record<string, string>>(attributes) }),
        ...(responseType === undefined ? {} : { responseType }),
        next: w.next,
        onError: w.onError,
      }),
    };
  },
};

function invertGeneric(a: FlowAction): Inversion {
  const entries: [string, V][] = [
    ["id", a.Identifier],
    ["type", a.Type],
  ];
  const cfg: GenericBlockConfig = { id: a.Identifier, type: a.Type };
  // Connect omits Parameters and could omit Transitions on an action that has
  // none, and a document read off disk is not guaranteed to have been through
  // export's normalization. GenericBlock itself already defaults both, so
  // matching it here keeps an unmodeled action degrading rather than throwing
  // "Cannot convert undefined or null to object".
  const parameters = a.Parameters ?? {};
  if (Object.keys(parameters).length > 0) {
    entries.push(["parameters", toV(parameters)]);
    cfg.parameters = parameters;
  }
  const t = a.Transitions ?? {};
  if (t.NextAction !== undefined) {
    entries.push(["next", t.NextAction]);
    cfg.next = t.NextAction;
  }
  const errors = t.Errors ?? [];
  if (errors.length > 0) {
    entries.push([
      "errors",
      new ArrV(
        errors.map(
          (e: ErrorTransition) =>
            new ObjV([
              ["errorType", e.ErrorType],
              ["target", e.NextAction],
            ]),
        ),
      ),
    ]);
    cfg.errors = errors.map((e) => ({ errorType: e.ErrorType, target: e.NextAction }));
  }
  const conditions = t.Conditions ?? [];
  if (conditions.length > 0) {
    entries.push([
      "conditions",
      new ArrV(
        conditions.map(
          (c) =>
            new ObjV([
              ["target", c.NextAction],
              ["operator", c.Condition.Operator],
              ["operands", new ArrV([...c.Condition.Operands])],
            ]),
        ),
      ),
    ]);
    cfg.conditions = conditions.map((c) => ({
      target: c.NextAction,
      operator: c.Condition.Operator,
      operands: c.Condition.Operands,
    }));
  }
  return { cls: "GenericBlock", entries, block: new GenericBlock(cfg) };
}

/** Exact inversion or the GenericBlock fallback; never lossy. */
function invertAction(a: FlowAction, ctx: Ctx): Inversion {
  const inverter = INVERTERS[a.Type];
  if (inverter !== undefined) {
    try {
      const scratch: Ctx = { refs: false, jsonPath: false };
      const candidate = inverter(a, scratch);
      if (candidate !== undefined && stableJson(candidate.block.toAction()) === stableJson(a)) {
        ctx.refs = ctx.refs || scratch.refs;
        ctx.jsonPath = ctx.jsonPath || scratch.jsonPath;
        return candidate;
      }
    } catch {
      // Constructor validation rejected the shape; fall through to generic.
    }
  }
  return invertGeneric(a);
}

// ---------------------------------------------------------------------------
// @keep comments
// ---------------------------------------------------------------------------

/** Comment lines marked `@keep`, above the export function and above each block by id. */
export interface KeepComments {
  beforeExport: string[];
  beforeBlock: Map<string, string[]>;
}

const NEW_BLOCK = /^new [A-Za-z_$][A-Za-z0-9_$]*\(\{/;
const BLOCK_ID = /\bid: (["'])((?:[^"'\\]|\\.)*)\1/;

/** The `@keep` comment lines of a generated source, keyed as codegen re-attaches them. */
export function extractKeepComments(previous: string): KeepComments {
  const out: KeepComments = { beforeExport: [], beforeBlock: new Map() };
  const lines = previous.split("\n");
  let pending: string[] = [];
  for (let i = 0; i < lines.length; i++) {
    const trimmed = lines[i]!.trim();
    if (trimmed.startsWith("//")) {
      pending.push(trimmed);
      continue;
    }
    const keeps = pending.filter((l) => l.includes("@keep"));
    pending = [];
    if (keeps.length === 0) continue;
    if (trimmed.startsWith("export function ")) {
      out.beforeExport = keeps;
    } else if (NEW_BLOCK.test(trimmed)) {
      // The id property is on this line or within the next few.
      for (let j = i; j < Math.min(i + 5, lines.length); j++) {
        const m = BLOCK_ID.exec(lines[j]!);
        if (m !== null) {
          out.beforeBlock.set(m[2]!, keeps);
          break;
        }
      }
    }
  }
  return out;
}

// ---------------------------------------------------------------------------
// Naming
// ---------------------------------------------------------------------------

const RESERVED_WORDS = new Set([
  "await",
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "enum",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "function",
  "if",
  "implements",
  "import",
  "in",
  "instanceof",
  "interface",
  "let",
  "new",
  "null",
  "package",
  "private",
  "protected",
  "public",
  "return",
  "static",
  "super",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "typeof",
  "var",
  "void",
  "while",
  "with",
  "yield",
]);

/**
 * The exported factory's name: camelCase of the flow name, prefixed with
 * "flow" when it would start with a digit, hit a reserved word, or collide
 * with an identifier the file imports (a flow named "json-path" must not emit
 * `export function jsonPath` next to `import { jsonPath }`).
 */
export function factoryName(name: string, taken: ReadonlySet<string> = new Set()): string {
  const parts = name.split(/[^A-Za-z0-9]+/).filter((p) => p.length > 0);
  if (parts.length === 0) {
    throw new Error(`Cannot derive a factory name from flow name "${name}".`);
  }
  let candidate = parts.map((p, i) => (i === 0 ? p : p[0]!.toUpperCase() + p.slice(1))).join("");
  while (/^[0-9]/.test(candidate) || RESERVED_WORDS.has(candidate) || taken.has(candidate)) {
    candidate = `flow${candidate[0]!.toUpperCase()}${candidate.slice(1)}`;
  }
  return candidate;
}

// ---------------------------------------------------------------------------
// Assembly
// ---------------------------------------------------------------------------

function flowConfigEntries(doc: FlowDoc): [string, V][] {
  const entries: [string, V][] = [["name", doc.name]];
  if (doc.displayName !== undefined) entries.push(["displayName", doc.displayName]);
  if (doc.description !== undefined) entries.push(["description", doc.description]);
  if (doc.kind !== "module") entries.push(["connectType", doc.connectType]);
  // A module's empty Settings is synth's default, so it is not worth emitting;
  // a non-empty one must be, or synth would re-default it and the round trip
  // would silently lose module configuration.
  const settings = doc.content.Settings;
  if (doc.kind === "module" && settings !== undefined && Object.keys(settings).length > 0) {
    entries.push(["settings", toV(settings)]);
  }
  const first = doc.content.Actions[0];
  if (first !== undefined && doc.content.StartAction !== first.Identifier) {
    entries.push(["start", doc.content.StartAction]);
  }
  // Layout equal to deterministic auto-layout is a derivable default; only
  // hand-placed positions are worth carrying in source. Either way
  // synth(codegen(doc)) reproduces doc.layout.
  if (doc.layout !== undefined) {
    const auto = autoLayout(doc.content.Actions, doc.content.StartAction);
    if (stableJson(doc.layout) !== stableJson(auto)) {
      const layoutEntries = Object.keys(doc.layout)
        .sort()
        .map((id): [string, V] => {
          const p = doc.layout![id] as Point;
          return [
            id,
            new ObjV([
              ["x", p.x],
              ["y", p.y],
            ]),
          ];
        });
      entries.push(["layout", new ObjV(layoutEntries)]);
    }
  }
  return entries;
}

function renderBlock(inv: Inversion, indent: string): string {
  const head = `new ${inv.cls}(`;
  if (inv.entries.length === 1) {
    const flat = inlineV(new ObjV(inv.entries));
    if (flat !== undefined && indent.length + head.length + flat.length + 2 <= PRINT_WIDTH) {
      return `${head}${flat})`;
    }
  }
  return `${head}${printBrokenObject(inv.entries, indent)})`;
}

/** A block's single-line form, or undefined when it must break. */
function inlineBlock(inv: Inversion): string | undefined {
  if (inv.entries.length !== 1) return undefined;
  const flat = inlineV(new ObjV(inv.entries));
  return flat === undefined ? undefined : `new ${inv.cls}(${flat})`;
}

export function codegen(doc: FlowDoc, options: CodegenOptions = {}): string {
  assertFlowDoc(doc, "codegen");
  if (doc.kind === "module" && doc.connectType !== "MODULE") {
    throw new Error(`FlowDoc kind "module" requires connectType MODULE, got ${doc.connectType}.`);
  }
  if (doc.content.Actions.length === 0) {
    throw new Error(`Flow "${doc.name}" has no actions; nothing to generate.`);
  }
  const spec = options.moduleSpecifier ?? DEFAULT_MODULE_SPECIFIER;
  const keep =
    options.keep ??
    (options.previous === undefined
      ? { beforeExport: [], beforeBlock: new Map<string, string[]>() }
      : extractKeepComments(options.previous));

  const ctx: Ctx = { refs: false, jsonPath: false };
  const inversions = doc.content.Actions.map((a) => invertAction(a, ctx));

  const flowClass = doc.kind === "module" ? "FlowModule" : "Flow";
  const imports = new Set<string>([flowClass, ...inversions.map((i) => i.cls)]);
  if (ctx.refs) imports.add("Refs");
  if (ctx.jsonPath) imports.add("jsonPath");
  const names = [...imports].sort();

  const importInline = `import { ${names.join(", ")} } from ${quoteString(spec)};`;
  const importSource =
    importInline.length <= PRINT_WIDTH
      ? importInline
      : `import {\n${names.map((n) => `  ${n},`).join("\n")}\n} from ${quoteString(spec)};`;

  const fn = factoryName(doc.name, imports);
  const cfgEntries = flowConfigEntries(doc);

  // The whole return statement collapses to one line when Prettier would:
  // every argument fits inline and the line stays within the print width.
  const cfgInline = inlineV(new ObjV(cfgEntries));
  const argInlines = inversions.map(inlineBlock);
  const hasBlockComments = inversions.some((i) => keep.beforeBlock.has(i.block.id));
  let body: string;
  const oneLine =
    cfgInline === undefined || argInlines.some((a) => a === undefined)
      ? undefined
      : `  return new ${flowClass}(${cfgInline}).add(${argInlines.join(", ")});`;
  if (oneLine !== undefined && oneLine.length <= PRINT_WIDTH && !hasBlockComments) {
    body = oneLine;
  } else {
    const openInline =
      cfgInline === undefined ? undefined : `  return new ${flowClass}(${cfgInline}).add(`;
    const open =
      openInline !== undefined && openInline.length <= PRINT_WIDTH
        ? openInline
        : `  return new ${flowClass}(${printBrokenObject(cfgEntries, "  ")}).add(`;
    const args: string[] = [];
    for (const inv of inversions) {
      for (const c of keep.beforeBlock.get(inv.block.id) ?? []) args.push(`    ${c}`);
      args.push(`    ${renderBlock(inv, "    ")},`);
    }
    body = `${open}\n${args.join("\n")}\n  );`;
  }

  const lines: string[] = [...generatedMarker(doc.name), "", importSource, ""];
  for (const c of keep.beforeExport) lines.push(c);
  lines.push(`export function ${fn}(): ${flowClass} {`, body, "}");
  return lines.join("\n") + "\n";
}
