/*
 * Copyright 2026 The flow-as-code Authors
 * SPDX-License-Identifier: Apache-2.0
 */
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import type { FlowAction, FlowDoc } from "./index.js";
import {
  ActionType,
  canonicalize,
  codegen,
  DisconnectParticipant,
  factoryName,
  Flow,
  GenericBlock,
  GetParticipantInput,
  MessageParticipant,
  Refs,
  synth,
  UpdateContactAttributes,
} from "./index.js";

const demoDoc = (): FlowDoc =>
  JSON.parse(
    readFileSync(
      new URL("../../../conformance/demo/appointment-line.flowdoc.json", import.meta.url),
      "utf8",
    ),
  ) as FlowDoc;

/** A minimal hand-rolled FlowDoc for shapes the builder cannot produce. */
function docWith(actions: FlowDoc["content"]["Actions"]): FlowDoc {
  return {
    flowdoc: "0.2",
    kind: "flow",
    name: "hand-rolled",
    connectType: "CONTACT_FLOW",
    content: { Version: "2019-10-30", StartAction: actions[0]!.Identifier, Actions: actions },
  };
}

describe("factoryName", () => {
  it("camelCases slugs", () => {
    expect(factoryName("appointment-line")).toBe("appointmentLine");
    expect(factoryName("main")).toBe("main");
  });

  it("guards names that are not valid identifiers", () => {
    expect(factoryName("24-7-line")).toBe("flow247Line");
    expect(factoryName("return")).toBe("flowReturn");
  });
});

describe("codegen emission", () => {
  it("opens with a neutral banner naming the document, not a licence header", () => {
    // The output is written into a user's project and is their file. Stamping
    // this repository's copyright on it would be a claim we do not have.
    const source = codegen(demoDoc());
    expect(source.split("\n").slice(0, 2)).toEqual([
      "// Generated by @flow-as-code/core codegen from appointment-line.flowdoc.json.",
      "// Edits to structure regenerate; comments marked @keep survive.",
    ]);
    expect(source).not.toContain("SPDX-License-Identifier");
    expect(source).not.toContain("Copyright");
  });

  it("defaults the import to the published package", () => {
    expect(codegen(demoDoc())).toContain('} from "@flow-as-code/core";');
  });

  it("honors options.moduleSpecifier", () => {
    expect(codegen(demoDoc(), { moduleSpecifier: "../index.js" })).toContain(
      '} from "../index.js";',
    );
  });

  it("omits layout when it equals the deterministic auto-layout", () => {
    // The demo fixture's layout is synth's auto-layout (see synth.test.ts).
    expect(codegen(demoDoc())).not.toContain("layout:");
  });

  it("emits hand-placed layout and an explicit start verbatim", () => {
    const doc = synth(
      new Flow({
        name: "placed",
        start: "greet",
        layout: { greet: { x: 12, y: 34 }, bye: { x: 56, y: 78 } },
      }).add(
        new GenericBlock({ id: "warm-up", type: "UpdateFlowLoggingBehavior", next: "greet" }),
        new MessageParticipant({ id: "greet", text: "hi", next: "bye", onError: "bye" }),
        new DisconnectParticipant({ id: "bye" }),
      ),
      { includeMeta: false },
    );
    const out = codegen(doc);
    expect(out).toContain('start: "greet",');
    expect(out).toContain("layout: {");
    expect(out).toContain("bye: { x: 56, y: 78 },");
    expect(out).toContain("greet: { x: 12, y: 34 },");
  });

  it("keeps a default TargetContact implicit and emits a non-default one", () => {
    const doc = synth(
      new Flow({ name: "attrs" }).add(
        new UpdateContactAttributes({
          id: "set-current",
          attributes: { a: "1" },
          next: "set-related",
          onError: "set-related",
        }),
        new UpdateContactAttributes({
          id: "set-related",
          attributes: { b: "2" },
          targetContact: "Related",
          next: "bye",
          onError: "bye",
        }),
        new DisconnectParticipant({ id: "bye" }),
      ),
      { includeMeta: false },
    );
    const out = codegen(doc);
    expect(out).not.toContain('targetContact: "Current"');
    expect(out.match(/targetContact: "Related"/g)).toHaveLength(1);
  });

  it("throws on a module doc with a non-MODULE connect type", () => {
    const doc = { ...demoDoc(), kind: "module" as const };
    expect(() => codegen(doc)).toThrow(/requires connectType MODULE/);
  });
});

describe("GenericBlock fallback keeps the round-trip lossless", () => {
  it("falls back when a modeled Type carries an extra parameter", () => {
    const doc = synth(
      new Flow({ name: "extra-param" }).add(
        new GenericBlock({
          id: "odd",
          type: "MessageParticipant",
          parameters: { Text: "hi", Unmodeled: "true" },
          next: "bye",
          errors: [{ errorType: "NoMatchingError", target: "bye" }],
        }),
        new DisconnectParticipant({ id: "bye" }),
      ),
      { includeMeta: false },
    );
    const out = codegen(doc);
    expect(out).toContain(
      'new GenericBlock({\n      id: "odd",\n      type: "MessageParticipant",',
    );
    expect(out).not.toContain("new MessageParticipant(");
  });

  it("falls back when a reference field holds a token of the wrong type", () => {
    const doc = synth(
      new Flow({ name: "wrong-ref" }).add(
        new GenericBlock({
          id: "set-queue",
          type: "UpdateContactTargetQueue",
          parameters: { QueueId: "${cdref:lambda:not-a-queue}" },
          next: "bye",
          errors: [{ errorType: "NoMatchingError", target: "bye" }],
        }),
        new DisconnectParticipant({ id: "bye" }),
      ),
      { includeMeta: false },
    );
    const out = codegen(doc);
    expect(out).toContain("new GenericBlock(");
    expect(out).toContain('QueueId: "${cdref:lambda:not-a-queue}"');
    expect(out).not.toContain("Refs.");
  });

  it("falls back when a modeled Type misses its required error branch", () => {
    const doc = docWith([
      {
        Identifier: "no-error-branch",
        Type: "MessageParticipant",
        Parameters: { Text: "hi" },
        Transitions: { NextAction: "bye", Errors: [], Conditions: [] },
      },
      { Identifier: "bye", Type: "DisconnectParticipant", Parameters: {}, Transitions: {} },
    ]);
    const out = codegen(doc);
    expect(out).toContain('type: "MessageParticipant"');
    expect(out).not.toContain("new MessageParticipant(");
  });

  it("keeps tokens inside GenericBlock parameters as verbatim strings", () => {
    const doc = synth(
      new Flow({ name: "passthrough" }).add(
        new GenericBlock({
          id: "lex",
          type: "ConnectParticipantWithLexBot",
          parameters: { LexV2Bot: "${cdref:lex:sales-bot}" },
          next: "bye",
        }),
        new DisconnectParticipant({ id: "bye" }),
      ),
      { includeMeta: false },
    );
    const out = codegen(doc);
    expect(out).toContain('LexV2Bot: "${cdref:lex:sales-bot}"');
    expect(out).not.toContain("Refs.lex");
  });
});

// invertAction does not trust an inverter: it constructs the block the inverter
// proposes and compares its toAction() against the source Action, falling back
// to GenericBlock on any difference. Every other fallback in this file is
// caught earlier, by an inverter's own guards, so the comparison itself was
// removable (replace it with a bare `candidate !== undefined`) with the whole
// suite green. These are the cases that reach it.
describe("codegen verifies an inversion instead of trusting it", () => {
  // Transitions.Conditions is optional in the Flow language and Connect's own
  // exports omit it when empty. wiredTransitions() accepts that (it only
  // requires no conditions), so the inverter hands back a MessageParticipant
  // candidate, but the class writes `Conditions: []` unconditionally. Only
  // re-synthesizing the candidate notices.
  const omittedConditions = (): FlowDoc =>
    docWith([
      {
        Identifier: "welcome",
        Type: "MessageParticipant",
        Parameters: { Text: "Thanks for calling." },
        Transitions: {
          NextAction: "bye",
          Errors: [{ ErrorType: "NoMatchingError", NextAction: "bye" }],
        },
      },
      { Identifier: "bye", Type: "DisconnectParticipant", Parameters: {}, Transitions: {} },
    ]);

  it("emits GenericBlock for a modeled Type whose block class would rewrite it", () => {
    const out = codegen(omittedConditions());
    expect(out).toContain('type: "MessageParticipant"');
    expect(out).not.toContain("new MessageParticipant(");
  });

  it("is exactly the divergence the comparison catches", () => {
    // Stated concretely so the next person to change wire() sees what this
    // fallback was protecting: the class adds a key the Action does not have.
    const action = omittedConditions().content.Actions[0]!;
    expect(action.Transitions).not.toHaveProperty("Conditions");
    const rebuilt = new MessageParticipant({
      id: "welcome",
      text: "Thanks for calling.",
      next: "bye",
      onError: "bye",
    }).toAction();
    expect(rebuilt.Transitions).toHaveProperty("Conditions");
  });

  it("emits GenericBlock when an error branch carries a field the class drops", () => {
    const doc = docWith([
      {
        Identifier: "welcome",
        Type: "MessageParticipant",
        Parameters: { Text: "Thanks for calling." },
        Transitions: {
          NextAction: "bye",
          // A future Flow language field, or one this library does not model
          // yet. The inverter reads ErrorType and NextAction only.
          Errors: [{ ErrorType: "NoMatchingError", NextAction: "bye", Unmodeled: "keep" } as never],
          Conditions: [],
        },
      },
      { Identifier: "bye", Type: "DisconnectParticipant", Parameters: {}, Transitions: {} },
    ]);
    const out = codegen(doc);
    expect(out).toContain('type: "MessageParticipant"');
    expect(out).not.toContain("new MessageParticipant(");
  });

  it("still emits the modeled block when the inversion does reproduce the Action", () => {
    const doc = docWith([
      {
        Identifier: "welcome",
        Type: "MessageParticipant",
        Parameters: { Text: "Thanks for calling." },
        Transitions: {
          NextAction: "bye",
          Errors: [{ ErrorType: "NoMatchingError", NextAction: "bye" }],
          Conditions: [],
        },
      },
      { Identifier: "bye", Type: "DisconnectParticipant", Parameters: {}, Transitions: {} },
    ]);
    const out = codegen(doc);
    expect(out).toContain("new MessageParticipant(");
    expect(out).not.toContain('type: "MessageParticipant"');
  });
});

describe("GetParticipantInput inverts only the shape the class emits", () => {
  /** The exact Action the class writes for a two-key menu. */
  const menuAction = (): FlowAction => ({
    Identifier: "menu",
    Type: "GetParticipantInput",
    Parameters: { Text: "Press 1 or 2.", InputTimeLimitSeconds: "5", StoreInput: "False" },
    Transitions: {
      NextAction: "again",
      Errors: [
        { ErrorType: "InputTimeLimitExceeded", NextAction: "again" },
        { ErrorType: "NoMatchingCondition", NextAction: "again" },
        { ErrorType: "NoMatchingError", NextAction: "bye" },
      ],
      Conditions: [
        { NextAction: "bye", Condition: { Operator: "Equals", Operands: ["1"] } },
        { NextAction: "again", Condition: { Operator: "Equals", Operands: ["2"] } },
      ],
    },
  });
  const rest = (): FlowAction[] => [
    {
      Identifier: "again",
      Type: "MessageParticipant",
      Parameters: { Text: "Sorry." },
      Transitions: {
        NextAction: "menu",
        Errors: [{ ErrorType: "NoMatchingError", NextAction: "bye" }],
        Conditions: [],
      },
    },
    { Identifier: "bye", Type: "DisconnectParticipant", Parameters: {}, Transitions: {} },
  ];
  const withMenu = (edit: (a: FlowAction) => void): FlowDoc => {
    const a = menuAction();
    edit(a);
    return docWith([a, ...rest()]);
  };
  const generic = (doc: FlowDoc) => {
    const out = codegen(doc);
    expect(out).toContain('type: "GetParticipantInput"');
    expect(out).not.toContain("new GetParticipantInput(");
    return out;
  };

  it("emits the class for the exact shape, and the class re-emits the Action", () => {
    const out = codegen(docWith([menuAction(), ...rest()]));
    expect(out).toContain(
      [
        "    new GetParticipantInput({",
        '      id: "menu",',
        '      text: "Press 1 or 2.",',
        "      timeoutSeconds: 5,",
        "      branches: [",
        '        { digit: "1", target: "bye" },',
        '        { digit: "2", target: "again" },',
        "      ],",
        '      onTimeout: "again",',
        '      onNoMatch: "again",',
        '      onError: "bye",',
        "    }),",
      ].join("\n"),
    );
    // The other direction: the block that source constructs synthesizes to
    // the same Action the doc held.
    const block = new GetParticipantInput({
      id: "menu",
      text: "Press 1 or 2.",
      timeoutSeconds: 5,
      branches: [
        { digit: "1", target: "bye" },
        { digit: "2", target: "again" },
      ],
      onTimeout: "again",
      onNoMatch: "again",
      onError: "bye",
    });
    expect(block.toAction()).toEqual(menuAction());
  });

  it("turns a PromptId token into Refs.prompt and a JSONPath into jsonPath()", () => {
    const token = codegen(
      withMenu((a) => {
        a.Parameters = { ...a.Parameters, PromptId: Refs.prompt("menu-prompt") };
        delete a.Parameters.Text;
      }),
    );
    expect(token).toContain('prompt: Refs.prompt("menu-prompt")');
    expect(token).toContain("new GetParticipantInput(");
    expect(token).toContain("Refs,");
    const path = codegen(
      withMenu((a) => {
        a.Parameters = { ...a.Parameters, PromptId: "$.Attributes.menuPrompt" };
        delete a.Parameters.Text;
      }),
    );
    expect(path).toContain('prompt: jsonPath("$.Attributes.menuPrompt")');
    expect(path).toContain("new GetParticipantInput(");
  });

  it("inverts a menu with SSML, and one with no prompt at all", () => {
    const ssml = codegen(
      withMenu((a) => {
        a.Parameters = { ...a.Parameters, SSML: "<speak>Press 1.</speak>" };
        delete a.Parameters.Text;
      }),
    );
    expect(ssml).toContain('ssml: "<speak>Press 1.</speak>"');
    expect(ssml).toContain("new GetParticipantInput(");
    const silent = codegen(
      withMenu((a) => {
        delete a.Parameters.Text;
      }),
    );
    expect(silent).toContain("new GetParticipantInput(");
    expect(silent).toContain('      id: "menu",\n      timeoutSeconds: 5,');
  });

  it("round-trips the synthesized shape byte-stably", () => {
    const flow = new Flow({ name: "menu" }).add(
      new GetParticipantInput({
        id: "menu",
        text: "Press 1 or 2.",
        timeoutSeconds: 5,
        branches: [
          { digit: "1", target: "bye" },
          { digit: "2", target: "again" },
        ],
        onTimeout: "again",
        onNoMatch: "again",
        onError: "bye",
      }),
      new MessageParticipant({ id: "again", text: "Sorry.", next: "menu", onError: "bye" }),
      new DisconnectParticipant({ id: "bye" }),
    );
    const doc = synth(flow, { includeMeta: false });
    expect(canonicalize(doc).content.Actions[0]).toEqual(
      canonicalize(docWith([menuAction()])).content.Actions[0],
    );
    const first = codegen(doc);
    expect(codegen(doc)).toBe(first);
    expect(first).toContain("new GetParticipantInput(");
  });

  it("falls back for the stored-input form, which the class never emits", () => {
    generic(
      withMenu((a) => {
        a.Parameters = {
          ...a.Parameters,
          StoreInput: "True",
          InputValidation: { CustomValidation: { MaximumLength: "4" } },
        };
        a.Transitions.Conditions = [];
      }),
    );
    generic(
      withMenu((a) => {
        a.Parameters = { ...a.Parameters, StoreInput: "True" };
      }),
    );
    generic(
      withMenu((a) => {
        delete a.Parameters.StoreInput;
      }),
    );
  });

  it("falls back when the timeout is not the plain decimal string the class writes", () => {
    for (const timeout of [5, "05", "5.0", " 5", "", "0", "181", "abc"]) {
      generic(
        withMenu((a) => {
          a.Parameters = { ...a.Parameters, InputTimeLimitSeconds: timeout };
        }),
      );
    }
    generic(
      withMenu((a) => {
        delete a.Parameters.InputTimeLimitSeconds;
      }),
    );
  });

  it("falls back when the prompt is doubled, mistyped, or a parameter is unmodeled", () => {
    generic(
      withMenu((a) => {
        a.Parameters = { ...a.Parameters, PromptId: Refs.prompt("p") };
      }),
    );
    generic(
      withMenu((a) => {
        a.Parameters = { ...a.Parameters, PromptId: Refs.queue("q") };
        delete a.Parameters.Text;
      }),
    );
    generic(
      withMenu((a) => {
        a.Parameters = { ...a.Parameters, Text: 5 };
      }),
    );
    generic(
      withMenu((a) => {
        a.Parameters = {
          ...a.Parameters,
          DTMFConfiguration: { InputTerminationSequence: "#" },
        };
      }),
    );
    generic(
      withMenu((a) => {
        a.Parameters = {
          ...a.Parameters,
          Media: { Uri: "x", SourceType: "S3", MediaType: "Audio" },
        };
      }),
    );
  });

  it("falls back when a condition is not a single-key Equals", () => {
    const setCondition = (c: { Operator: string; Operands: string[] }) =>
      withMenu((a) => {
        a.Transitions.Conditions![0]!.Condition = c as never;
      });
    generic(setCondition({ Operator: "TextStartsWith", Operands: ["1"] }));
    generic(setCondition({ Operator: "Equals", Operands: ["10"] }));
    generic(setCondition({ Operator: "Equals", Operands: ["a"] }));
    generic(setCondition({ Operator: "Equals", Operands: [""] }));
    generic(setCondition({ Operator: "Equals", Operands: ["1", "2"] }));
    generic(setCondition({ Operator: "Equals", Operands: [] }));
    generic(
      withMenu((a) => {
        delete a.Transitions.Conditions;
      }),
    );
  });

  it("falls back when a key branches twice, which the class refuses", () => {
    // The shape is otherwise exact, so this fallback rides on the constructor
    // check alone: codegen builds the real block to verify an inversion, and
    // the throw sends the action to GenericBlock. The conformance fixture
    // pins the same shape for the other implementations.
    generic(
      withMenu((a) => {
        a.Transitions.Conditions![1]!.Condition.Operands = ["1"];
      }),
    );
    const fixture = JSON.parse(
      readFileSync(
        new URL("../../../conformance/roundtrip/repeated-key/doc.flowdoc.json", import.meta.url),
        "utf8",
      ),
    ) as FlowDoc;
    generic(fixture);
  });

  it("falls back when the error set or its order differs from the class's", () => {
    generic(
      withMenu((a) => {
        a.Transitions.Errors = [
          a.Transitions.Errors![1]!,
          a.Transitions.Errors![0]!,
          a.Transitions.Errors![2]!,
        ];
      }),
    );
    generic(
      withMenu((a) => {
        a.Transitions.Errors = a.Transitions.Errors!.filter(
          (e) => e.ErrorType !== "InputTimeLimitExceeded",
        );
      }),
    );
    generic(
      withMenu((a) => {
        a.Transitions.Errors = a.Transitions.Errors!.filter(
          (e) => e.ErrorType !== "NoMatchingCondition",
        );
      }),
    );
    generic(
      withMenu((a) => {
        a.Transitions.Errors = a.Transitions.Errors!.filter(
          (e) => e.ErrorType !== "NoMatchingError",
        );
      }),
    );
    generic(
      withMenu((a) => {
        a.Transitions.Errors!.push({ ErrorType: "InvalidPhoneNumber", NextAction: "bye" });
      }),
    );
  });

  it("falls back on a field the inverter never reads, by re-synthesizing the candidate", () => {
    // isCondition checks the fields the class uses and nothing else, so only
    // verify-by-construction notices a condition entry carrying more.
    generic(
      withMenu((a) => {
        a.Transitions.Conditions![0] = {
          ...a.Transitions.Conditions![0]!,
          Unmodeled: "keep",
        } as never;
      }),
    );
    generic(
      withMenu((a) => {
        a.Transitions.Errors![0] = { ...a.Transitions.Errors![0]!, Unmodeled: "keep" } as never;
      }),
    );
  });

  it("falls back when NextAction does not mirror the NoMatchingCondition target", () => {
    generic(
      withMenu((a) => {
        a.Transitions.NextAction = "bye";
      }),
    );
    generic(
      withMenu((a) => {
        delete a.Transitions.NextAction;
      }),
    );
  });

  it("keeps a menu that predates the class generic: numeric timeout, two errors, no StoreInput", () => {
    generic(
      withMenu((a) => {
        a.Parameters = { InputTimeLimitSeconds: 5, Text: "Press 1 for sales or 2 for support." };
        a.Transitions.Errors = [
          { ErrorType: "NoMatchingError", NextAction: "bye" },
          { ErrorType: "InputTimeLimitExceeded", NextAction: "bye" },
        ];
        a.Transitions.NextAction = "bye";
      }),
    );
  });
});

describe("DequeueContactAndTransferToQueue inverts the three targets the class writes", () => {
  const action = (parameters: Record<string, unknown>): FlowAction => ({
    Identifier: "requeue",
    Type: "DequeueContactAndTransferToQueue",
    Parameters: parameters,
    Transitions: {
      NextAction: "bye",
      Errors: [
        { ErrorType: "QueueAtCapacity", NextAction: "bye" },
        { ErrorType: "NoMatchingError", NextAction: "bye" },
      ],
      Conditions: [],
    },
  });
  const bye: FlowAction = {
    Identifier: "bye",
    Type: "DisconnectParticipant",
    Parameters: {},
    Transitions: {},
  };
  const typed = (parameters: Record<string, unknown>) => {
    const doc = docWith([action(parameters), bye]);
    const out = codegen(doc);
    expect(out).toContain("new DequeueContactAndTransferToQueue({");
    expect(out).not.toContain('type: "DequeueContactAndTransferToQueue"');
    return out;
  };
  const generic = (edit: (a: FlowAction) => void) => {
    const a = action({ QueueId: "${cdref:queue:priority}" });
    edit(a);
    const out = codegen(docWith([a, bye]));
    expect(out).toContain('type: "DequeueContactAndTransferToQueue"');
    expect(out).not.toContain("new DequeueContactAndTransferToQueue(");
  };

  it("emits queue, agent, or no target at all", () => {
    expect(typed({ QueueId: "${cdref:queue:priority}" })).toContain(
      'queue: Refs.queue("priority")',
    );
    expect(typed({ AgentId: "$.Attributes.agentArn" })).toContain(
      'agent: jsonPath("$.Attributes.agentArn")',
    );
    const bare = typed({});
    expect(bare).not.toContain("queue:");
    expect(bare).not.toContain("agent:");
    expect(bare).toContain('onQueueAtCapacity: "bye"');
  });

  it("falls back when both targets are set, a token is the wrong type, or an error is missing", () => {
    generic((a) => {
      a.Parameters.AgentId = "${cdref:queue:overflow}";
    });
    generic((a) => {
      a.Parameters.QueueId = "${cdref:flow:not-a-queue}";
    });
    generic((a) => {
      a.Transitions.Errors = [{ ErrorType: "NoMatchingError", NextAction: "bye" }];
    });
  });
});

describe("TransferContactToAgent is terminal", () => {
  const transfer = (): FlowAction => ({
    Identifier: "hand-off",
    Type: "TransferContactToAgent",
    Parameters: {},
    Transitions: {},
  });

  it("inverts the bare terminal shape", () => {
    expect(codegen(docWith([transfer()]))).toContain(
      'new TransferContactToAgent({ id: "hand-off" })',
    );
  });

  it("falls back when the action carries a transition or a parameter", () => {
    const wired = transfer();
    wired.Transitions = { NextAction: "hand-off", Errors: [], Conditions: [] };
    expect(codegen(docWith([wired]))).toContain('type: "TransferContactToAgent"');
    const withParam = transfer();
    withParam.Parameters = { AgentId: "${cdref:queue:front-desk}" };
    expect(codegen(docWith([withParam]))).toContain('type: "TransferContactToAgent"');
  });
});

describe("UpdateContactRoutingBehavior inverts one adjustment and no error branch", () => {
  const action = (parameters: Record<string, unknown>): FlowAction => ({
    Identifier: "bump",
    Type: "UpdateContactRoutingBehavior",
    Parameters: parameters,
    Transitions: { NextAction: "bye", Errors: [], Conditions: [] },
  });
  const bye: FlowAction = {
    Identifier: "bye",
    Type: "DisconnectParticipant",
    Parameters: {},
    Transitions: {},
  };
  const typed = (parameters: Record<string, unknown>) => {
    const out = codegen(docWith([action(parameters), bye]));
    expect(out).toContain("new UpdateContactRoutingBehavior({");
    expect(out).not.toContain('type: "UpdateContactRoutingBehavior"');
    return out;
  };
  const generic = (a: FlowAction) => {
    const out = codegen(docWith([a, bye]));
    expect(out).toContain('type: "UpdateContactRoutingBehavior"');
    expect(out).not.toContain("new UpdateContactRoutingBehavior(");
  };

  it("reads the console's decimal strings back as numbers", () => {
    expect(typed({ QueuePriority: "1" })).toContain("queuePriority: 1");
    expect(typed({ QueueTimeAdjustmentSeconds: "-30" })).toContain(
      "queueTimeAdjustmentSeconds: -30",
    );
    expect(typed({ QueueTimeAdjustmentSeconds: "0" })).toContain("queueTimeAdjustmentSeconds: 0");
  });

  it("falls back on both, on neither, on a JSON number, a leading zero, a fraction, a priority of 0, or an error branch", () => {
    generic(action({ QueuePriority: "1", QueueTimeAdjustmentSeconds: "30" }));
    generic(action({}));
    generic(action({ QueuePriority: 1 }));
    generic(action({ QueuePriority: "05" }));
    generic(action({ QueuePriority: "1.0" }));
    generic(action({ QueuePriority: "0" }));
    const withError = action({ QueuePriority: "1" });
    withError.Transitions.Errors = [{ ErrorType: "NoMatchingError", NextAction: "bye" }];
    generic(withError);
  });
});

describe("CreateCallbackContact inverts the full and the minimal shape", () => {
  const action = (parameters: Record<string, unknown>): FlowAction => ({
    Identifier: "callback",
    Type: "CreateCallbackContact",
    Parameters: parameters,
    Transitions: {
      NextAction: "bye",
      Errors: [{ ErrorType: "NoMatchingError", NextAction: "bye" }],
      Conditions: [],
    },
  });
  const bye: FlowAction = {
    Identifier: "bye",
    Type: "DisconnectParticipant",
    Parameters: {},
    Transitions: {},
  };
  // The console's spelling, from its export of the Sample interruptible
  // queue flow with callback.
  const minimal = {
    InitialCallDelaySeconds: "60",
    MaximumConnectionAttempts: "2",
    RetryDelaySeconds: "600",
  };
  const typed = (parameters: Record<string, unknown>) => {
    const out = codegen(docWith([action(parameters), bye]));
    expect(out).toContain("new CreateCallbackContact({");
    expect(out).not.toContain('type: "CreateCallbackContact"');
    return out;
  };
  const generic = (parameters: Record<string, unknown>) => {
    const out = codegen(docWith([action(parameters), bye]));
    expect(out).toContain('type: "CreateCallbackContact"');
    expect(out).not.toContain("new CreateCallbackContact(");
  };

  it("emits every optional field it finds, and only those", () => {
    const full = typed({
      ...minimal,
      QueueId: "${cdref:queue:callbacks}",
      ContactFlowId: "${cdref:flow:callback-greeting}",
      CallerId: "$.SystemEndpoint.Address",
    });
    expect(full).toContain('queue: Refs.queue("callbacks")');
    expect(full).toContain('flow: Refs.flow("callback-greeting")');
    expect(full).toContain('callerId: "$.SystemEndpoint.Address"');
    expect(full).toContain("initialCallDelaySeconds: 60");
    const bare = typed(minimal);
    expect(bare).not.toContain("queue:");
    expect(bare).not.toContain("flow:");
    expect(bare).not.toContain("callerId:");
    expect(typed({ ...minimal, AgentId: "$.Attributes.agentArn" })).toContain(
      'agent: jsonPath("$.Attributes.agentArn")',
    );
  });

  it("falls back on both targets, a missing or out-of-range delay, a JSON number, a leading zero, or a wrong token", () => {
    generic({ ...minimal, QueueId: "${cdref:queue:a}", AgentId: "${cdref:queue:b}" });
    generic({ MaximumConnectionAttempts: "2", RetryDelaySeconds: "600" });
    generic({ ...minimal, InitialCallDelaySeconds: "259201" });
    generic({ ...minimal, MaximumConnectionAttempts: 2 });
    generic({ ...minimal, RetryDelaySeconds: "0600" });
    generic({ ...minimal, ContactFlowId: "${cdref:module:not-a-flow@prod}" });
  });
});

describe("UpdateContactCallbackNumber inverts a JSONPath number with its two named errors", () => {
  const action = (): FlowAction => ({
    Identifier: "set-number",
    Type: "UpdateContactCallbackNumber",
    Parameters: { CallbackNumber: "$.StoredCustomerInput" },
    Transitions: {
      NextAction: "bye",
      Errors: [
        { ErrorType: "InvalidCallbackNumber", NextAction: "bye" },
        { ErrorType: "CallbackNumberNotDialable", NextAction: "bye" },
      ],
      Conditions: [],
    },
  });
  const bye: FlowAction = {
    Identifier: "bye",
    Type: "DisconnectParticipant",
    Parameters: {},
    Transitions: {},
  };
  const generic = (edit: (a: FlowAction) => void) => {
    const a = action();
    edit(a);
    const out = codegen(docWith([a, bye]));
    expect(out).toContain('type: "UpdateContactCallbackNumber"');
    expect(out).not.toContain("new UpdateContactCallbackNumber(");
  };

  it("emits the class with jsonPath() and imports it", () => {
    const out = codegen(docWith([action(), bye]));
    expect(out).toContain('callbackNumber: jsonPath("$.StoredCustomerInput")');
    expect(out).toContain('onInvalidNumber: "bye"');
    expect(out).toContain('onNotDialable: "bye"');
    expect(out).toMatch(/import \{[^}]*jsonPath[^}]*\} from/);
  });

  it("falls back on a static number, a swapped or missing error, a catch-all, or an extra parameter", () => {
    generic((a) => {
      a.Parameters.CallbackNumber = "+15555550100";
    });
    generic((a) => {
      a.Transitions.Errors = [a.Transitions.Errors![1]!, a.Transitions.Errors![0]!];
    });
    generic((a) => {
      a.Transitions.Errors = [a.Transitions.Errors![0]!];
    });
    generic((a) => {
      a.Transitions.Errors!.push({ ErrorType: "NoMatchingError", NextAction: "bye" });
    });
    generic((a) => {
      a.Parameters.Routing = { Depth: 2 };
    });
  });
});

describe("Loop inverts the two fixed conditions with NextAction mirroring the done path", () => {
  const loop = (count: unknown): FlowAction => ({
    Identifier: "again",
    Type: "Loop",
    Parameters: { LoopCount: count },
    Transitions: {
      NextAction: "bye",
      Errors: [],
      Conditions: [
        { NextAction: "again", Condition: { Operator: "Equals", Operands: ["ContinueLooping"] } },
        { NextAction: "bye", Condition: { Operator: "Equals", Operands: ["DoneLooping"] } },
      ],
    },
  });
  const bye: FlowAction = {
    Identifier: "bye",
    Type: "DisconnectParticipant",
    Parameters: {},
    Transitions: {},
  };
  const generic = (edit: (a: FlowAction) => void, count: unknown = 2) => {
    const a = loop(count);
    edit(a);
    const out = codegen(docWith([a, bye]));
    expect(out).toContain('type: "Loop"');
    expect(out).not.toContain("new Loop(");
  };

  it("emits a static count as a number and a dynamic one as jsonPath()", () => {
    const out = codegen(docWith([loop(2), bye]));
    expect(out).toContain("new Loop({");
    expect(out).toContain("count: 2");
    expect(out).toContain('onContinue: "again"');
    expect(out).toContain('onDone: "bye"');
    const dynamic = codegen(docWith([loop("$.Attributes.retries"), bye]));
    expect(dynamic).toContain('count: jsonPath("$.Attributes.retries")');
    expect(dynamic).toMatch(/import \{[^}]*jsonPath[^}]*\} from/);
  });

  it("falls back on a count out of range or spelled as a string, an error branch, swapped conditions, or an unmirrored NextAction", () => {
    generic(() => {}, 101);
    generic(() => {}, "2");
    generic((a) => {
      a.Transitions.Errors = [{ ErrorType: "NoMatchingError", NextAction: "bye" }];
    });
    generic((a) => {
      a.Transitions.Conditions = [a.Transitions.Conditions![1]!, a.Transitions.Conditions![0]!];
    });
    generic((a) => {
      a.Transitions.NextAction = "again";
    });
  });
});

describe("Wait inverts the timeout, its events, and the conditional ParticipantNotFound", () => {
  const wait = (events: string[], withBotError: boolean): FlowAction => ({
    Identifier: "hold",
    Type: "Wait",
    Parameters: { TimeLimitSeconds: "300", ...(events.length > 0 ? { Events: events } : {}) },
    Transitions: {
      NextAction: "bye",
      Errors: [
        { ErrorType: "NoMatchingError", NextAction: "bye" },
        ...(withBotError ? [{ ErrorType: "ParticipantNotFound", NextAction: "bye" }] : []),
      ],
      Conditions: [
        { NextAction: "bye", Condition: { Operator: "Equals", Operands: ["WaitCompleted"] } },
        ...events.map((e) => ({
          NextAction: "hold",
          Condition: { Operator: "Equals", Operands: [e] },
        })),
      ],
    },
  });
  const bye: FlowAction = {
    Identifier: "bye",
    Type: "DisconnectParticipant",
    Parameters: {},
    Transitions: {},
  };
  const typed = (a: FlowAction) => {
    const out = codegen(docWith([a, bye]));
    expect(out).toContain("new Wait({");
    expect(out).not.toContain('type: "Wait"');
    return out;
  };
  const generic = (a: FlowAction) => {
    const out = codegen(docWith([a, bye]));
    expect(out).toContain('type: "Wait"');
    expect(out).not.toContain("new Wait(");
  };

  it("emits the plain timeout, one event, and both events with the bot error", () => {
    const plain = typed(wait([], false));
    expect(plain).toContain("timeoutSeconds: 300");
    expect(plain).not.toContain("onEvent");
    expect(plain).not.toContain("onParticipantNotFound");
    expect(typed(wait(["CustomerReturned"], false))).toContain(
      'onEvent: { CustomerReturned: "hold" }',
    );
    const both = typed(wait(["CustomerReturned", "BotParticipantDisconnected"], true));
    expect(both).toContain('BotParticipantDisconnected: "hold"');
    expect(both).toContain('onParticipantNotFound: "bye"');
    const dynamic = wait([], false);
    dynamic.Parameters.TimeLimitSeconds = "$.Attributes.holdSeconds";
    expect(typed(dynamic)).toContain('timeoutSeconds: jsonPath("$.Attributes.holdSeconds")');
  });

  it("falls back when events and conditions disagree, the bot error is unpaired, the order is swapped, or the timeout is out of range", () => {
    generic(wait(["BotParticipantDisconnected"], false));
    generic(wait(["CustomerReturned"], true));
    const listedOnly = wait([], false);
    listedOnly.Parameters.Events = ["CustomerReturned"];
    generic(listedOnly);
    const swapped = wait(["CustomerReturned", "BotParticipantDisconnected"], true);
    swapped.Parameters.Events = ["BotParticipantDisconnected", "CustomerReturned"];
    swapped.Transitions.Conditions = [
      swapped.Transitions.Conditions![0]!,
      swapped.Transitions.Conditions![2]!,
      swapped.Transitions.Conditions![1]!,
    ];
    generic(swapped);
    const tooLong = wait([], false);
    tooLong.Parameters.TimeLimitSeconds = "604801";
    generic(tooLong);
    const asNumber = wait([], false);
    asNumber.Parameters.TimeLimitSeconds = 300;
    generic(asNumber);
    const pageKey = wait([], false);
    delete pageKey.Parameters.TimeLimitSeconds;
    pageKey.Parameters.TimeoutSeconds = "300";
    generic(pageKey);
    const unmirrored = wait([], false);
    unmirrored.Transitions.NextAction = "hold";
    generic(unmirrored);
  });
});

describe("DistributeByPercentage inverts the console's threshold chain into percentages", () => {
  const split = (operands: string[]): FlowAction => ({
    Identifier: "split",
    Type: "DistributeByPercentage",
    Parameters: {},
    Transitions: {
      NextAction: "bye",
      Errors: [{ ErrorType: "NoMatchingCondition", NextAction: "bye" }],
      Conditions: operands.map((o) => ({
        NextAction: "bye",
        Condition: { Operator: "NumberLessThan", Operands: [o] },
      })),
    },
  });
  const bye: FlowAction = {
    Identifier: "bye",
    Type: "DisconnectParticipant",
    Parameters: {},
    Transitions: {},
  };
  const generic = (a: FlowAction) => {
    const out = codegen(docWith([a, bye]));
    expect(out).toContain('type: "DistributeByPercentage"');
    expect(out).not.toContain("new DistributeByPercentage(");
  };

  it("reads the Sample AB test thresholds 4, 10, 18 as 3%, 6%, 8%", () => {
    const out = codegen(docWith([split(["4", "10", "18"]), bye]));
    expect(out).toContain("new DistributeByPercentage({");
    expect(out).toContain('{ percent: 3, target: "bye" }');
    expect(out).toContain('{ percent: 6, target: "bye" }');
    expect(out).toContain('{ percent: 8, target: "bye" }');
    expect(out).toContain('onRemainder: "bye"');
    expect(codegen(docWith([split(["100"]), bye]))).toContain("percent: 99");
  });

  it("falls back on a threshold above 100, a non-increasing chain, a non-integer, another operator, an unmirrored NextAction, or a parameter", () => {
    generic(split(["101"]));
    generic(split(["10", "10"]));
    generic(split(["1"]));
    generic(split(["4.5"]));
    const other = split(["4"]);
    other.Transitions.Conditions![0]!.Condition.Operator = "NumberGreaterThan";
    generic(other);
    const unmirrored = split(["4"]);
    unmirrored.Transitions.NextAction = "split";
    generic(unmirrored);
    const withParam = split(["4"]);
    withParam.Parameters = { Seed: 1 };
    generic(withParam);
  });
});

describe("UpdateFlowAttributes inverts an opaque attributes object with no error branch", () => {
  const action = (attributes: unknown): FlowAction => ({
    Identifier: "remember",
    Type: "UpdateFlowAttributes",
    Parameters: { FlowAttributes: attributes },
    Transitions: { NextAction: "bye", Errors: [], Conditions: [] },
  });
  const bye: FlowAction = {
    Identifier: "bye",
    Type: "DisconnectParticipant",
    Parameters: {},
    Transitions: {},
  };
  const generic = (a: FlowAction) => {
    const out = codegen(docWith([a, bye]));
    expect(out).toContain('type: "UpdateFlowAttributes"');
    expect(out).not.toContain("new UpdateFlowAttributes(");
  };

  it("emits the object verbatim, nested values included", () => {
    const out = codegen(docWith([action({ retries: "2", nested: { Value: "x" } }), bye]));
    expect(out).toContain("new UpdateFlowAttributes({");
    expect(out).toContain('retries: "2"');
    expect(out).toContain('nested: { Value: "x" }');
    expect(codegen(docWith([action({}), bye]))).toContain("attributes: {}");
  });

  it("falls back on a non-object, a missing key, or an error branch", () => {
    generic(action("retries=2"));
    generic(action(["a"]));
    const missing = action({});
    missing.Parameters = {};
    generic(missing);
    const withError = action({});
    withError.Transitions.Errors = [{ ErrorType: "NoMatchingError", NextAction: "bye" }];
    generic(withError);
  });
});

describe("CheckMetricData inverts the console's staffing check and a queue-depth chain", () => {
  const check = (
    parameters: Record<string, unknown>,
    conditions: { operator: string; operand: string }[],
  ): FlowAction => ({
    Identifier: "staffed",
    Type: "CheckMetricData",
    Parameters: parameters,
    Transitions: {
      NextAction: "bye",
      Errors: [
        { ErrorType: "NoMatchingError", NextAction: "bye" },
        { ErrorType: "NoMatchingCondition", NextAction: "again" },
      ],
      Conditions: conditions.map((c) => ({
        NextAction: "again",
        Condition: { Operator: c.operator as "Equals", Operands: [c.operand] },
      })),
    },
  });
  const rest: FlowAction[] = [
    {
      Identifier: "again",
      Type: "MessageParticipant",
      Parameters: { Text: "Again." },
      Transitions: {
        NextAction: "bye",
        Errors: [{ ErrorType: "NoMatchingError", NextAction: "bye" }],
        Conditions: [],
      },
    },
    { Identifier: "bye", Type: "DisconnectParticipant", Parameters: {}, Transitions: {} },
  ];
  const typed = (a: FlowAction) => {
    const out = codegen(docWith([a, ...rest]));
    expect(out).toContain("new CheckMetricData({");
    expect(out).not.toContain('type: "CheckMetricData"');
    return out;
  };
  const generic = (a: FlowAction) => {
    const out = codegen(docWith([a, ...rest]));
    expect(out).toContain('type: "CheckMetricData"');
    expect(out).not.toContain("new CheckMetricData(");
  };
  const staffed = { operator: "NumberGreaterThan", operand: "0" };

  it("emits the default queue transfer's staffing check as recorded from the console", () => {
    const out = typed(check({ MetricType: "NumberOfAgentsStaffed" }, [staffed]));
    expect(out).toContain('metric: "NumberOfAgentsStaffed"');
    expect(out).toContain('{ operator: "NumberGreaterThan", operand: "0", target: "again" }');
    expect(out).toContain('onNoMatch: "again"');
    expect(out).toContain('onError: "bye"');
    expect(out).not.toContain("queue:");
  });

  it("emits a queue metric with a token or JSONPath target and several comparisons", () => {
    const depth = check(
      { MetricType: "NumberOfContactsInQueue", QueueId: "${cdref:queue:front-desk}" },
      [
        { operator: "NumberLessThan", operand: "5" },
        { operator: "NumberGreaterOrEqualTo", operand: "5" },
      ],
    );
    const out = typed(depth);
    expect(out).toContain('queue: Refs.queue("front-desk")');
    expect(out).toContain('{ operator: "NumberLessThan", operand: "5", target: "again" }');
    expect(
      typed(
        check({ MetricType: "OldestContactInQueueAgeSeconds", AgentId: "$.Attributes.agentArn" }, [
          { operator: "Equals", operand: "0" },
        ]),
      ),
    ).toContain('agent: jsonPath("$.Attributes.agentArn")');
  });

  it("falls back on an agent metric with any other comparison, an unknown metric, both targets, a missing branch, or an unmirrored NextAction", () => {
    generic(
      check({ MetricType: "NumberOfAgentsAvailable" }, [
        { operator: "NumberLessThan", operand: "5" },
      ]),
    );
    generic(check({ MetricType: "NumberOfAgentsOnline" }, [staffed, staffed]));
    generic(check({ MetricType: "NumberOfAgentsHappy" }, [staffed]));
    generic(
      check(
        {
          MetricType: "NumberOfAgentsStaffed",
          QueueId: "${cdref:queue:a}",
          AgentId: "${cdref:queue:b}",
        },
        [staffed],
      ),
    );
    const noMatchMissing = check({ MetricType: "NumberOfAgentsStaffed" }, [staffed]);
    noMatchMissing.Transitions.Errors = [noMatchMissing.Transitions.Errors![0]!];
    generic(noMatchMissing);
    const unmirrored = check({ MetricType: "NumberOfAgentsStaffed" }, [staffed]);
    unmirrored.Transitions.NextAction = "again";
    generic(unmirrored);
    generic(
      check({ MetricType: "NumberOfContactsInQueue" }, [
        { operator: "TextContains", operand: "5" },
      ]),
    );
  });
});

describe("GetMetricData inverts its optional queue, agent queue and channel", () => {
  const load = (parameters: Record<string, unknown>): FlowAction => ({
    Identifier: "load",
    Type: "GetMetricData",
    Parameters: parameters,
    Transitions: {
      NextAction: "bye",
      Errors: [{ ErrorType: "NoMatchingError", NextAction: "bye" }],
      Conditions: [],
    },
  });
  const bye: FlowAction = {
    Identifier: "bye",
    Type: "DisconnectParticipant",
    Parameters: {},
    Transitions: {},
  };
  const typed = (parameters: Record<string, unknown>) => {
    const out = codegen(docWith([load(parameters), bye]));
    expect(out).toContain("new GetMetricData({");
    expect(out).not.toContain('type: "GetMetricData"');
    return out;
  };
  const generic = (parameters: Record<string, unknown>) => {
    const out = codegen(docWith([load(parameters), bye]));
    expect(out).toContain('type: "GetMetricData"');
    expect(out).not.toContain("new GetMetricData(");
  };

  it("emits nothing, a queue with a static channel, or an agent queue with a dynamic one", () => {
    const bare = typed({});
    expect(bare).not.toContain("queue:");
    expect(bare).not.toContain("channel:");
    const voice = typed({ QueueId: "${cdref:queue:front-desk}", QueueChannel: "Voice" });
    expect(voice).toContain('queue: Refs.queue("front-desk")');
    expect(voice).toContain('channel: "Voice"');
    const dynamic = typed({ AgentId: "$.Attributes.agentArn", QueueChannel: "$.Channel" });
    expect(dynamic).toContain('agent: jsonPath("$.Attributes.agentArn")');
    expect(dynamic).toContain('channel: jsonPath("$.Channel")');
  });

  it("falls back on both targets, a channel the page does not list, or a wrong token", () => {
    generic({ QueueId: "${cdref:queue:a}", AgentId: "${cdref:queue:b}" });
    generic({ QueueChannel: "Email" });
    generic({ QueueId: "${cdref:hours:not-a-queue}" });
  });
});

describe("TagContact inverts a string map of up to six user-defined tags", () => {
  const tag = (tags: unknown): FlowAction => ({
    Identifier: "tag",
    Type: "TagContact",
    Parameters: { Tags: tags },
    Transitions: { NextAction: "bye", Errors: [], Conditions: [] },
  });
  const bye: FlowAction = {
    Identifier: "bye",
    Type: "DisconnectParticipant",
    Parameters: {},
    Transitions: {},
  };
  const generic = (a: FlowAction) => {
    const out = codegen(docWith([a, bye]));
    expect(out).toContain('type: "TagContact"');
    expect(out).not.toContain("new TagContact(");
  };

  it("emits the tags verbatim, dynamic values included", () => {
    const out = codegen(docWith([tag({ team: "cx", tier: "$.Attributes.tier" }), bye]));
    expect(out).toContain("new TagContact({");
    expect(out).toContain('team: "cx"');
    expect(out).toContain('tier: "$.Attributes.tier"');
  });

  it("falls back on no tags, seven tags, a system-tag key, a non-string value, or an error branch", () => {
    generic(tag({}));
    generic(tag(Object.fromEntries("abcdefg".split("").map((k) => [k, k]))));
    generic(tag({ "aws:connect:instanceId": "x" }));
    generic(tag({ count: 1 }));
    const withError = tag({ team: "cx" });
    withError.Transitions.Errors = [{ ErrorType: "NoMatchingError", NextAction: "bye" }];
    generic(withError);
  });
});

describe("UnTagContact inverts a list of user-defined tag keys", () => {
  const untag = (keys: unknown): FlowAction => ({
    Identifier: "untag",
    Type: "UnTagContact",
    Parameters: { TagKeys: keys },
    Transitions: {
      NextAction: "bye",
      Errors: [{ ErrorType: "NoMatchingError", NextAction: "bye" }],
      Conditions: [],
    },
  });
  const bye: FlowAction = {
    Identifier: "bye",
    Type: "DisconnectParticipant",
    Parameters: {},
    Transitions: {},
  };
  const generic = (a: FlowAction) => {
    const out = codegen(docWith([a, bye]));
    expect(out).toContain('type: "UnTagContact"');
    expect(out).not.toContain("new UnTagContact(");
  };

  it("emits the keys as an array", () => {
    const out = codegen(docWith([untag(["tier", "team"]), bye]));
    expect(out).toContain("new UnTagContact({");
    expect(out).toContain('tagKeys: ["tier", "team"]');
  });

  it("falls back on no keys, a system-tag key, a non-string, or a missing catch-all", () => {
    generic(untag([]));
    generic(untag(["aws:connect:instanceId"]));
    generic(untag([1]));
    const unwired = untag(["tier"]);
    unwired.Transitions.Errors = [];
    generic(unwired);
  });
});

describe("UpdateContactTextToSpeechVoice inverts the voice with its optional engine and style", () => {
  const voice = (parameters: Record<string, unknown>): FlowAction => ({
    Identifier: "voice",
    Type: "UpdateContactTextToSpeechVoice",
    Parameters: parameters,
    Transitions: {
      NextAction: "bye",
      Errors: [{ ErrorType: "NoMatchingError", NextAction: "bye" }],
      Conditions: [],
    },
  });
  const bye: FlowAction = {
    Identifier: "bye",
    Type: "DisconnectParticipant",
    Parameters: {},
    Transitions: {},
  };
  const typed = (parameters: Record<string, unknown>) => {
    const out = codegen(docWith([voice(parameters), bye]));
    expect(out).toContain("new UpdateContactTextToSpeechVoice({");
    expect(out).not.toContain('type: "UpdateContactTextToSpeechVoice"');
    return out;
  };
  const generic = (parameters: Record<string, unknown>) => {
    const out = codegen(docWith([voice(parameters), bye]));
    expect(out).toContain('type: "UpdateContactTextToSpeechVoice"');
    expect(out).not.toContain("new UpdateContactTextToSpeechVoice(");
  };

  it("emits the voice alone, with a static engine and style, or with dynamic ones", () => {
    expect(typed({ TextToSpeechVoice: "Joanna" })).toContain('voice: "Joanna"');
    const full = typed({
      TextToSpeechVoice: "Matthew",
      TextToSpeechEngine: "neural",
      TextToSpeechStyle: "Conversational",
    });
    expect(full).toContain('engine: "neural"');
    expect(full).toContain('style: "Conversational"');
    const dynamic = typed({
      TextToSpeechVoice: "$.Attributes.voice",
      TextToSpeechEngine: "$.Attributes.engine",
    });
    expect(dynamic).toContain('voice: "$.Attributes.voice"');
    expect(dynamic).toContain('engine: jsonPath("$.Attributes.engine")');
  });

  it("falls back on an empty voice, an engine or style the pages do not list, or an extra key", () => {
    generic({ TextToSpeechVoice: "" });
    generic({ TextToSpeechVoice: "Joanna", TextToSpeechEngine: "premium" });
    generic({ TextToSpeechVoice: "Joanna", TextToSpeechStyle: "Coversational" });
    generic({ TextToSpeechVoice: "Joanna", LanguageCode: "en-US" });
  });
});

describe("UpdateContactData inverts every optional field in the page's spelling", () => {
  const data = (parameters: Record<string, unknown>): FlowAction => ({
    Identifier: "data",
    Type: "UpdateContactData",
    Parameters: { TargetContact: "Current", ...parameters },
    Transitions: {
      NextAction: "bye",
      Errors: [{ ErrorType: "NoMatchingError", NextAction: "bye" }],
      Conditions: [],
    },
  });
  const bye: FlowAction = {
    Identifier: "bye",
    Type: "DisconnectParticipant",
    Parameters: {},
    Transitions: {},
  };
  const typed = (parameters: Record<string, unknown>) => {
    const out = codegen(docWith([data(parameters), bye]));
    expect(out).toContain("new UpdateContactData({");
    expect(out).not.toContain('type: "UpdateContactData"');
    return out;
  };
  const generic = (a: FlowAction) => {
    const out = codegen(docWith([a, bye]));
    expect(out).toContain('type: "UpdateContactData"');
    expect(out).not.toContain("new UpdateContactData(");
  };

  it("keeps a Current target implicit and emits the rest as typed fields", () => {
    const bare = typed({});
    expect(bare).not.toContain("targetContact");
    const full = typed({
      Name: "$.Attributes.name",
      Description: "Priority caller",
      LanguageCode: "en-US",
      CustomerId: "c-1",
      References: { CaseId: "$.Attributes.caseId" },
      IsVoiceIdStreamingEnabled: "TRUE",
      IsVoiceAuthenticationEnabled: "TRUE",
      IsFraudDetectionEnabled: "FALSE",
      VoiceAuthenticationThreshold: "80",
      VoiceAuthenticationResponseTime: "7",
      FraudDetectionThreshold: "50",
      WatchlistId: "wl-1",
      WisdomSessionArn: "$.Wisdom.SessionArn",
      TargetContact: "Related",
    });
    expect(full).toContain('targetContact: "Related"');
    expect(full).toContain('name: "$.Attributes.name"');
    expect(full).toContain('references: { CaseId: "$.Attributes.caseId" }');
    expect(full).toContain("voiceIdStreaming: true");
    expect(full).toContain("fraudDetection: false");
    expect(full).toContain("voiceAuthenticationThreshold: 80");
    expect(full).toContain("voiceAuthenticationResponseTime: 7");
    expect(full).toContain('wisdomSessionArn: "$.Wisdom.SessionArn"');
  });

  it("falls back on a missing target, a lowercase flag, a threshold out of range or as a number, or a non-string reference", () => {
    const noTarget = data({});
    noTarget.Parameters = {};
    generic(noTarget);
    generic(data({ IsFraudDetectionEnabled: "true" }));
    generic(data({ VoiceAuthenticationThreshold: "101" }));
    generic(data({ VoiceAuthenticationResponseTime: "4" }));
    generic(data({ FraudDetectionThreshold: 50 }));
    generic(data({ References: { CaseId: 1 } }));
  });
});

describe("UpdateContactEventHooks inverts the one hook and its flow", () => {
  const hooks = (map: unknown): FlowAction => ({
    Identifier: "hook",
    Type: "UpdateContactEventHooks",
    Parameters: { EventHooks: map },
    Transitions: {
      NextAction: "bye",
      Errors: [{ ErrorType: "NoMatchingError", NextAction: "bye" }],
      Conditions: [],
    },
  });
  const bye: FlowAction = {
    Identifier: "bye",
    Type: "DisconnectParticipant",
    Parameters: {},
    Transitions: {},
  };
  const generic = (a: FlowAction) => {
    const out = codegen(docWith([a, bye]));
    expect(out).toContain('type: "UpdateContactEventHooks"');
    expect(out).not.toContain("new UpdateContactEventHooks(");
  };

  it("emits the hook name and a Refs.flow or jsonPath value", () => {
    const token = codegen(
      docWith([hooks({ CustomerQueue: "${cdref:flow:queue-experience}" }), bye]),
    );
    expect(token).toContain("new UpdateContactEventHooks({");
    expect(token).toContain('hook: "CustomerQueue"');
    expect(token).toContain('flow: Refs.flow("queue-experience")');
    const dynamic = codegen(docWith([hooks({ CustomerWhisper: "$.Attributes.whisperFlow" }), bye]));
    expect(dynamic).toContain('flow: jsonPath("$.Attributes.whisperFlow")');
  });

  it("falls back on no hook, two hooks, a hook the page does not list, or a non-flow token", () => {
    generic(hooks({}));
    generic(hooks({ CustomerQueue: "${cdref:flow:a}", CustomerHold: "${cdref:flow:b}" }));
    generic(hooks({ AgentQueue: "${cdref:flow:a}" }));
    generic(hooks({ CustomerQueue: "${cdref:module:not-a-flow@prod}" }));
  });
});

describe("MessageParticipantIteratively inverts the console's hold-loop and interrupt shapes", () => {
  const loop = (
    messages: unknown[],
    extra: { seconds?: string; interrupt?: boolean; error?: boolean } = {},
  ): FlowAction => ({
    Identifier: "hold-music",
    Type: "MessageParticipantIteratively",
    Parameters: {
      Messages: messages,
      ...(extra.seconds === undefined ? {} : { InterruptFrequencySeconds: extra.seconds }),
    },
    Transitions: {
      Errors: extra.error === true ? [{ ErrorType: "NoMatchingError", NextAction: "end" }] : [],
      Conditions:
        extra.interrupt === true
          ? [
              {
                NextAction: "end",
                Condition: { Operator: "Equals", Operands: ["MessagesInterrupted"] },
              },
            ]
          : [],
    },
  });
  const end: FlowAction = {
    Identifier: "end",
    Type: "EndFlowExecution",
    Parameters: {},
    Transitions: {},
  };
  const docOf = (a: FlowAction): FlowDoc => ({
    ...docWith([a, end]),
    connectType: "CUSTOMER_QUEUE",
  });
  const typed = (a: FlowAction) => {
    const out = codegen(docOf(a));
    expect(out).toContain("new MessageParticipantIteratively({");
    expect(out).not.toContain('type: "MessageParticipantIteratively"');
    return out;
  };
  const generic = (a: FlowAction) => {
    const out = codegen(docOf(a));
    expect(out).toContain('type: "MessageParticipantIteratively"');
    expect(out).not.toContain("new MessageParticipantIteratively(");
  };
  const media = { Media: { Uri: "s3://bucket/hold.wav", SourceType: "S3", MediaType: "Audio" } };

  it("emits the default hold flow's shape: messages, no next, no error", () => {
    const out = typed(loop([{ SSML: "<speak>You are on hold</speak>" }]));
    expect(out).toContain('{ ssml: "<speak>You are on hold</speak>" }');
    expect(out).not.toContain("onError");
    expect(out).not.toContain("onInterrupt");
  });

  it("emits every message kind, the interrupt pair, and the optional catch-all", () => {
    const out = typed(
      loop(
        [{ Text: "Thank you for holding." }, { PromptId: "${cdref:prompt:hold-music}" }, media],
        { seconds: "30", interrupt: true, error: true },
      ),
    );
    expect(out).toContain('{ text: "Thank you for holding." }');
    expect(out).toContain('{ prompt: Refs.prompt("hold-music") }');
    expect(out).toContain('{ media: { uri: "s3://bucket/hold.wav" } }');
    expect(out).toContain("interruptFrequencySeconds: 30");
    expect(out).toContain('onInterrupt: "end"');
    expect(out).toContain('onError: "end"');
  });

  it("falls back on a NextAction, an unpaired interrupt, a two-key message, a non-S3 media, or no messages", () => {
    const withNext = loop([{ Text: "hi" }]);
    withNext.Transitions.NextAction = "end";
    generic(withNext);
    generic(loop([{ Text: "hi" }], { seconds: "30" }));
    generic(loop([{ Text: "hi" }], { interrupt: true }));
    generic(loop([{ Text: "hi", SSML: "<speak>hi</speak>" }]));
    generic(loop([{ Media: { Uri: "s3://b/x", SourceType: "HTTP", MediaType: "Audio" } }]));
    generic(loop([]));
    const asNumber = loop([{ Text: "hi" }], { seconds: "30", interrupt: true });
    asNumber.Parameters.InterruptFrequencySeconds = 30;
    generic(asNumber);
  });
});

describe("ConnectParticipantWithLexBot inverts the V2 form with its intents", () => {
  const lex = (parameters: Record<string, unknown>, intents: string[] = ["Sales"]): FlowAction => ({
    Identifier: "bot",
    Type: "ConnectParticipantWithLexBot",
    Parameters: { LexV2Bot: { AliasArn: "${cdref:lex:sales-bot}" }, ...parameters },
    Transitions: {
      NextAction: "bye",
      Errors: [
        { ErrorType: "InputTimeLimitExceeded", NextAction: "bye" },
        { ErrorType: "NoMatchingError", NextAction: "bye" },
        { ErrorType: "NoMatchingCondition", NextAction: "bye" },
      ],
      Conditions: intents.map((i) => ({
        NextAction: "bye",
        Condition: { Operator: "Equals", Operands: [i] },
      })),
    },
  });
  const bye: FlowAction = {
    Identifier: "bye",
    Type: "DisconnectParticipant",
    Parameters: {},
    Transitions: {},
  };
  const typed = (a: FlowAction) => {
    const out = codegen(docWith([a, bye]));
    expect(out).toContain("new ConnectParticipantWithLexBot({");
    expect(out).not.toContain('type: "ConnectParticipantWithLexBot"');
    return out;
  };
  const generic = (a: FlowAction) => {
    const out = codegen(docWith([a, bye]));
    expect(out).toContain('type: "ConnectParticipantWithLexBot"');
    expect(out).not.toContain("new ConnectParticipantWithLexBot(");
  };

  it("emits the bot alone, and every optional field with intents", () => {
    const bare = typed(lex({}, []));
    expect(bare).toContain('bot: Refs.lex("sales-bot")');
    expect(bare).toContain("intents: []");
    const full = typed(
      lex(
        {
          Text: "How can I help?",
          LexSessionAttributes: { channel: "$.Channel" },
          LexInitializationData: { InitialMessage: "Hi" },
          LexTimeoutSeconds: { Text: "300" },
        },
        ["Sales", "Support"],
      ),
    );
    expect(full).toContain('text: "How can I help?"');
    expect(full).toContain('sessionAttributes: { channel: "$.Channel" }');
    expect(full).toContain('initialMessage: "Hi"');
    expect(full).toContain("timeoutSeconds: 300");
    expect(full).toContain('{ name: "Support", target: "bye" }');
    expect(full).toContain('onTimeout: "bye"');
    const dynamic = typed(lex({ PromptId: "${cdref:prompt:greeting}" }));
    expect(dynamic).toContain('prompt: Refs.prompt("greeting")');
    const byPath = lex({});
    byPath.Parameters.LexV2Bot = { AliasArn: "$.Attributes.botAlias" };
    expect(typed(byPath)).toContain('bot: jsonPath("$.Attributes.botAlias")');
  });

  it("falls back on the V1 form, Media, two bodies, a timeout out of range, a swapped error, or an unmirrored NextAction", () => {
    const v1 = lex({});
    v1.Parameters = { LexBot: { Name: "sales", Region: "us-east-1", Alias: "prod" } };
    generic(v1);
    generic(lex({ Media: { Uri: "s3://b/x", SourceType: "S3", MediaType: "Audio" } }));
    generic(lex({ Text: "hi", SSML: "<speak>hi</speak>" }));
    generic(lex({ LexTimeoutSeconds: { Text: "59" } }));
    generic(lex({ LexTimeoutSeconds: { Text: 300 } }));
    const swapped = lex({});
    swapped.Transitions.Errors = [
      swapped.Transitions.Errors![1]!,
      swapped.Transitions.Errors![0]!,
      swapped.Transitions.Errors![2]!,
    ];
    generic(swapped);
    const unmirrored = lex({});
    unmirrored.Transitions.NextAction = "bot";
    generic(unmirrored);
  });
});

describe("the unknown-actions fixture holds only types the builder does not model", () => {
  it("emits a GenericBlock for every action, tokens kept verbatim", () => {
    const doc = JSON.parse(
      readFileSync(
        new URL("../../../conformance/roundtrip/unknown-actions/doc.flowdoc.json", import.meta.url),
        "utf8",
      ),
    ) as FlowDoc;
    for (const a of doc.content.Actions) {
      expect(Object.values(ActionType) as string[]).not.toContain(a.Type);
    }
    const out = codegen(doc);
    expect(out.match(/new GenericBlock\(/g)).toHaveLength(doc.content.Actions.length);
    expect(out).toContain('"${cdref:flow:task-flow}"');
    expect(out).not.toContain("Refs.");
  });
});

describe("@keep comments survive regeneration", () => {
  it("re-attaches @keep comments to the matching block and the export", () => {
    const doc = demoDoc();
    const base = codegen(doc);
    const previous = base
      .replace(
        "    new CheckHoursOfOperation({",
        "    // Business hours drive everything below. @keep\n    // scratch note, not kept\n    new CheckHoursOfOperation({",
      )
      .replace(
        "export function appointmentLine",
        "// Reviewed by on-call. @keep\nexport function appointmentLine",
      );
    const regen = codegen(doc, { previous });
    expect(regen).toContain(
      "    // Business hours drive everything below. @keep\n    new CheckHoursOfOperation({",
    );
    expect(regen).toContain("// Reviewed by on-call. @keep\nexport function appointmentLine");
    expect(regen).not.toContain("scratch note");
  });

  it("is idempotent: regenerating from its own output changes nothing", () => {
    const doc = demoDoc();
    const base = codegen(doc);
    expect(codegen(doc, { previous: base })).toBe(base);
    const withKeep = codegen(doc, {
      previous: base.replace(
        '    new DisconnectParticipant({ id: "hang-up" }),',
        '    // Terminal on purpose. @keep\n    new DisconnectParticipant({ id: "hang-up" }),',
      ),
    });
    expect(codegen(doc, { previous: withKeep })).toBe(withKeep);
  });

  it("drops a @keep comment whose block id no longer exists", () => {
    const doc = demoDoc();
    const base = codegen(doc);
    const previous = base.replace(
      '    new MessageParticipant({\n      id: "welcome",',
      '    // Stale note. @keep\n    new MessageParticipant({\n      id: "gone-now",',
    );
    const regen = codegen(doc, { previous });
    expect(regen).not.toContain("Stale note");
  });
});
