/*
 * Copyright 2026 The flow-as-code Authors
 * SPDX-License-Identifier: Apache-2.0
 */
// The HCL contract's structure, ungated: every case under conformance/hcl
// points at a FlowDoc 0.2 in synth normal form, binds only keys its document
// references, and names only sub-blocks the catalog knows. The bytes of the
// goldens are held by @flow-as-code/hcl once it exists (task B03) and the fmt
// fixed point by the gated test in packages/tf; this test keeps a golden from
// drifting from the documents and the catalog in the meantime.

import { existsSync, readFileSync, readdirSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { FLOWDOC_VERSION, actionCatalog, serialize, type FlowDoc } from "./index.js";

const HCL = new URL("../../../conformance/hcl/", import.meta.url);
const read = (url: URL): string => readFileSync(url, "utf8");
const dirs = (url: URL): string[] =>
  existsSync(url)
    ? readdirSync(url, { withFileTypes: true })
        .filter((e) => e.isDirectory())
        .map((e) => e.name)
        .sort()
    : [];

interface CaseFile {
  description: string;
  doc: string;
  options?: { instanceId?: string; tags?: Record<string, string>; lintDisable?: string[] };
  validate?: string;
}

const BANNER =
  /^# Generated by @flow-as-code\/hcl from ([^\n]+)\.\n# Edits to structure regenerate; comments marked @keep survive\.\n\n/;
const LOOSE_BANNER =
  /^# Generated by @flow-as-code\/hcl from ([^\n]+)\.\n# Edits to structure regenerate; comments marked @keep survive\.\n/;
const BLOCKS = new Set(
  Object.values(actionCatalog.actions).flatMap((a) =>
    a.modeled ? [(a as { block: string }).block] : [],
  ),
);
const STRUCTURAL = new Set([
  "action",
  "generic",
  "condition",
  "error",
  "position",
  "lint",
  "lifecycle",
]);
const KEY =
  /^(queue|hours|lambda|lex|prompt|flow|module|view):[a-z0-9]+(-[a-z0-9]+)*(@[a-z0-9]+(-[a-z0-9]+)*)?$/;

/** A document's reference keys, spelled the way the resource's refs map spells them. */
function refKeys(doc: FlowDoc): string[] {
  return (doc.refs ?? []).map(
    (r) => `${r.type}:${r.name}${r.alias === undefined ? "" : `@${r.alias}`}`,
  );
}

/** The names of blocks opened inside the file: a `name {` or `name {}` line. */
function blockNames(tf: string): string[] {
  return [...tf.matchAll(/^\s+([a-z_]+) \{\}?$/gm)].map((m) => m[1]!);
}

/** A document in the repository's canonical bytes (synth normal form, sorted keys). */
function normalDoc(url: URL): FlowDoc {
  const raw = read(url);
  const doc = JSON.parse(raw) as FlowDoc;
  expect(doc.flowdoc, url.pathname).toBe(FLOWDOC_VERSION);
  expect(serialize(doc), `${url.pathname} is not in normal form`).toBe(raw);
  return doc;
}

describe("conformance/hcl/roundtrip", () => {
  const cases = dirs(new URL("roundtrip/", HCL));

  it("has the cases the contract names", () => {
    expect(cases.length).toBeGreaterThanOrEqual(12);
  });

  for (const name of cases) {
    const dir = new URL(`roundtrip/${name}/`, HCL);

    it(`${name}: a normal-form document, bindings to its references, and a golden naming only catalog blocks`, () => {
      const spec = JSON.parse(read(new URL("case.json", dir))) as CaseFile;
      expect(spec.description.length).toBeGreaterThan(0);
      expect(["pass", "fail", "skip"]).toContain(spec.validate ?? "skip");
      const doc = normalDoc(new URL(spec.doc, dir));
      const keys = refKeys(doc);
      for (const key of keys) expect(key).toMatch(KEY);

      const bindings = JSON.parse(read(new URL("bindings.json", dir))) as Record<string, string>;
      for (const key of Object.keys(bindings)) {
        expect(keys, `binding ${key} has no reference in the document`).toContain(key);
        expect(bindings[key]).not.toContain("arn:aws:");
      }

      const tf = read(new URL("expected.flow.tf", dir));
      expect(BANNER.exec(tf)?.[1]).toBe(spec.doc.split("/").pop());
      const resource =
        doc.kind === "module" ? "flowascode_contact_flow_module" : "flowascode_contact_flow";
      expect(tf.match(/^resource /gm)).toHaveLength(1);
      expect(tf).toContain(`resource "${resource}" "`);
      for (const block of blockNames(tf)) {
        if (STRUCTURAL.has(block)) continue;
        expect(BLOCKS, `sub-block ${block}`).toContain(block);
      }
      // Every action once, every reference key in the refs map (bound or
      // null), every binding written as given, and no literal ARN.
      for (const a of doc.content.Actions) {
        expect(tf.match(new RegExp(`^    id +?= "${a.Identifier}"$`, "gm"))).toHaveLength(1);
      }
      for (const key of keys) {
        const bound = bindings[key];
        expect(tf).toMatch(
          new RegExp(
            `^    "${key}" += ${bound === undefined ? "null" : bound.replaceAll(".", "\\.")}$`,
            "m",
          ),
        );
      }
      expect(tf).not.toContain("arn:aws:");
    });
  }
});

describe("conformance/hcl/regenerate", () => {
  for (const name of dirs(new URL("regenerate/", HCL))) {
    const dir = new URL(`regenerate/${name}/`, HCL);
    it(`${name}: a document and two companions with their banners`, () => {
      normalDoc(new URL("doc.flowdoc.json", dir));
      for (const file of ["previous.flow.tf", "expected.flow.tf"]) {
        const tf = read(new URL(file, dir));
        // A previous file is the user's and may have lost the blank line
        // under the banner (keep-under-banner); what the writer produces has it.
        const banner = file === "previous.flow.tf" ? LOOSE_BANNER : BANNER;
        expect(banner.exec(tf)?.[1], `${name}/${file}`).toBe("doc.flowdoc.json");
        expect(tf).not.toContain("arn:aws:");
      }
    });
  }
});

const CODES = [
  "LITERAL_ARN",
  "REF_EXPRESSION_REFUSED",
  "REF_SUGAR_UNSUPPORTED_TYPE",
  "REF_KEY_MALFORMED",
  "UNKNOWN_BLOCK",
  "UNKNOWN_ATTRIBUTE",
  "MULTIPLE_TYPE_BLOCKS",
  "NO_TYPE_BLOCK",
  "DUPLICATE_ACTION_ID",
  "INVALID_IDENTIFIER",
  "POSITION_NOT_INTEGER",
  "START_UNKNOWN",
  "NON_LITERAL_VALUE",
  "LONE_SURROGATE",
  "LABEL_MISMATCH",
  "SECOND_RESOURCE",
  "COUNT_OR_FOR_EACH",
  "MODULE_WITH_TYPE",
  "FLOW_WITH_SETTINGS",
  "UNKNOWN_LINT_RULE",
  "DUPLICATE_ATTRIBUTE",
];

describe("conformance/hcl/README.md", () => {
  const readme = read(new URL("README.md", HCL));
  it("lists exactly the error codes the refuse cases may name", () => {
    const section = readme.slice(readme.indexOf("## Error codes"));
    const listed = section.slice(0, section.indexOf("The provider puts"));
    expect([...listed.matchAll(/`([A-Z_]+)`/g)].map((m) => m[1])).toEqual(CODES);
  });
});

describe("conformance/hcl/parse and refuse", () => {
  for (const name of dirs(new URL("parse/", HCL))) {
    const dir = new URL(`parse/${name}/`, HCL);
    it(`parse/${name}: an input, a normal-form document and a sidecar`, () => {
      normalDoc(new URL("expected.flowdoc.json", dir));
      const sidecar = JSON.parse(read(new URL("expected.sidecar.json", dir))) as object;
      for (const key of ["refs", "lint", "tags", "instanceId", "normalized"]) {
        expect(sidecar).toHaveProperty(key);
      }
      expect(read(new URL("input.flow.tf", dir))).not.toContain("arn:aws:");
    });
  }
  it("has a refuse case for every error code", () => {
    const named = new Set(
      dirs(new URL("refuse/", HCL)).map(
        (name) =>
          (JSON.parse(read(new URL(`refuse/${name}/expected-error.json`, HCL))) as { code: string })
            .code,
      ),
    );
    expect(CODES.filter((c) => !named.has(c))).toEqual([]);
  });
  it("has parse cases", () => {
    expect(dirs(new URL("parse/", HCL)).length).toBeGreaterThanOrEqual(12);
  });
  for (const name of dirs(new URL("refuse/", HCL))) {
    const dir = new URL(`refuse/${name}/`, HCL);
    it(`refuse/${name}: names a contract code`, () => {
      const err = JSON.parse(read(new URL("expected-error.json", dir))) as { code: string };
      expect(CODES).toContain(err.code);
      expect(existsSync(new URL("input.flow.tf", dir))).toBe(true);
    });
  }
});
