/*
 * Copyright 2026 The flow-as-code Authors
 * SPDX-License-Identifier: Apache-2.0
 */
// The one place the npm package names are written down as values.
//
// Everything that embeds a package name in its output, rather than importing
// it, reads it from here: codegen's default import, the cdk stack scaffold,
// the tf "generated by" banner, and the CLI's studio asset resolution. A
// rename is then one edit to PACKAGE_SCOPE plus the package.json files, and a
// test in core keeps this file honest against those manifests.
//
// The hosted demo build (docs/05-hosted-demo.md) aliases this module to a
// neutral placeholder so no package name reaches the deployed artifact.

/** The npm scope every package publishes under. */
export const PACKAGE_SCOPE = "@flow-as-code";

/** Published package names, keyed by their short names. */
export const PACKAGE_NAMES = {
  core: `${PACKAGE_SCOPE}/core`,
  cdk: `${PACKAGE_SCOPE}/cdk`,
  cli: `${PACKAGE_SCOPE}/cli`,
  tf: `${PACKAGE_SCOPE}/tf`,
  studio: `${PACKAGE_SCOPE}/studio`,
} as const;
