/*
 * Copyright 2026 The flow-as-code Authors
 * SPDX-License-Identifier: Apache-2.0
 */
// @vitest-environment happy-dom
//
// A FlowDoc another generator owns (meta.generator naming something other
// than core@ or cli@, the two forms docs/01-flowdoc-spec.md gives): the
// studio shows which generator, and asks once before the first edit, saying
// the next run will overwrite it. Nothing is written to the document for it.

import type { FlowDoc } from "@flow-as-code/core";
import { afterEach, beforeAll, describe, expect, it } from "vitest";
import { App } from "../src/App.js";
import { foreignGenerator } from "../src/model/generated.js";
import { MemoryStore } from "../src/store/memoryStore.js";
import {
  button,
  click,
  installDomStubs,
  present,
  query,
  render,
  testId,
  typeAndBlur,
  unmount,
} from "./appHarness.js";
import { demoDoc } from "./helpers.js";

beforeAll(installDomStubs);
afterEach(unmount);

const GENERATOR = "generators/districts.ts@1";

function generatedDoc(generator: string | undefined): FlowDoc {
  const doc = demoDoc();
  if (generator === undefined) delete doc.meta;
  else doc.meta = { ...doc.meta, generator };
  return doc;
}

async function renderWith(generator: string | undefined): Promise<void> {
  await render(<App store={new MemoryStore("opened", [generatedDoc(generator)])} />);
}

const dialog = () => query('[data-testid="generated-edit-dialog"]');
const badge = () => query('[data-testid="generated-badge"]');
const welcomeText = () => testId<HTMLTextAreaElement>("message-body").value;

describe("foreignGenerator", () => {
  it("names a generator that is not this toolchain's own stamp", () => {
    expect(foreignGenerator(generatedDoc(GENERATOR))).toBe(GENERATOR);
    expect(foreignGenerator(generatedDoc("core@0.2"))).toBeUndefined();
    expect(foreignGenerator(generatedDoc("cli@0.2.1"))).toBeUndefined();
    expect(foreignGenerator(generatedDoc(undefined))).toBeUndefined();
    expect(foreignGenerator(generatedDoc(""))).toBeUndefined();
    expect(foreignGenerator(null)).toBeUndefined();
  });
});

describe("a generated document in the studio", () => {
  it("is marked with its generator, and a document of this toolchain's is not", async () => {
    await renderWith(GENERATOR);
    expect(present('[data-testid="generated-badge"]').textContent).toBe(
      `Generated by ${GENERATOR}`,
    );
    unmount();
    await renderWith("cli@0.2.1");
    expect(badge()).toBeNull();
  });

  it("asks before the first edit, saying the next run overwrites it, and applies nothing until told to", async () => {
    await renderWith(GENERATOR);
    await click(present('[data-testid="node-welcome"]'));
    const before = welcomeText();
    expect(dialog()).toBeNull();

    await typeAndBlur(testId<HTMLTextAreaElement>("message-body"), "Edited on the canvas.");
    const asked = present('[data-testid="generated-edit-dialog"]');
    expect(asked.textContent).toContain(GENERATOR);
    expect(asked.textContent).toContain("the next run of it will overwrite");
    // The edit is held, not applied: nothing is dirty yet.
    expect(document.body.textContent).not.toContain("unsaved changes");

    // "Keep it as generated" drops the edit. The inspector keeps its draft
    // until the selection moves, so another block is selected first and the
    // value read back is the document's.
    await click(button("generated-edit-cancel"));
    expect(dialog()).toBeNull();
    await click(present('[data-testid="node-hang-up"]'));
    await click(present('[data-testid="node-welcome"]'));
    expect(welcomeText()).toBe(before);
    expect(document.body.textContent).not.toContain("unsaved changes");

    // "Edit anyway" applies it, and the document is not asked about again.
    await typeAndBlur(testId<HTMLTextAreaElement>("message-body"), "Edited on the canvas.");
    present('[data-testid="generated-edit-dialog"]');
    await click(button("generated-edit-confirm"));
    expect(dialog()).toBeNull();
    expect(welcomeText()).toBe("Edited on the canvas.");
    expect(document.body.textContent).toContain("unsaved changes");
    await typeAndBlur(testId<HTMLTextAreaElement>("message-body"), "Edited twice.");
    expect(dialog()).toBeNull();
    expect(welcomeText()).toBe("Edited twice.");
  });

  it("never asks for a document this toolchain generated", async () => {
    await renderWith("cli@0.2.1");
    await click(present('[data-testid="node-welcome"]'));
    await typeAndBlur(testId<HTMLTextAreaElement>("message-body"), "Edited on the canvas.");
    expect(dialog()).toBeNull();
    expect(welcomeText()).toBe("Edited on the canvas.");
  });
});
