#!/usr/bin/env node
/*
 * Copyright 2026 The flow-as-code Authors
 * SPDX-License-Identifier: Apache-2.0
 */

// Writes the vector logo files the site publishes.
//
//   node design/build-logo.mjs
//
//   site/mark.svg      the mark alone, ink, following the reader's theme
//   site/favicon.svg   the same mark in the icon green, for a browser tab
//   site/logo.svg      the lockup for a light background
//   site/logo-dark.svg the lockup for a dark background
//
// The raster files (og.png, logo.png, apple-touch-icon.png, favicon.ico) are
// drawn in a browser canvas by design/build-raster.mjs, because this repository
// has no image dependency and is not about to grow one to draw four pictures.
//
// Everything here is derived: the geometry from design/mark.mjs, design/
// wordmark.mjs and design/lockup.mjs, the colours from design/palette.mjs. To
// change the mark, change the paths in mark.mjs and run this. Nothing in site/
// is edited by hand.

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import { MARK_LABEL, MARK_PATHS, MARK_SIZE, markPaths, markSvg } from "./mark.mjs";
import { lockup } from "./lockup.mjs";
import { PALETTE } from "./palette.mjs";
import { WORDMARK_FACE, WORDMARK_PATH, WORDMARK_TEXT } from "./wordmark.mjs";

const ROOT = join(fileURLToPath(new URL(".", import.meta.url)), "..");
const SITE = join(ROOT, "site");

/** The lockup as a standalone SVG, at a fixed pair of colours. */
function lockupSvg({ markFill, wordFill, height = 40 }) {
  const box = lockup(100);
  const width = Number(((box.width * height) / box.height).toFixed(2));
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${String(box.width)} ${String(box.height)}" width="${String(width)}" height="${String(height)}" role="img" aria-label="${MARK_LABEL}">
  <title>${MARK_LABEL}</title>
  <!-- The wordmark is "${WORDMARK_TEXT}" in ${WORDMARK_FACE}, converted to
       outlines by design/build-wordmark.mjs so it is the same shape on every
       machine. Generated by design/build-logo.mjs; do not edit by hand. -->
  <g fill="${markFill}" transform="translate(${String(box.markX)} ${String(box.markY)}) scale(${String(box.markScale)})">
${markPaths("    ")}
  </g>
  <path fill="${wordFill}" transform="translate(${String(box.wordX)} ${String(box.baseline)})" d="${WORDMARK_PATH}" />
</svg>
`;
}

function main() {
  const files = [
    [
      "mark.svg",
      markSvg({ light: PALETTE.INK, dark: PALETTE.INK_DARK, size: MARK_SIZE * 4 }),
      "the mark alone, in ink, following the reader's theme",
    ],
    [
      "favicon.svg",
      markSvg({ light: PALETTE.ACCENT, dark: PALETTE.ACCENT_DARK }),
      "the tab icon, at its design size",
    ],
    [
      "logo.svg",
      lockupSvg({ markFill: PALETTE.ACCENT, wordFill: PALETTE.INK }),
      "the lockup on a light background",
    ],
    [
      "logo-dark.svg",
      lockupSvg({ markFill: PALETTE.ACCENT_DARK, wordFill: PALETTE.INK_DARK }),
      "the lockup on a dark background",
    ],
  ];

  for (const [name, contents, what] of files) {
    writeFileSync(join(SITE, name), contents);
    console.log(`build-logo: site/${name} (${what}), ${String(contents.length)} bytes`);
  }
  const box = lockup(100);
  console.log(
    `build-logo: mark ${String(MARK_PATHS.length)} paths on a ${String(MARK_SIZE)} grid; ` +
      `lockup ${String(box.width)} by ${String(box.height)}.`,
  );
}

main();
