# Generated by @flow-as-code/hcl from casefield-key.flowdoc.json.
# Edits to structure regenerate; comments marked @keep survive.

resource "flowascode_contact_flow" "casefield_key" {
  instance_id = var.connect_instance_id
  name        = "casefield-key"
  type        = "CONTACT_FLOW"

  refs = {
    "assistant:agent-help"         = awscc_wisdom_assistant.agent_help.assistant_arn
    "casefield:priority"           = awscc_connectcases_field.priority.field_id
    "casefield:summary"            = awscc_connectcases_field.summary.field_id
    "casetemplate:billing-dispute" = awscc_connectcases_template.billing_dispute.template_id
    "flow:task-line"               = flowascode_contact_flow.task_line.arn
    "phonenumber:main-did"         = aws_connect_phone_number.main_did.arn
    "tasktemplate:follow-up"       = awscc_connect_task_template.follow_up.arn
  }

  action {
    id   = "open-case"
    next = "read-case"
    generic {
      type = "CreateCase"
      parameters = jsonencode({
        CaseRequestFields = {
          "$${cdref:casefield:priority}" = "high"
          "$${cdref:casefield:summary}"  = "$.Attributes.summary"
        }
        CaseTemplateId    = "$${cdref:casetemplate:billing-dispute}"
        LinkContactToCase = "true"
      })
    }
    error {
      type = "ContactNotLinked"
      next = "hang-up"
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
  }

  action {
    id   = "read-case"
    next = "follow-up"
    generic {
      type = "GetCase"
      parameters = jsonencode({
        CaseResponseFields = ["$${cdref:casefield:priority}"]
        CustomerId         = "$.Customer.ProfileId"
        GetLastUpdatedCase = "true"
        LinkContactToCase  = "false"
      })
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
    position {
      x = 340
      y = 20
    }
  }

  action {
    id   = "follow-up"
    next = "assist"
    generic {
      type = "CreateTask"
      parameters = jsonencode({
        ContactFlowId  = "$${cdref:flow:task-line}"
        Name           = "Follow up"
        TaskTemplateId = "$${cdref:tasktemplate:follow-up}"
      })
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
    position {
      x = 660
      y = 20
    }
  }

  action {
    id   = "assist"
    next = "text-back"
    generic {
      type = "CreateWisdomSession"
      parameters = jsonencode({
        WisdomAssistantArn = "$${cdref:assistant:agent-help}"
      })
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
    position {
      x = 980
      y = 20
    }
  }

  action {
    id   = "text-back"
    next = "hang-up"
    generic {
      type = "StartOutboundChatContact"
      parameters = jsonencode({
        ContactFlowArn = "$${cdref:flow:task-line}"
        ContactSubtype = "connect:SMS"
        DestinationEndpoint = {
          Address = "$.CustomerEndpoint.Address"
          Type    = "TELEPHONE_NUMBER"
        }
        SourceEndpoint = {
          Address = "$${cdref:phonenumber:main-did}"
          Type    = "CONNECT_PHONENUMBER_ARN"
        }
      })
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
    position {
      x = 1300
      y = 20
    }
  }

  action {
    id = "hang-up"
    disconnect_participant {}
    position {
      x = 1620
      y = 20
    }
  }
}
