// Generated by @flow-as-code/core codegen from case-intake.flowdoc.json.
// Edits to structure regenerate; comments marked @keep survive.

import { DisconnectParticipant, Flow, GenericBlock } from "@flow-as-code/core";

export function caseIntake(): Flow {
  return new Flow({
    name: "case-intake",
    displayName: "Case Intake",
    connectType: "CONTACT_FLOW",
  }).add(
    new GenericBlock({
      id: "open-case",
      type: "CreateCase",
      parameters: {
        CaseRequestFields: { "ffff0000-0000-4000-8000-000000000001": "high" },
        CaseTemplateId: "${cdref:casetemplate:billing-dispute}",
        LinkContactToCase: "false",
      },
      next: "read-case",
      errors: [{ errorType: "NoMatchingError", target: "hang-up" }],
    }),
    new GenericBlock({
      id: "read-case",
      type: "GetCase",
      parameters: {
        CaseResponseFields: ["${cdref:casefield:priority}"],
        CustomerId: "$.Customer.ProfileId",
        GetLastUpdatedCase: "true",
        LinkContactToCase: "false",
      },
      next: "assist",
      errors: [{ errorType: "NoMatchingError", target: "hang-up" }],
    }),
    new GenericBlock({
      id: "assist",
      type: "CreateWisdomSession",
      parameters: { WisdomAssistantArn: "${cdref:assistant:agent-help}" },
      next: "text-back",
      errors: [{ errorType: "NoMatchingError", target: "hang-up" }],
    }),
    new GenericBlock({
      id: "text-back",
      type: "StartOutboundChatContact",
      parameters: {
        ContactFlowArn: "${cdref:flow:task-follow-up}",
        ContactSubtype: "connect:SMS",
        DestinationEndpoint: { Address: "$.CustomerEndpoint.Address", Type: "TELEPHONE_NUMBER" },
        SourceEndpoint: {
          Address: "${cdref:phonenumber:main-did}",
          Type: "CONNECT_PHONENUMBER_ARN",
        },
      },
      next: "hang-up",
      errors: [{ errorType: "NoMatchingError", target: "hang-up" }],
    }),
    new DisconnectParticipant({ id: "hang-up" }),
  );
}
