// Generated by @flow-as-code/core codegen from task-follow-up.flowdoc.json.
// Edits to structure regenerate; comments marked @keep survive.

import { DisconnectParticipant, Flow, GenericBlock } from "@flow-as-code/core";

export function taskFollowUp(): Flow {
  return new Flow({
    name: "task-follow-up",
    displayName: "Task Follow Up",
    connectType: "CONTACT_FLOW",
  }).add(
    new GenericBlock({
      id: "create-task",
      type: "CreateTask",
      parameters: {
        ContactFlowId: "${cdref:flow:case-intake}",
        Name: "Follow up",
        TaskTemplateId: "${cdref:tasktemplate:follow-up}",
      },
      next: "hang-up",
      errors: [{ errorType: "NoMatchingError", target: "hang-up" }],
    }),
    new DisconnectParticipant({ id: "hang-up" }),
  );
}
