/*
 * Copyright 2026 The flow-as-code Authors
 * SPDX-License-Identifier: Apache-2.0
 */
// The vocabulary of conformance/hcl/README.md, written once. The reader, the
// writer and the emitter take their names from here, and the package's tests
// hold these tables to the contract's files.

import {
  PACKAGE_NAMES,
  actionCatalog,
  parseToken,
  type CatalogParameter,
  type RefType,
  type ModeledAction,
} from "@flow-as-code/core";

/**
 * The provider's registry address and the constraint emitted configuration
 * requires. `~> 0.1` is what the provider tutorials, the cookbook and every
 * example root ask for, and packages/hcl/src/emit.test.ts holds them to this
 * one string: it admits every 0.x release and excludes 1.0, the release that
 * may change the resource schema.
 */
export const FLOWASCODE_PROVIDER_SOURCE = "flow-as-code/flowascode";
export const FLOWASCODE_PROVIDER_CONSTRAINT = "~> 0.1";
/** The oldest Terraform the provider supports (state moves need 1.8; OpenTofu needs 1.10). */
export const HCL_VERSION_FLOOR = "1.8.0";

export const FLOW_RESOURCE = "flowascode_contact_flow";
export const MODULE_RESOURCE = "flowascode_contact_flow_module";
/** Rule 27: a module's snapshot and the alias a flow invokes it through. */
export const MODULE_VERSION_RESOURCE = "flowascode_contact_flow_module_version";
export const MODULE_ALIAS_RESOURCE = "flowascode_contact_flow_module_alias";

/** The banner's two lines (rule 2); the first names the document file. */
export function banner(fileName: string): string {
  return (
    `# Generated by ${PACKAGE_NAMES.hcl} from ${fileName}.\n` +
    "# Edits to structure regenerate; comments marked @keep survive.\n"
  );
}

/** Every error code the contract lists, in its order. */
export const ERROR_CODES = [
  "LITERAL_ARN",
  "REF_EXPRESSION_REFUSED",
  "REF_SUGAR_UNSUPPORTED_TYPE",
  "REF_KEY_MALFORMED",
  "UNKNOWN_BLOCK",
  "UNKNOWN_ATTRIBUTE",
  "MULTIPLE_TYPE_BLOCKS",
  "NO_TYPE_BLOCK",
  "DUPLICATE_ACTION_ID",
  "INVALID_IDENTIFIER",
  "POSITION_NOT_INTEGER",
  "START_UNKNOWN",
  "NON_LITERAL_VALUE",
  "LONE_SURROGATE",
  "LABEL_MISMATCH",
  "SECOND_RESOURCE",
  "COUNT_OR_FOR_EACH",
  "MODULE_WITH_TYPE",
  "FLOW_WITH_SETTINGS",
  "UNKNOWN_LINT_RULE",
  "DUPLICATE_ATTRIBUTE",
] as const;
export type ErrorCode = (typeof ERROR_CODES)[number];

/** Attributes a resource may set (rule 20), and the meta-arguments carried verbatim. */
export const RESOURCE_ATTRIBUTES = [
  "instance_id",
  "name",
  "display_name",
  "type",
  "description",
  "state",
  "start",
  "refs",
  "tags",
  "settings",
  "external_invocation_enabled",
  "depends_on",
  "provider",
] as const;
export const RESOURCE_BLOCKS = ["lint", "lifecycle", "action"] as const;

/** Blocks inside an action other than its typed sub-block. */
export const ACTION_BLOCKS = ["condition", "error", "position"] as const;

/** Resource addresses the TypeScript reader rewrites to a key (address-sugar.json). */
export const ADDRESS_SUGAR: readonly { prefix: string; type: string }[] = [
  { prefix: "aws_connect_queue", type: "queue" },
  { prefix: "aws_connect_hours_of_operation", type: "hours" },
  { prefix: "aws_lambda_function", type: "lambda" },
  { prefix: "data.aws_lambda_function", type: "lambda" },
  { prefix: "data.aws_connect_prompt", type: "prompt" },
  { prefix: "aws_connect_contact_flow", type: "flow" },
  { prefix: "flowascode_contact_flow", type: "flow" },
  { prefix: "aws_connect_contact_flow_module", type: "module" },
  { prefix: "flowascode_contact_flow_module", type: "module" },
];

/** A reference key: `queue:front-desk`, `module:survey@prod`, `view:form@1`. */
export const REF_KEY =
  /^(queue|hours|lambda|lex|prompt|flow|module|view):([a-z0-9]+(?:-[a-z0-9]+)*)(?:@([a-z0-9]+(?:-[a-z0-9]+)*))?$/;

/**
 * What a document may hold in a reference field for a typed sub-block to
 * write it (rule 10): a JSONPath, or a token of the field's type. The reader
 * accepts exactly these (as a key, the token, or a JSONPath), so anything else
 * goes to a generic block rather than into a file the reader would refuse.
 */
export function isRefFieldValue(value: string, type: RefType): boolean {
  if (value.startsWith("$.")) return true;
  const entry = parseToken(value);
  return entry !== undefined && entry.type === type;
}

/** The modeled catalog entries, by their HCL block name. */
export function entryByBlock(): Map<string, { type: string; entry: ModeledAction }> {
  const out = new Map<string, { type: string; entry: ModeledAction }>();
  for (const [type, entry] of Object.entries(actionCatalog.actions)) {
    if (entry.modeled) out.set(entry.block, { type, entry });
  }
  return out;
}

/** A parameter or field by its attribute name. */
export function byAttr(params: readonly CatalogParameter[]): Map<string, CatalogParameter> {
  return new Map(params.map((p) => [p.attr, p]));
}
