/*
 * Copyright 2026 The flow-as-code Authors
 * SPDX-License-Identifier: Apache-2.0
 */
// emitFlowascode: a set of FlowDocs as one configuration for the
// flow-as-code/flowascode provider, the `emit --target flowascode` output.
// It mirrors @flow-as-code/tf's emitTf (docs/03-tf-emitter.md) in what it
// takes and how it refuses, and differs in what it writes: each document is
// its own resource with its content as action blocks (conformance/hcl/
// README.md), so there are no templates and no shared locals, and each
// resource's refs map holds its own bindings.
//
// It writes flows.tf, variables.tf and versions.tf.example, never a
// per-document <name>.flow.tf, so an emit into a directory the studio serves
// cannot create a companion.

import {
  PACKAGE_NAMES,
  SLUG_PATTERN,
  collectRefs,
  lookupRefValue,
  migrateFlowDoc,
  parseToken,
  refKey,
  slugIdentifier,
  type FlowDoc,
} from "@flow-as-code/core";
import {
  FLOWASCODE_PROVIDER_CONSTRAINT,
  FLOWASCODE_PROVIDER_SOURCE,
  FLOW_RESOURCE,
  HCL_VERSION_FLOOR,
  MODULE_ALIAS_RESOURCE,
  MODULE_RESOURCE,
  MODULE_VERSION_RESOURCE,
} from "./contract.js";
import { format } from "./format.js";
import { quote } from "./quote.js";
import { resourceLines } from "./write.js";

/** Emission refused. Every problem found is listed, not just the first. */
export class EmitFlowascodeError extends Error {
  readonly problems: readonly string[];

  constructor(problems: readonly string[]) {
    super(`Cannot emit flowascode configuration:\n  - ${problems.join("\n  - ")}`);
    this.name = "EmitFlowascodeError";
    this.problems = problems;
  }
}

export interface EmitFlowascodeOptions {
  /**
   * Reference to terraform address expression, keyed as emitTf's is: the
   * token, the reference key, or the `<type>_<name>_arn` variable name. Values
   * are HCL expressions, never literal ARNs. A reference this set resolves
   * itself ignores its entry; an entry matching no reference is ignored.
   */
  addressMap?: Record<string, string>;
  /**
   * Expression for every resource's `instance_id`. Defaults to
   * `var.connect_instance_id`, in which case variables.tf declares it.
   */
  instanceIdExpression?: string;
}

export interface EmitFlowascodeResult {
  /** Relative POSIX path to file content, sorted by path. */
  files: Record<string, string>;
}

const DEFAULT_INSTANCE_ID_EXPRESSION = "var.connect_instance_id";

const GENERATED_BY = [
  `# Generated by ${PACKAGE_NAMES.hcl}. Do not edit by hand: edit the`,
  "# FlowDocs and re-emit. See docs/06-terraform-provider.md.",
];

const ident = slugIdentifier;
const byString = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0);
const resourceType = (doc: FlowDoc): string =>
  doc.kind === "module" ? MODULE_RESOURCE : FLOW_RESOURCE;

/** The address map's expressions are pasted unevaluated, so they are checked first. */
function checkExpression(label: string, value: string, problems: string[]): void {
  if (value.trim() === "") {
    problems.push(`${label} is empty`);
    return;
  }
  if (/arn:aws/i.test(value)) {
    problems.push(`${label} is a literal ARN (${value}); map to a terraform address instead`);
  }
  if (/[\n\r]/.test(value))
    problems.push(`${label} spans multiple lines (${JSON.stringify(value)})`);
  if (/#|\/\/|\/\*/.test(value)) problems.push(`${label} contains a comment marker (${value})`);
}

function checkDocs(docs: readonly FlowDoc[]): FlowDoc[] {
  const problems: string[] = [];
  if (docs.length === 0) problems.push("no documents to emit");
  const seen = new Set<string>();
  for (const doc of docs) {
    if (!SLUG_PATTERN.test(doc.name)) {
      problems.push(`document name "${doc.name}" is not a slug`);
      continue;
    }
    if (doc.kind === "module" && doc.connectType !== "MODULE") {
      problems.push(`module "${doc.name}" has connectType ${doc.connectType}, expected MODULE`);
    }
    if (doc.kind === "flow" && doc.connectType === "MODULE") {
      problems.push(`flow "${doc.name}" has connectType MODULE; emit it as kind "module"`);
    }
    const address = `${resourceType(doc)}.${ident(doc.name)}`;
    if (seen.has(address)) problems.push(`two documents both emit ${address}`);
    seen.add(address);
  }
  if (problems.length > 0) throw new EmitFlowascodeError(problems);
  return [...docs].sort((a, b) => byString(a.name, b.name) || byString(a.kind, b.kind));
}

/** Aliases each emitted module is invoked through, from the references to it. */
function aliasesByModule(docs: readonly FlowDoc[]): Map<string, string[]> {
  const aliases = new Map<string, Set<string>>();
  for (const doc of docs) if (doc.kind === "module") aliases.set(doc.name, new Set());
  for (const doc of docs) {
    for (const entry of collectRefs(doc.content)) {
      if (entry.type === "module" && entry.alias !== undefined)
        aliases.get(entry.name)?.add(entry.alias);
    }
  }
  return new Map([...aliases].map(([name, set]) => [name, [...set].sort(byString)]));
}

/**
 * A document's refs bindings. The set resolves its own flows and modules (a
 * module by alias through the alias resource, rule 27); the address map
 * supplies the rest; what neither covers is written null under the TODO
 * comment, which the provider refuses at plan time naming the key.
 */
function bindingsFor(
  doc: FlowDoc,
  docs: readonly FlowDoc[],
  addressMap: Record<string, string>,
): Record<string, string | null> {
  const flows = new Set(docs.filter((d) => d.kind === "flow").map((d) => d.name));
  const modules = new Set(docs.filter((d) => d.kind === "module").map((d) => d.name));
  const out: Record<string, string | null> = {};
  for (const entry of collectRefs(doc.content)) {
    const key = refKey(entry);
    if (entry.type === "module" && modules.has(entry.name)) {
      out[key] =
        entry.alias === undefined
          ? `${MODULE_RESOURCE}.${ident(entry.name)}.arn`
          : `${MODULE_ALIAS_RESOURCE}.${ident(entry.name)}_${ident(entry.alias)}.arn`;
    } else if (entry.type === "flow" && flows.has(entry.name)) {
      out[key] = `${FLOW_RESOURCE}.${ident(entry.name)}.arn`;
    } else {
      out[key] = lookupRefValue(addressMap, entry) ?? null;
    }
  }
  return out;
}

function flowsTf(
  docs: readonly FlowDoc[],
  instanceId: string,
  addressMap: Record<string, string>,
): string {
  const aliases = aliasesByModule(docs);
  const out: string[] = [
    ...GENERATED_BY,
    "#",
    "# One resource per FlowDoc, applied by the flow-as-code/flowascode",
    "# provider. Provider, credential, and backend configuration is yours;",
    "# versions.tf.example lists what this needs.",
  ];
  for (const doc of docs) {
    out.push(
      "",
      ...resourceLines(doc, { instanceId, bindings: bindingsFor(doc, docs, addressMap) }),
    );
    if (doc.kind !== "module") continue;
    const versions = aliases.get(doc.name) ?? [];
    if (versions.length === 0) continue;
    const module = `${MODULE_RESOURCE}.${ident(doc.name)}`;
    out.push(
      "",
      "# A snapshot of the module's content, replaced when the content",
      "# changes, and the aliases the flows in this set invoke it through.",
      `resource "${MODULE_VERSION_RESOURCE}" ${quote(ident(doc.name))} {`,
      `  instance_id = ${instanceId}`,
      `  contact_flow_module_id = ${module}.contact_flow_module_id`,
      `  content_hash = ${module}.content_hash`,
      "}",
    );
    for (const alias of versions) {
      out.push(
        "",
        `resource "${MODULE_ALIAS_RESOURCE}" ${quote(`${ident(doc.name)}_${ident(alias)}`)} {`,
        `  instance_id = ${instanceId}`,
        `  contact_flow_module_id = ${module}.contact_flow_module_id`,
        `  name = ${quote(alias)}`,
        `  contact_flow_module_version = ${MODULE_VERSION_RESOURCE}.${ident(doc.name)}.version`,
        "}",
      );
    }
  }
  return format(`${out.join("\n")}\n`);
}

function variablesTf(): string {
  return format(
    [
      ...GENERATED_BY,
      "",
      'variable "connect_instance_id" {',
      `  description = ${quote("Identifier of the Amazon Connect instance that holds these flows.")}`,
      "  type = string",
      "}",
      "",
    ].join("\n"),
  );
}

function versionsExample(): string {
  return format(
    [
      ...GENERATED_BY,
      "#",
      "# Example only. This file is not loaded by terraform or tofu, which",
      "# read *.tf; copy what you need into your own configuration. No",
      "# provider credentials and no backend configuration are emitted.",
      "#",
      "# The provider moves state across resource types, which needs",
      "# Terraform 1.8 or OpenTofu 1.10.",
      "",
      "terraform {",
      `  required_version = ${quote(`>= ${HCL_VERSION_FLOOR}`)}`,
      "",
      "  required_providers {",
      "    flowascode = {",
      `      source = ${quote(FLOWASCODE_PROVIDER_SOURCE)}`,
      `      version = ${quote(FLOWASCODE_PROVIDER_CONSTRAINT)}`,
      "    }",
      "  }",
      "}",
      "",
    ].join("\n"),
  );
}

/**
 * A configuration for the flowascode provider from a set of FlowDocs. Pure
 * and deterministic: the same documents and options give byte-identical
 * files, every one a `terraform fmt` fixed point.
 */
export function emitFlowascode(
  docs: readonly FlowDoc[],
  options: EmitFlowascodeOptions = {},
): EmitFlowascodeResult {
  const ordered = checkDocs(docs.map((doc) => migrateFlowDoc(doc, "emitFlowascode")));
  const problems: string[] = [];
  const instanceId = options.instanceIdExpression ?? DEFAULT_INSTANCE_ID_EXPRESSION;
  if (options.instanceIdExpression !== undefined) {
    checkExpression("instanceIdExpression", options.instanceIdExpression, problems);
  }
  const addressMap = options.addressMap ?? {};
  for (const k of Object.keys(addressMap)) {
    if (k.startsWith("${") && parseToken(k) === undefined) {
      problems.push(`address map key "${k}" looks like a token but does not parse as one`);
    }
  }
  const used = new Set<string>();
  for (const doc of ordered) {
    for (const entry of collectRefs(doc.content)) {
      const v = lookupRefValue(addressMap, entry);
      if (v !== undefined && !used.has(entry.token)) {
        used.add(entry.token);
        checkExpression(`address for ${entry.token}`, v, problems);
      }
    }
  }
  if (problems.length > 0) throw new EmitFlowascodeError(problems);

  const files: Record<string, string> = {
    "flows.tf": flowsTf(ordered, instanceId, addressMap),
    "versions.tf.example": versionsExample(),
  };
  if (options.instanceIdExpression === undefined) files["variables.tf"] = variablesTf();
  return { files: Object.fromEntries(Object.entries(files).sort(([a], [b]) => byString(a, b))) };
}
