/*
 * Copyright 2026 The flow-as-code Authors
 * SPDX-License-Identifier: Apache-2.0
 */
// The question before the first edit of a document another generator owns
// (model/generated.ts). The reducer parks the edit in `pendingEdit` and shows
// this; "Edit anyway" applies it and stops asking for this document, "Keep it
// as generated" drops it. Nothing is written to the document either way.

import { generatedEditWarning } from "../model/generated.js";
import { useStudio } from "../state/studio.js";

export function GeneratedModal() {
  const { state, dispatch } = useStudio();
  if (state.pendingEdit === null || state.generator === null) return null;

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-labelledby="generated-edit-title"
      data-testid="generated-edit-dialog"
      className="absolute inset-0 z-30 flex items-center justify-center bg-neutral-900/40 p-6"
    >
      <div className="w-full max-w-md rounded border border-neutral-300 bg-white p-4 text-sm shadow-xl dark:border-neutral-600 dark:bg-neutral-900">
        <h2 id="generated-edit-title" className="font-semibold">
          Generated by {state.generator}
        </h2>
        <p className="mt-2 text-neutral-700 dark:text-neutral-300">
          {generatedEditWarning(state.generator)}
        </p>
        <div className="mt-4 flex justify-end gap-2">
          <button
            type="button"
            data-testid="generated-edit-cancel"
            className="rounded border border-neutral-300 px-3 py-1 hover:bg-neutral-100 dark:border-neutral-600 dark:hover:bg-neutral-800"
            onClick={() => dispatch({ type: "generated-edit", apply: false })}
          >
            Keep it as generated
          </button>
          <button
            type="button"
            data-testid="generated-edit-confirm"
            className="rounded bg-amber-600 px-3 py-1 text-white hover:bg-amber-700"
            onClick={() => dispatch({ type: "generated-edit", apply: true })}
          >
            Edit anyway
          </button>
        </div>
      </div>
    </div>
  );
}
